// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_challenges.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthChallenge = `-- name: ConsumeAuthChallenge :one
UPDATE auth_challenges
SET consumed_at = NOW()
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
  AND attempts < max_attempts
RETURNING id, auth_transaction_id, identifier, secret_hash, purpose, state, attempts, max_attempts, expires_at, consumed_at, created_at
`

func (q *Queries) ConsumeAuthChallenge(ctx context.Context, id uuid.UUID) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, consumeAuthChallenge, id)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.AuthTransactionID,
		&i.Identifier,
		&i.SecretHash,
		&i.Purpose,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthChallenge = `-- name: CreateAuthChallenge :one
INSERT INTO auth_challenges (
    auth_transaction_id,
    identifier,
    secret_hash,
    purpose,
    state,
    max_attempts,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, auth_transaction_id, identifier, secret_hash, purpose, state, attempts, max_attempts, expires_at, consumed_at, created_at
`

type CreateAuthChallengeParams struct {
	AuthTransactionID *uuid.UUID         `db:"auth_transaction_id" json:"auth_transaction_id"`
	Identifier        string             `db:"identifier" json:"identifier"`
	SecretHash        string             `db:"secret_hash" json:"secret_hash"`
	Purpose           string             `db:"purpose" json:"purpose"`
	State             []byte             `db:"state" json:"state"`
	MaxAttempts       int32              `db:"max_attempts" json:"max_attempts"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateAuthChallenge(ctx context.Context, arg CreateAuthChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, createAuthChallenge,
		arg.AuthTransactionID,
		arg.Identifier,
		arg.SecretHash,
		arg.Purpose,
		arg.State,
		arg.MaxAttempts,
		arg.ExpiresAt,
	)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.AuthTransactionID,
		&i.Identifier,
		&i.SecretHash,
		&i.Purpose,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAuthChallenges = `-- name: DeleteExpiredAuthChallenges :exec
DELETE FROM auth_challenges
WHERE expires_at <= NOW()
   OR consumed_at IS NOT NULL
`

func (q *Queries) DeleteExpiredAuthChallenges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthChallenges)
	return err
}

const getActiveAuthChallenge = `-- name: GetActiveAuthChallenge :one
SELECT id, auth_transaction_id, identifier, secret_hash, purpose, state, attempts, max_attempts, expires_at, consumed_at, created_at
FROM auth_challenges
WHERE auth_transaction_id = $1
  AND purpose = $2
  AND consumed_at IS NULL
  AND expires_at > NOW()
  AND attempts < max_attempts
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveAuthChallengeParams struct {
	AuthTransactionID *uuid.UUID `db:"auth_transaction_id" json:"auth_transaction_id"`
	Purpose           string     `db:"purpose" json:"purpose"`
}

func (q *Queries) GetActiveAuthChallenge(ctx context.Context, arg GetActiveAuthChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, getActiveAuthChallenge, arg.AuthTransactionID, arg.Purpose)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.AuthTransactionID,
		&i.Identifier,
		&i.SecretHash,
		&i.Purpose,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthChallengeByID = `-- name: GetAuthChallengeByID :one
SELECT id, auth_transaction_id, identifier, secret_hash, purpose, state, attempts, max_attempts, expires_at, consumed_at, created_at
FROM auth_challenges
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAuthChallengeByID(ctx context.Context, id uuid.UUID) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, getAuthChallengeByID, id)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.AuthTransactionID,
		&i.Identifier,
		&i.SecretHash,
		&i.Purpose,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAuthChallengeAttempts = `-- name: IncrementAuthChallengeAttempts :one
UPDATE auth_challenges
SET attempts = attempts + 1
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
  AND attempts < max_attempts
RETURNING id, auth_transaction_id, identifier, secret_hash, purpose, state, attempts, max_attempts, expires_at, consumed_at, created_at
`

func (q *Queries) IncrementAuthChallengeAttempts(ctx context.Context, id uuid.UUID) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, incrementAuthChallengeAttempts, id)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.AuthTransactionID,
		&i.Identifier,
		&i.SecretHash,
		&i.Purpose,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
