// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backoffice.sql

package sqlc

import "context"

const listBackofficeCalls = `-- name: ListBackofficeCalls :many
SELECT
    c.id::TEXT AS id,
    o.name AS organization_name,
    c.from_uri,
    c.to_uri,
    c.direction,
    c.state,
    GREATEST(
        0::BIGINT,
        COALESCE(
            EXTRACT(EPOCH FROM (COALESCE(c.ended_at, NOW()) - c.answered_at))::BIGINT,
            0::BIGINT
        )
    ) AS duration_seconds,
    to_char(c.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') AS created_at
FROM calls AS c
JOIN organizations AS o ON o.id = c.organization_id
ORDER BY c.created_at DESC
LIMIT 100
`

type ListBackofficeCallsRow struct {
	ID               string `db:"id" json:"id"`
	OrganizationName string `db:"organization_name" json:"organization_name"`
	FromUri          string `db:"from_uri" json:"from_uri"`
	ToUri            string `db:"to_uri" json:"to_uri"`
	Direction        string `db:"direction" json:"direction"`
	State            string `db:"state" json:"state"`
	DurationSeconds  int64  `db:"duration_seconds" json:"duration_seconds"`
	CreatedAt        string `db:"created_at" json:"created_at"`
}

func (q *Queries) ListBackofficeCalls(ctx context.Context) ([]ListBackofficeCallsRow, error) {
	rows, err := q.db.Query(ctx, listBackofficeCalls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackofficeCallsRow{}
	for rows.Next() {
		var i ListBackofficeCallsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationName,
			&i.FromUri,
			&i.ToUri,
			&i.Direction,
			&i.State,
			&i.DurationSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackofficeCarrierConnections = `-- name: ListBackofficeCarrierConnections :many
SELECT
    cc.id::TEXT AS id,
    COALESCE(o.name, 'Platform') AS organization_name,
    cc.name,
    cp.name AS provider_name,
    cc.scope,
    cc.status,
    cc.inbound_enabled,
    cc.max_cps,
    cc.max_concurrent_calls,
    COUNT(t.id)::BIGINT AS trunk_count
FROM carrier_connections AS cc
JOIN carrier_providers AS cp ON cp.id = cc.provider_id
LEFT JOIN organizations AS o ON o.id = cc.organization_id
LEFT JOIN trunks AS t ON t.carrier_connection_id = cc.id
GROUP BY
    cc.id,
    o.name,
    cc.name,
    cp.name,
    cc.scope,
    cc.status,
    cc.inbound_enabled,
    cc.max_cps,
    cc.max_concurrent_calls,
    cc.created_at
ORDER BY cc.created_at DESC
LIMIT 100
`

type ListBackofficeCarrierConnectionsRow struct {
	ID                 string `db:"id" json:"id"`
	OrganizationName   string `db:"organization_name" json:"organization_name"`
	Name               string `db:"name" json:"name"`
	ProviderName       string `db:"provider_name" json:"provider_name"`
	Scope              string `db:"scope" json:"scope"`
	Status             string `db:"status" json:"status"`
	InboundEnabled     bool   `db:"inbound_enabled" json:"inbound_enabled"`
	MaxCps             int32  `db:"max_cps" json:"max_cps"`
	MaxConcurrentCalls int32  `db:"max_concurrent_calls" json:"max_concurrent_calls"`
	TrunkCount         int64  `db:"trunk_count" json:"trunk_count"`
}

func (q *Queries) ListBackofficeCarrierConnections(ctx context.Context) ([]ListBackofficeCarrierConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listBackofficeCarrierConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackofficeCarrierConnectionsRow{}
	for rows.Next() {
		var i ListBackofficeCarrierConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationName,
			&i.Name,
			&i.ProviderName,
			&i.Scope,
			&i.Status,
			&i.InboundEnabled,
			&i.MaxCps,
			&i.MaxConcurrentCalls,
			&i.TrunkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackofficeCommercialAccounts = `-- name: ListBackofficeCommercialAccounts :many
SELECT
    o.id::TEXT AS organization_id,
    o.name AS organization_name,
    COALESCE(p.name, '—') AS plan_name,
    COALESCE(s.status, 'none') AS subscription_status,
    COALESCE(s.billing_provider, '—') AS billing_provider,
    COALESCE(
        to_char(s.renews_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI'),
        '—'
    ) AS renews_at
FROM organizations AS o
LEFT JOIN subscriptions AS s
    ON s.organization_id = o.id
   AND s.status IN ('active', 'past_due')
LEFT JOIN plans AS p ON p.id = s.plan_id
WHERE o.deleted_at IS NULL
ORDER BY o.created_at DESC
LIMIT 100
`

type ListBackofficeCommercialAccountsRow struct {
	OrganizationID     string `db:"organization_id" json:"organization_id"`
	OrganizationName   string `db:"organization_name" json:"organization_name"`
	PlanName           string `db:"plan_name" json:"plan_name"`
	SubscriptionStatus string `db:"subscription_status" json:"subscription_status"`
	BillingProvider    string `db:"billing_provider" json:"billing_provider"`
	RenewsAt           string `db:"renews_at" json:"renews_at"`
}

func (q *Queries) ListBackofficeCommercialAccounts(ctx context.Context) ([]ListBackofficeCommercialAccountsRow, error) {
	rows, err := q.db.Query(ctx, listBackofficeCommercialAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackofficeCommercialAccountsRow{}
	for rows.Next() {
		var i ListBackofficeCommercialAccountsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.OrganizationName,
			&i.PlanName,
			&i.SubscriptionStatus,
			&i.BillingProvider,
			&i.RenewsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackofficeOrganizations = `-- name: ListBackofficeOrganizations :many
SELECT
    o.id::TEXT AS id,
    o.name,
    o.status,
    COUNT(om.user_id) FILTER (WHERE om.status = 'active')::BIGINT AS member_count,
    COALESCE(p.name, '—') AS plan_name,
    to_char(o.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') AS created_at
FROM organizations AS o
LEFT JOIN organization_members AS om ON om.organization_id = o.id
LEFT JOIN subscriptions AS s
    ON s.organization_id = o.id
   AND s.status IN ('active', 'past_due')
LEFT JOIN plans AS p ON p.id = s.plan_id
WHERE o.deleted_at IS NULL
GROUP BY o.id, o.name, o.status, p.name, o.created_at
ORDER BY o.created_at DESC
LIMIT 100
`

type ListBackofficeOrganizationsRow struct {
	ID          string `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Status      string `db:"status" json:"status"`
	MemberCount int64  `db:"member_count" json:"member_count"`
	PlanName    string `db:"plan_name" json:"plan_name"`
	CreatedAt   string `db:"created_at" json:"created_at"`
}

func (q *Queries) ListBackofficeOrganizations(ctx context.Context) ([]ListBackofficeOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listBackofficeOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackofficeOrganizationsRow{}
	for rows.Next() {
		var i ListBackofficeOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.MemberCount,
			&i.PlanName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackofficePhoneNumbers = `-- name: ListBackofficePhoneNumbers :many
SELECT
    pn.id::TEXT AS id,
    o.name AS organization_name,
    pn.number,
    pn.country_code::TEXT AS country_code,
    pn.provisioning_mode,
    COALESCE(cp.name, 'BYOC') AS provider_name,
    pn.voice_enabled,
    pn.sms_enabled,
    pn.status,
    to_char(pn.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') AS created_at
FROM phone_numbers AS pn
JOIN organizations AS o ON o.id = pn.organization_id
LEFT JOIN carrier_providers AS cp ON cp.id = pn.provider_id
ORDER BY pn.created_at DESC
LIMIT 100
`

type ListBackofficePhoneNumbersRow struct {
	ID               string `db:"id" json:"id"`
	OrganizationName string `db:"organization_name" json:"organization_name"`
	Number           string `db:"number" json:"number"`
	CountryCode      string `db:"country_code" json:"country_code"`
	ProvisioningMode string `db:"provisioning_mode" json:"provisioning_mode"`
	ProviderName     string `db:"provider_name" json:"provider_name"`
	VoiceEnabled     bool   `db:"voice_enabled" json:"voice_enabled"`
	SmsEnabled       bool   `db:"sms_enabled" json:"sms_enabled"`
	Status           string `db:"status" json:"status"`
	CreatedAt        string `db:"created_at" json:"created_at"`
}

func (q *Queries) ListBackofficePhoneNumbers(ctx context.Context) ([]ListBackofficePhoneNumbersRow, error) {
	rows, err := q.db.Query(ctx, listBackofficePhoneNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackofficePhoneNumbersRow{}
	for rows.Next() {
		var i ListBackofficePhoneNumbersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationName,
			&i.Number,
			&i.CountryCode,
			&i.ProvisioningMode,
			&i.ProviderName,
			&i.VoiceEnabled,
			&i.SmsEnabled,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackofficeProviders = `-- name: ListBackofficeProviders :many
SELECT
    cp.id::TEXT AS id,
    cp.slug,
    cp.name,
    cp.adapter,
    cp.status,
    COUNT(DISTINCT cc.id)::BIGINT AS connection_count,
    COUNT(DISTINCT po.id) FILTER (
        WHERE po.state IN ('pending', 'provider_accepted')
    )::BIGINT AS pending_operation_count,
    COUNT(DISTINCT po.id) FILTER (
        WHERE po.state = 'failed'
    )::BIGINT AS failed_operation_count
FROM carrier_providers AS cp
LEFT JOIN carrier_connections AS cc ON cc.provider_id = cp.id
LEFT JOIN provider_operations AS po ON po.carrier_provider_id = cp.id
GROUP BY cp.id, cp.slug, cp.name, cp.adapter, cp.status, cp.created_at
ORDER BY cp.created_at DESC
`

type ListBackofficeProvidersRow struct {
	ID                    string `db:"id" json:"id"`
	Slug                  string `db:"slug" json:"slug"`
	Name                  string `db:"name" json:"name"`
	Adapter               string `db:"adapter" json:"adapter"`
	Status                string `db:"status" json:"status"`
	ConnectionCount       int64  `db:"connection_count" json:"connection_count"`
	PendingOperationCount int64  `db:"pending_operation_count" json:"pending_operation_count"`
	FailedOperationCount  int64  `db:"failed_operation_count" json:"failed_operation_count"`
}

func (q *Queries) ListBackofficeProviders(ctx context.Context) ([]ListBackofficeProvidersRow, error) {
	rows, err := q.db.Query(ctx, listBackofficeProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackofficeProvidersRow{}
	for rows.Next() {
		var i ListBackofficeProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Adapter,
			&i.Status,
			&i.ConnectionCount,
			&i.PendingOperationCount,
			&i.FailedOperationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackofficeTrunks = `-- name: ListBackofficeTrunks :many
SELECT
    t.id::TEXT AS id,
    COALESCE(o.name, 'Platform') AS organization_name,
    t.name,
    t.provisioning_mode,
    COALESCE(cp.name, '—') AS provider_name,
    t.direction,
    t.status,
    COUNT(te.id)::BIGINT AS endpoint_count
FROM trunks AS t
LEFT JOIN organizations AS o ON o.id = t.organization_id
LEFT JOIN carrier_connections AS cc ON cc.id = t.carrier_connection_id
LEFT JOIN carrier_providers AS cp ON cp.id = cc.provider_id
LEFT JOIN trunk_endpoints AS te ON te.trunk_id = t.id
GROUP BY
    t.id,
    o.name,
    t.name,
    t.provisioning_mode,
    cp.name,
    t.direction,
    t.status,
    t.created_at
ORDER BY t.created_at DESC
LIMIT 100
`

type ListBackofficeTrunksRow struct {
	ID               string `db:"id" json:"id"`
	OrganizationName string `db:"organization_name" json:"organization_name"`
	Name             string `db:"name" json:"name"`
	ProvisioningMode string `db:"provisioning_mode" json:"provisioning_mode"`
	ProviderName     string `db:"provider_name" json:"provider_name"`
	Direction        string `db:"direction" json:"direction"`
	Status           string `db:"status" json:"status"`
	EndpointCount    int64  `db:"endpoint_count" json:"endpoint_count"`
}

func (q *Queries) ListBackofficeTrunks(ctx context.Context) ([]ListBackofficeTrunksRow, error) {
	rows, err := q.db.Query(ctx, listBackofficeTrunks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackofficeTrunksRow{}
	for rows.Next() {
		var i ListBackofficeTrunksRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationName,
			&i.Name,
			&i.ProvisioningMode,
			&i.ProviderName,
			&i.Direction,
			&i.Status,
			&i.EndpointCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
