// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calls.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCall = `-- name: CreateCall :one
INSERT INTO calls (
    organization_id,
    application_id,
    direction,
    state,
    from_uri,
    to_uri,
    sip_call_id
) VALUES (
    $1,
    $2,
    $3,
    COALESCE($4, 'initiating'),
    $5,
    $6,
    $7
)
RETURNING id, organization_id, application_id, direction, state, from_uri, to_uri, sip_call_id, provider_id, started_at, answered_at, ended_at, hangup_reason, created_at, updated_at
`

type CreateCallParams struct {
	OrganizationID uuid.UUID   `db:"organization_id" json:"organization_id"`
	ApplicationID  *uuid.UUID  `db:"application_id" json:"application_id"`
	Direction      string      `db:"direction" json:"direction"`
	State          interface{} `db:"state" json:"state"`
	FromUri        string      `db:"from_uri" json:"from_uri"`
	ToUri          string      `db:"to_uri" json:"to_uri"`
	SipCallID      *string     `db:"sip_call_id" json:"sip_call_id"`
}

func (q *Queries) CreateCall(ctx context.Context, arg CreateCallParams) (Call, error) {
	row := q.db.QueryRow(ctx, createCall,
		arg.OrganizationID,
		arg.ApplicationID,
		arg.Direction,
		arg.State,
		arg.FromUri,
		arg.ToUri,
		arg.SipCallID,
	)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ApplicationID,
		&i.Direction,
		&i.State,
		&i.FromUri,
		&i.ToUri,
		&i.SipCallID,
		&i.ProviderID,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.HangupReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCall = `-- name: GetCall :one
SELECT id, organization_id, application_id, direction, state, from_uri, to_uri, sip_call_id, provider_id, started_at, answered_at, ended_at, hangup_reason, created_at, updated_at
FROM calls
WHERE organization_id = $1
  AND id = $2
LIMIT 1
`

type GetCallParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetCall(ctx context.Context, arg GetCallParams) (Call, error) {
	row := q.db.QueryRow(ctx, getCall, arg.OrganizationID, arg.ID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ApplicationID,
		&i.Direction,
		&i.State,
		&i.FromUri,
		&i.ToUri,
		&i.SipCallID,
		&i.ProviderID,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.HangupReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCallBySIPCallID = `-- name: GetCallBySIPCallID :one
SELECT id, organization_id, application_id, direction, state, from_uri, to_uri, sip_call_id, provider_id, started_at, answered_at, ended_at, hangup_reason, created_at, updated_at
FROM calls
WHERE organization_id = $1
  AND sip_call_id = $2
LIMIT 1
`

type GetCallBySIPCallIDParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	SipCallID      *string   `db:"sip_call_id" json:"sip_call_id"`
}

func (q *Queries) GetCallBySIPCallID(ctx context.Context, arg GetCallBySIPCallIDParams) (Call, error) {
	row := q.db.QueryRow(ctx, getCallBySIPCallID, arg.OrganizationID, arg.SipCallID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ApplicationID,
		&i.Direction,
		&i.State,
		&i.FromUri,
		&i.ToUri,
		&i.SipCallID,
		&i.ProviderID,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.HangupReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCalls = `-- name: ListCalls :many
SELECT id, organization_id, application_id, direction, state, from_uri, to_uri, sip_call_id, provider_id, started_at, answered_at, ended_at, hangup_reason, created_at, updated_at
FROM calls
WHERE organization_id = $1
  AND ($2::text IS NULL OR state = $2::text)
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type ListCallsParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	State          *string   `db:"state" json:"state"`
	PageOffset     int32     `db:"page_offset" json:"page_offset"`
	PageLimit      int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListCalls(ctx context.Context, arg ListCallsParams) ([]Call, error) {
	rows, err := q.db.Query(ctx, listCalls,
		arg.OrganizationID,
		arg.State,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Call{}
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ApplicationID,
			&i.Direction,
			&i.State,
			&i.FromUri,
			&i.ToUri,
			&i.SipCallID,
			&i.ProviderID,
			&i.StartedAt,
			&i.AnsweredAt,
			&i.EndedAt,
			&i.HangupReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCallActive = `-- name: MarkCallActive :one
UPDATE calls
SET state = 'active', updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
  AND state IN ('answered', 'ringing')
RETURNING id, organization_id, application_id, direction, state, from_uri, to_uri, sip_call_id, provider_id, started_at, answered_at, ended_at, hangup_reason, created_at, updated_at
`

type MarkCallActiveParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkCallActive(ctx context.Context, arg MarkCallActiveParams) (Call, error) {
	row := q.db.QueryRow(ctx, markCallActive, arg.OrganizationID, arg.ID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ApplicationID,
		&i.Direction,
		&i.State,
		&i.FromUri,
		&i.ToUri,
		&i.SipCallID,
		&i.ProviderID,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.HangupReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCallAnswered = `-- name: MarkCallAnswered :one
UPDATE calls
SET
    state = 'answered',
    answered_at = COALESCE(answered_at, NOW()),
    updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
  AND state IN ('initiating', 'ringing')
RETURNING id, organization_id, application_id, direction, state, from_uri, to_uri, sip_call_id, provider_id, started_at, answered_at, ended_at, hangup_reason, created_at, updated_at
`

type MarkCallAnsweredParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkCallAnswered(ctx context.Context, arg MarkCallAnsweredParams) (Call, error) {
	row := q.db.QueryRow(ctx, markCallAnswered, arg.OrganizationID, arg.ID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ApplicationID,
		&i.Direction,
		&i.State,
		&i.FromUri,
		&i.ToUri,
		&i.SipCallID,
		&i.ProviderID,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.HangupReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCallCancelled = `-- name: MarkCallCancelled :one
UPDATE calls
SET
    state = 'cancelled',
    ended_at = COALESCE(ended_at, NOW()),
    hangup_reason = COALESCE($1, hangup_reason),
    updated_at = NOW()
WHERE organization_id = $2
  AND id = $3
  AND state IN ('initiating', 'ringing')
RETURNING id, organization_id, application_id, direction, state, from_uri, to_uri, sip_call_id, provider_id, started_at, answered_at, ended_at, hangup_reason, created_at, updated_at
`

type MarkCallCancelledParams struct {
	HangupReason   *string   `db:"hangup_reason" json:"hangup_reason"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkCallCancelled(ctx context.Context, arg MarkCallCancelledParams) (Call, error) {
	row := q.db.QueryRow(ctx, markCallCancelled, arg.HangupReason, arg.OrganizationID, arg.ID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ApplicationID,
		&i.Direction,
		&i.State,
		&i.FromUri,
		&i.ToUri,
		&i.SipCallID,
		&i.ProviderID,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.HangupReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCallCompleted = `-- name: MarkCallCompleted :one
UPDATE calls
SET
    state = 'completed',
    ended_at = COALESCE(ended_at, NOW()),
    hangup_reason = COALESCE($1, hangup_reason),
    updated_at = NOW()
WHERE organization_id = $2
  AND id = $3
  AND state NOT IN ('completed', 'failed', 'cancelled')
RETURNING id, organization_id, application_id, direction, state, from_uri, to_uri, sip_call_id, provider_id, started_at, answered_at, ended_at, hangup_reason, created_at, updated_at
`

type MarkCallCompletedParams struct {
	HangupReason   *string   `db:"hangup_reason" json:"hangup_reason"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkCallCompleted(ctx context.Context, arg MarkCallCompletedParams) (Call, error) {
	row := q.db.QueryRow(ctx, markCallCompleted, arg.HangupReason, arg.OrganizationID, arg.ID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ApplicationID,
		&i.Direction,
		&i.State,
		&i.FromUri,
		&i.ToUri,
		&i.SipCallID,
		&i.ProviderID,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.HangupReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCallFailed = `-- name: MarkCallFailed :one
UPDATE calls
SET
    state = 'failed',
    ended_at = COALESCE(ended_at, NOW()),
    hangup_reason = COALESCE($1, hangup_reason),
    updated_at = NOW()
WHERE organization_id = $2
  AND id = $3
  AND state NOT IN ('completed', 'failed', 'cancelled')
RETURNING id, organization_id, application_id, direction, state, from_uri, to_uri, sip_call_id, provider_id, started_at, answered_at, ended_at, hangup_reason, created_at, updated_at
`

type MarkCallFailedParams struct {
	HangupReason   *string   `db:"hangup_reason" json:"hangup_reason"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkCallFailed(ctx context.Context, arg MarkCallFailedParams) (Call, error) {
	row := q.db.QueryRow(ctx, markCallFailed, arg.HangupReason, arg.OrganizationID, arg.ID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ApplicationID,
		&i.Direction,
		&i.State,
		&i.FromUri,
		&i.ToUri,
		&i.SipCallID,
		&i.ProviderID,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.HangupReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCallRinging = `-- name: MarkCallRinging :one
UPDATE calls
SET state = 'ringing', updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
  AND state = 'initiating'
RETURNING id, organization_id, application_id, direction, state, from_uri, to_uri, sip_call_id, provider_id, started_at, answered_at, ended_at, hangup_reason, created_at, updated_at
`

type MarkCallRingingParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkCallRinging(ctx context.Context, arg MarkCallRingingParams) (Call, error) {
	row := q.db.QueryRow(ctx, markCallRinging, arg.OrganizationID, arg.ID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ApplicationID,
		&i.Direction,
		&i.State,
		&i.FromUri,
		&i.ToUri,
		&i.SipCallID,
		&i.ProviderID,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.HangupReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCallState = `-- name: UpdateCallState :one
UPDATE calls
SET
    state = $1,
    updated_at = NOW()
WHERE organization_id = $2
  AND id = $3
RETURNING id, organization_id, application_id, direction, state, from_uri, to_uri, sip_call_id, provider_id, started_at, answered_at, ended_at, hangup_reason, created_at, updated_at
`

type UpdateCallStateParams struct {
	State          string    `db:"state" json:"state"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateCallState(ctx context.Context, arg UpdateCallStateParams) (Call, error) {
	row := q.db.QueryRow(ctx, updateCallState, arg.State, arg.OrganizationID, arg.ID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ApplicationID,
		&i.Direction,
		&i.State,
		&i.FromUri,
		&i.ToUri,
		&i.SipCallID,
		&i.ProviderID,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.HangupReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
