// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carrier_rates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCarrierRate = `-- name: CreateCarrierRate :one
INSERT INTO carrier_rates (
    plan_id,
    meter_id,
    carrier_provider_id,
    direction,
    country_code,
    network,
    currency,
    unit_amount_micros,
    unit_size,
    effective_from,
    effective_until,
    active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    COALESCE($9, 1),
    COALESCE($10, NOW()),
    $11,
    COALESCE($12, true)
)
RETURNING id, plan_id, meter_id, carrier_provider_id, direction, country_code, network, currency, unit_amount_micros, unit_size, effective_from, effective_until, active, created_at, updated_at
`

type CreateCarrierRateParams struct {
	PlanID            uuid.UUID          `db:"plan_id" json:"plan_id"`
	MeterID           uuid.UUID          `db:"meter_id" json:"meter_id"`
	CarrierProviderID *uuid.UUID         `db:"carrier_provider_id" json:"carrier_provider_id"`
	Direction         *string            `db:"direction" json:"direction"`
	CountryCode       *string            `db:"country_code" json:"country_code"`
	Network           *string            `db:"network" json:"network"`
	Currency          string             `db:"currency" json:"currency"`
	UnitAmountMicros  int64              `db:"unit_amount_micros" json:"unit_amount_micros"`
	UnitSize          interface{}        `db:"unit_size" json:"unit_size"`
	EffectiveFrom     interface{}        `db:"effective_from" json:"effective_from"`
	EffectiveUntil    pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	Active            interface{}        `db:"active" json:"active"`
}

func (q *Queries) CreateCarrierRate(ctx context.Context, arg CreateCarrierRateParams) (CarrierRate, error) {
	row := q.db.QueryRow(ctx, createCarrierRate,
		arg.PlanID,
		arg.MeterID,
		arg.CarrierProviderID,
		arg.Direction,
		arg.CountryCode,
		arg.Network,
		arg.Currency,
		arg.UnitAmountMicros,
		arg.UnitSize,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.Active,
	)
	var i CarrierRate
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.MeterID,
		&i.CarrierProviderID,
		&i.Direction,
		&i.CountryCode,
		&i.Network,
		&i.Currency,
		&i.UnitAmountMicros,
		&i.UnitSize,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCarrierRateByID = `-- name: GetCarrierRateByID :one
SELECT id, plan_id, meter_id, carrier_provider_id, direction, country_code, network, currency, unit_amount_micros, unit_size, effective_from, effective_until, active, created_at, updated_at
FROM carrier_rates
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCarrierRateByID(ctx context.Context, id uuid.UUID) (CarrierRate, error) {
	row := q.db.QueryRow(ctx, getCarrierRateByID, id)
	var i CarrierRate
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.MeterID,
		&i.CarrierProviderID,
		&i.Direction,
		&i.CountryCode,
		&i.Network,
		&i.Currency,
		&i.UnitAmountMicros,
		&i.UnitSize,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCarrierRatesByPlan = `-- name: ListCarrierRatesByPlan :many
SELECT id, plan_id, meter_id, carrier_provider_id, direction, country_code, network, currency, unit_amount_micros, unit_size, effective_from, effective_until, active, created_at, updated_at
FROM carrier_rates
WHERE plan_id = $1
ORDER BY effective_from DESC, created_at DESC
`

func (q *Queries) ListCarrierRatesByPlan(ctx context.Context, planID uuid.UUID) ([]CarrierRate, error) {
	rows, err := q.db.Query(ctx, listCarrierRatesByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CarrierRate{}
	for rows.Next() {
		var i CarrierRate
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.MeterID,
			&i.CarrierProviderID,
			&i.Direction,
			&i.CountryCode,
			&i.Network,
			&i.Currency,
			&i.UnitAmountMicros,
			&i.UnitSize,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCarrierRate = `-- name: ResolveCarrierRate :one
SELECT id, plan_id, meter_id, carrier_provider_id, direction, country_code, network, currency, unit_amount_micros, unit_size, effective_from, effective_until, active, created_at, updated_at
FROM carrier_rates
WHERE plan_id = $1
  AND meter_id = $2
  AND active = true
  AND effective_from <= $3
  AND (effective_until IS NULL OR effective_until > $3)
  AND (carrier_provider_id IS NULL OR carrier_provider_id = $4)
  AND (direction IS NULL OR direction = $5)
  AND (country_code IS NULL OR country_code = $6)
  AND (network IS NULL OR network = $7)
ORDER BY
    (carrier_provider_id IS NOT NULL)::int
    + (direction IS NOT NULL)::int
    + (country_code IS NOT NULL)::int
    + (network IS NOT NULL)::int DESC,
    effective_from DESC
LIMIT 1
`

type ResolveCarrierRateParams struct {
	PlanID            uuid.UUID          `db:"plan_id" json:"plan_id"`
	MeterID           uuid.UUID          `db:"meter_id" json:"meter_id"`
	AtTime            pgtype.Timestamptz `db:"at_time" json:"at_time"`
	CarrierProviderID *uuid.UUID         `db:"carrier_provider_id" json:"carrier_provider_id"`
	Direction         *string            `db:"direction" json:"direction"`
	CountryCode       *string            `db:"country_code" json:"country_code"`
	Network           *string            `db:"network" json:"network"`
}

func (q *Queries) ResolveCarrierRate(ctx context.Context, arg ResolveCarrierRateParams) (CarrierRate, error) {
	row := q.db.QueryRow(ctx, resolveCarrierRate,
		arg.PlanID,
		arg.MeterID,
		arg.AtTime,
		arg.CarrierProviderID,
		arg.Direction,
		arg.CountryCode,
		arg.Network,
	)
	var i CarrierRate
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.MeterID,
		&i.CarrierProviderID,
		&i.Direction,
		&i.CountryCode,
		&i.Network,
		&i.Currency,
		&i.UnitAmountMicros,
		&i.UnitSize,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCarrierRateActive = `-- name: SetCarrierRateActive :one
UPDATE carrier_rates
SET
    active = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, plan_id, meter_id, carrier_provider_id, direction, country_code, network, currency, unit_amount_micros, unit_size, effective_from, effective_until, active, created_at, updated_at
`

type SetCarrierRateActiveParams struct {
	Active bool      `db:"active" json:"active"`
	ID     uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) SetCarrierRateActive(ctx context.Context, arg SetCarrierRateActiveParams) (CarrierRate, error) {
	row := q.db.QueryRow(ctx, setCarrierRateActive, arg.Active, arg.ID)
	var i CarrierRate
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.MeterID,
		&i.CarrierProviderID,
		&i.Direction,
		&i.CountryCode,
		&i.Network,
		&i.Currency,
		&i.UnitAmountMicros,
		&i.UnitSize,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
