// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carrier_connections.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearCarrierConnectionOutboundAuth = `-- name: ClearCarrierConnectionOutboundAuth :exec
UPDATE carrier_connections
SET
    outbound_auth_method = 'none',
    auth_username = NULL,
    auth_secret_ciphertext = NULL,
    updated_at = NOW()
WHERE id = $1
  AND scope = 'organization'
  AND organization_id = $2
`

type ClearCarrierConnectionOutboundAuthParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	OrganizationID *uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ClearCarrierConnectionOutboundAuth(ctx context.Context, arg ClearCarrierConnectionOutboundAuthParams) error {
	_, err := q.db.Exec(ctx, clearCarrierConnectionOutboundAuth, arg.ID, arg.OrganizationID)
	return err
}

const createCarrierConnection = `-- name: CreateCarrierConnection :one
INSERT INTO carrier_connections (
    organization_id,
    provider_id,
    scope,
    name,
    status,
    outbound_auth_method,
    auth_username,
    auth_secret_ciphertext,
    inbound_enabled,
    inbound_auth_method,
    inbound_username,
    inbound_secret_ciphertext,
    max_cps,
    max_concurrent_calls,
    max_daily_minutes,
    codecs,
    supports_video,
    supports_fax
)
SELECT
    $1 AS organization_id,
    $2 AS provider_id,
    'organization' AS scope,
    $3 AS name,
    COALESCE($4, 'active') AS status,
    COALESCE($5, 'none') AS outbound_auth_method,
    $6 AS auth_username,
    $7 AS auth_secret_ciphertext,
    COALESCE($8, false) AS inbound_enabled,
    COALESCE($9, 'ip') AS inbound_auth_method,
    $10 AS inbound_username,
    $11 AS inbound_secret_ciphertext,
    COALESCE($12, 10) AS max_cps,
    COALESCE($13, 100) AS max_concurrent_calls,
    $14 AS max_daily_minutes,
    COALESCE($15, ARRAY['PCMU','PCMA']::TEXT[]) AS codecs,
    COALESCE($16, false) AS supports_video,
    COALESCE($17, false) AS supports_fax
FROM organizations AS o
JOIN carrier_providers AS cp ON cp.id = $2
WHERE o.id = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
  AND cp.status = 'active'
RETURNING id, organization_id, provider_id, scope, name, status, outbound_auth_method, auth_username, auth_secret_ciphertext, inbound_enabled, inbound_auth_method, inbound_username, inbound_secret_ciphertext, max_cps, max_concurrent_calls, max_daily_minutes, codecs, supports_video, supports_fax, created_at, updated_at
`

type CreateCarrierConnectionParams struct {
	OrganizationID          *uuid.UUID `db:"organization_id" json:"organization_id"`
	ProviderID              uuid.UUID  `db:"provider_id" json:"provider_id"`
	Name                    string     `db:"name" json:"name"`
	Status                  *string    `db:"status" json:"status"`
	OutboundAuthMethod      *string    `db:"outbound_auth_method" json:"outbound_auth_method"`
	AuthUsername            *string    `db:"auth_username" json:"auth_username"`
	AuthSecretCiphertext    *string    `db:"auth_secret_ciphertext" json:"auth_secret_ciphertext"`
	InboundEnabled          *bool      `db:"inbound_enabled" json:"inbound_enabled"`
	InboundAuthMethod       *string    `db:"inbound_auth_method" json:"inbound_auth_method"`
	InboundUsername         *string    `db:"inbound_username" json:"inbound_username"`
	InboundSecretCiphertext *string    `db:"inbound_secret_ciphertext" json:"inbound_secret_ciphertext"`
	MaxCps                  *int32     `db:"max_cps" json:"max_cps"`
	MaxConcurrentCalls      *int32     `db:"max_concurrent_calls" json:"max_concurrent_calls"`
	MaxDailyMinutes         *int64     `db:"max_daily_minutes" json:"max_daily_minutes"`
	Codecs                  []string   `db:"codecs" json:"codecs"`
	SupportsVideo           *bool      `db:"supports_video" json:"supports_video"`
	SupportsFax             *bool      `db:"supports_fax" json:"supports_fax"`
}

func (q *Queries) CreateCarrierConnection(ctx context.Context, arg CreateCarrierConnectionParams) (CarrierConnection, error) {
	row := q.db.QueryRow(ctx, createCarrierConnection,
		arg.OrganizationID,
		arg.ProviderID,
		arg.Name,
		arg.Status,
		arg.OutboundAuthMethod,
		arg.AuthUsername,
		arg.AuthSecretCiphertext,
		arg.InboundEnabled,
		arg.InboundAuthMethod,
		arg.InboundUsername,
		arg.InboundSecretCiphertext,
		arg.MaxCps,
		arg.MaxConcurrentCalls,
		arg.MaxDailyMinutes,
		arg.Codecs,
		arg.SupportsVideo,
		arg.SupportsFax,
	)
	var i CarrierConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.Scope,
		&i.Name,
		&i.Status,
		&i.OutboundAuthMethod,
		&i.AuthUsername,
		&i.AuthSecretCiphertext,
		&i.InboundEnabled,
		&i.InboundAuthMethod,
		&i.InboundUsername,
		&i.InboundSecretCiphertext,
		&i.MaxCps,
		&i.MaxConcurrentCalls,
		&i.MaxDailyMinutes,
		&i.Codecs,
		&i.SupportsVideo,
		&i.SupportsFax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCarrierConnectionSourceIP = `-- name: CreateCarrierConnectionSourceIP :one
INSERT INTO carrier_connection_source_ips (
    organization_id,
    carrier_connection_id,
    cidr
)
SELECT
    $1 AS organization_id,
    $2 AS carrier_connection_id,
    $3 AS cidr
FROM carrier_connections AS cc
WHERE cc.id = $2
  AND cc.scope = 'organization'
  AND cc.organization_id = $1
RETURNING id, organization_id, carrier_connection_id, cidr, created_at
`

type CreateCarrierConnectionSourceIPParams struct {
	OrganizationID      *uuid.UUID   `db:"organization_id" json:"organization_id"`
	CarrierConnectionID uuid.UUID    `db:"carrier_connection_id" json:"carrier_connection_id"`
	Cidr                netip.Prefix `db:"cidr" json:"cidr"`
}

func (q *Queries) CreateCarrierConnectionSourceIP(ctx context.Context, arg CreateCarrierConnectionSourceIPParams) (CarrierConnectionSourceIp, error) {
	row := q.db.QueryRow(ctx, createCarrierConnectionSourceIP, arg.OrganizationID, arg.CarrierConnectionID, arg.Cidr)
	var i CarrierConnectionSourceIp
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CarrierConnectionID,
		&i.Cidr,
		&i.CreatedAt,
	)
	return i, err
}

const createPlatformCarrierConnection = `-- name: CreatePlatformCarrierConnection :one
INSERT INTO carrier_connections (
    organization_id,
    provider_id,
    scope,
    name,
    status,
    outbound_auth_method,
    auth_username,
    auth_secret_ciphertext,
    inbound_enabled,
    inbound_auth_method,
    inbound_username,
    inbound_secret_ciphertext,
    max_cps,
    max_concurrent_calls,
    max_daily_minutes,
    codecs,
    supports_video,
    supports_fax
)
SELECT
    NULL::UUID AS organization_id,
    $1 AS provider_id,
    'platform' AS scope,
    $2 AS name,
    COALESCE($3, 'active') AS status,
    COALESCE($4, 'none') AS outbound_auth_method,
    $5 AS auth_username,
    $6 AS auth_secret_ciphertext,
    COALESCE($7, false) AS inbound_enabled,
    COALESCE($8, 'ip') AS inbound_auth_method,
    $9 AS inbound_username,
    $10 AS inbound_secret_ciphertext,
    COALESCE($11, 10) AS max_cps,
    COALESCE($12, 100) AS max_concurrent_calls,
    $13 AS max_daily_minutes,
    COALESCE($14, ARRAY['PCMU','PCMA']::TEXT[]) AS codecs,
    COALESCE($15, false) AS supports_video,
    COALESCE($16, false) AS supports_fax
FROM carrier_providers AS cp
WHERE cp.id = $1
  AND cp.status = 'active'
RETURNING id, organization_id, provider_id, scope, name, status, outbound_auth_method, auth_username, auth_secret_ciphertext, inbound_enabled, inbound_auth_method, inbound_username, inbound_secret_ciphertext, max_cps, max_concurrent_calls, max_daily_minutes, codecs, supports_video, supports_fax, created_at, updated_at
`

type CreatePlatformCarrierConnectionParams struct {
	ProviderID              uuid.UUID `db:"provider_id" json:"provider_id"`
	Name                    string    `db:"name" json:"name"`
	Status                  *string   `db:"status" json:"status"`
	OutboundAuthMethod      *string   `db:"outbound_auth_method" json:"outbound_auth_method"`
	AuthUsername            *string   `db:"auth_username" json:"auth_username"`
	AuthSecretCiphertext    *string   `db:"auth_secret_ciphertext" json:"auth_secret_ciphertext"`
	InboundEnabled          *bool     `db:"inbound_enabled" json:"inbound_enabled"`
	InboundAuthMethod       *string   `db:"inbound_auth_method" json:"inbound_auth_method"`
	InboundUsername         *string   `db:"inbound_username" json:"inbound_username"`
	InboundSecretCiphertext *string   `db:"inbound_secret_ciphertext" json:"inbound_secret_ciphertext"`
	MaxCps                  *int32    `db:"max_cps" json:"max_cps"`
	MaxConcurrentCalls      *int32    `db:"max_concurrent_calls" json:"max_concurrent_calls"`
	MaxDailyMinutes         *int64    `db:"max_daily_minutes" json:"max_daily_minutes"`
	Codecs                  []string  `db:"codecs" json:"codecs"`
	SupportsVideo           *bool     `db:"supports_video" json:"supports_video"`
	SupportsFax             *bool     `db:"supports_fax" json:"supports_fax"`
}

func (q *Queries) CreatePlatformCarrierConnection(ctx context.Context, arg CreatePlatformCarrierConnectionParams) (CarrierConnection, error) {
	row := q.db.QueryRow(ctx, createPlatformCarrierConnection,
		arg.ProviderID,
		arg.Name,
		arg.Status,
		arg.OutboundAuthMethod,
		arg.AuthUsername,
		arg.AuthSecretCiphertext,
		arg.InboundEnabled,
		arg.InboundAuthMethod,
		arg.InboundUsername,
		arg.InboundSecretCiphertext,
		arg.MaxCps,
		arg.MaxConcurrentCalls,
		arg.MaxDailyMinutes,
		arg.Codecs,
		arg.SupportsVideo,
		arg.SupportsFax,
	)
	var i CarrierConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.Scope,
		&i.Name,
		&i.Status,
		&i.OutboundAuthMethod,
		&i.AuthUsername,
		&i.AuthSecretCiphertext,
		&i.InboundEnabled,
		&i.InboundAuthMethod,
		&i.InboundUsername,
		&i.InboundSecretCiphertext,
		&i.MaxCps,
		&i.MaxConcurrentCalls,
		&i.MaxDailyMinutes,
		&i.Codecs,
		&i.SupportsVideo,
		&i.SupportsFax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCarrierConnectionSourceIP = `-- name: DeleteCarrierConnectionSourceIP :exec
DELETE FROM carrier_connection_source_ips AS src
USING carrier_connections AS cc
WHERE src.id = $1
  AND src.carrier_connection_id = $2
  AND src.organization_id = $3
  AND cc.id = src.carrier_connection_id
  AND cc.scope = 'organization'
  AND cc.organization_id = src.organization_id
`

type DeleteCarrierConnectionSourceIPParams struct {
	ID                  uuid.UUID  `db:"id" json:"id"`
	CarrierConnectionID uuid.UUID  `db:"carrier_connection_id" json:"carrier_connection_id"`
	OrganizationID      *uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) DeleteCarrierConnectionSourceIP(ctx context.Context, arg DeleteCarrierConnectionSourceIPParams) error {
	_, err := q.db.Exec(ctx, deleteCarrierConnectionSourceIP, arg.ID, arg.CarrierConnectionID, arg.OrganizationID)
	return err
}

const disableCarrierConnection = `-- name: DisableCarrierConnection :exec
UPDATE carrier_connections
SET
    status = 'disabled',
    updated_at = NOW()
WHERE id = $1
  AND scope = 'organization'
  AND organization_id = $2
  AND status = 'active'
`

type DisableCarrierConnectionParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	OrganizationID *uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) DisableCarrierConnection(ctx context.Context, arg DisableCarrierConnectionParams) error {
	_, err := q.db.Exec(ctx, disableCarrierConnection, arg.ID, arg.OrganizationID)
	return err
}

const enableCarrierConnection = `-- name: EnableCarrierConnection :exec
UPDATE carrier_connections
SET
    status = 'active',
    updated_at = NOW()
WHERE id = $1
  AND scope = 'organization'
  AND organization_id = $2
  AND status = 'disabled'
`

type EnableCarrierConnectionParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	OrganizationID *uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) EnableCarrierConnection(ctx context.Context, arg EnableCarrierConnectionParams) error {
	_, err := q.db.Exec(ctx, enableCarrierConnection, arg.ID, arg.OrganizationID)
	return err
}

const getCarrierConnectionByID = `-- name: GetCarrierConnectionByID :one
SELECT
    id,
    organization_id,
    provider_id,
    scope,
    name,
    status,
    outbound_auth_method,
    auth_username,
    auth_secret_ciphertext IS NOT NULL AS has_outbound_credentials,
    inbound_enabled,
    inbound_auth_method,
    inbound_username,
    inbound_secret_ciphertext IS NOT NULL AS has_inbound_credentials,
    max_cps,
    max_concurrent_calls,
    max_daily_minutes,
    codecs,
    supports_video,
    supports_fax,
    created_at,
    updated_at
FROM carrier_connections
WHERE id = $1
  AND scope = 'organization'
  AND organization_id = $2
LIMIT 1
`

type GetCarrierConnectionByIDParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	OrganizationID *uuid.UUID `db:"organization_id" json:"organization_id"`
}

type GetCarrierConnectionByIDRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	OrganizationID         *uuid.UUID         `db:"organization_id" json:"organization_id"`
	ProviderID             uuid.UUID          `db:"provider_id" json:"provider_id"`
	Scope                  string             `db:"scope" json:"scope"`
	Name                   string             `db:"name" json:"name"`
	Status                 string             `db:"status" json:"status"`
	OutboundAuthMethod     string             `db:"outbound_auth_method" json:"outbound_auth_method"`
	AuthUsername           *string            `db:"auth_username" json:"auth_username"`
	HasOutboundCredentials interface{}        `db:"has_outbound_credentials" json:"has_outbound_credentials"`
	InboundEnabled         bool               `db:"inbound_enabled" json:"inbound_enabled"`
	InboundAuthMethod      string             `db:"inbound_auth_method" json:"inbound_auth_method"`
	InboundUsername        *string            `db:"inbound_username" json:"inbound_username"`
	HasInboundCredentials  interface{}        `db:"has_inbound_credentials" json:"has_inbound_credentials"`
	MaxCps                 int32              `db:"max_cps" json:"max_cps"`
	MaxConcurrentCalls     int32              `db:"max_concurrent_calls" json:"max_concurrent_calls"`
	MaxDailyMinutes        *int64             `db:"max_daily_minutes" json:"max_daily_minutes"`
	Codecs                 []string           `db:"codecs" json:"codecs"`
	SupportsVideo          bool               `db:"supports_video" json:"supports_video"`
	SupportsFax            bool               `db:"supports_fax" json:"supports_fax"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetCarrierConnectionByID(ctx context.Context, arg GetCarrierConnectionByIDParams) (GetCarrierConnectionByIDRow, error) {
	row := q.db.QueryRow(ctx, getCarrierConnectionByID, arg.ID, arg.OrganizationID)
	var i GetCarrierConnectionByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.Scope,
		&i.Name,
		&i.Status,
		&i.OutboundAuthMethod,
		&i.AuthUsername,
		&i.HasOutboundCredentials,
		&i.InboundEnabled,
		&i.InboundAuthMethod,
		&i.InboundUsername,
		&i.HasInboundCredentials,
		&i.MaxCps,
		&i.MaxConcurrentCalls,
		&i.MaxDailyMinutes,
		&i.Codecs,
		&i.SupportsVideo,
		&i.SupportsFax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCarrierConnectionCredentials = `-- name: GetCarrierConnectionCredentials :one
SELECT
    outbound_auth_method,
    auth_username,
    auth_secret_ciphertext,
    inbound_auth_method,
    inbound_username,
    inbound_secret_ciphertext
FROM carrier_connections
WHERE id = $1
  AND scope = 'organization'
  AND organization_id = $2
  AND status = 'active'
LIMIT 1
`

type GetCarrierConnectionCredentialsParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	OrganizationID *uuid.UUID `db:"organization_id" json:"organization_id"`
}

type GetCarrierConnectionCredentialsRow struct {
	OutboundAuthMethod      string  `db:"outbound_auth_method" json:"outbound_auth_method"`
	AuthUsername            *string `db:"auth_username" json:"auth_username"`
	AuthSecretCiphertext    *string `db:"auth_secret_ciphertext" json:"auth_secret_ciphertext"`
	InboundAuthMethod       string  `db:"inbound_auth_method" json:"inbound_auth_method"`
	InboundUsername         *string `db:"inbound_username" json:"inbound_username"`
	InboundSecretCiphertext *string `db:"inbound_secret_ciphertext" json:"inbound_secret_ciphertext"`
}

func (q *Queries) GetCarrierConnectionCredentials(ctx context.Context, arg GetCarrierConnectionCredentialsParams) (GetCarrierConnectionCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getCarrierConnectionCredentials, arg.ID, arg.OrganizationID)
	var i GetCarrierConnectionCredentialsRow
	err := row.Scan(
		&i.OutboundAuthMethod,
		&i.AuthUsername,
		&i.AuthSecretCiphertext,
		&i.InboundAuthMethod,
		&i.InboundUsername,
		&i.InboundSecretCiphertext,
	)
	return i, err
}

const getPlatformCarrierConnectionByID = `-- name: GetPlatformCarrierConnectionByID :one
SELECT id, organization_id, provider_id, scope, name, status, outbound_auth_method, auth_username, auth_secret_ciphertext, inbound_enabled, inbound_auth_method, inbound_username, inbound_secret_ciphertext, max_cps, max_concurrent_calls, max_daily_minutes, codecs, supports_video, supports_fax, created_at, updated_at
FROM carrier_connections
WHERE id = $1
  AND scope = 'platform'
  AND organization_id IS NULL
LIMIT 1
`

func (q *Queries) GetPlatformCarrierConnectionByID(ctx context.Context, id uuid.UUID) (CarrierConnection, error) {
	row := q.db.QueryRow(ctx, getPlatformCarrierConnectionByID, id)
	var i CarrierConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.Scope,
		&i.Name,
		&i.Status,
		&i.OutboundAuthMethod,
		&i.AuthUsername,
		&i.AuthSecretCiphertext,
		&i.InboundEnabled,
		&i.InboundAuthMethod,
		&i.InboundUsername,
		&i.InboundSecretCiphertext,
		&i.MaxCps,
		&i.MaxConcurrentCalls,
		&i.MaxDailyMinutes,
		&i.Codecs,
		&i.SupportsVideo,
		&i.SupportsFax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformCarrierConnectionCredentials = `-- name: GetPlatformCarrierConnectionCredentials :one
SELECT
    outbound_auth_method,
    auth_username,
    auth_secret_ciphertext,
    inbound_auth_method,
    inbound_username,
    inbound_secret_ciphertext
FROM carrier_connections
WHERE id = $1
  AND scope = 'platform'
  AND organization_id IS NULL
  AND status = 'active'
LIMIT 1
`

type GetPlatformCarrierConnectionCredentialsRow struct {
	OutboundAuthMethod      string  `db:"outbound_auth_method" json:"outbound_auth_method"`
	AuthUsername            *string `db:"auth_username" json:"auth_username"`
	AuthSecretCiphertext    *string `db:"auth_secret_ciphertext" json:"auth_secret_ciphertext"`
	InboundAuthMethod       string  `db:"inbound_auth_method" json:"inbound_auth_method"`
	InboundUsername         *string `db:"inbound_username" json:"inbound_username"`
	InboundSecretCiphertext *string `db:"inbound_secret_ciphertext" json:"inbound_secret_ciphertext"`
}

func (q *Queries) GetPlatformCarrierConnectionCredentials(ctx context.Context, id uuid.UUID) (GetPlatformCarrierConnectionCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getPlatformCarrierConnectionCredentials, id)
	var i GetPlatformCarrierConnectionCredentialsRow
	err := row.Scan(
		&i.OutboundAuthMethod,
		&i.AuthUsername,
		&i.AuthSecretCiphertext,
		&i.InboundAuthMethod,
		&i.InboundUsername,
		&i.InboundSecretCiphertext,
	)
	return i, err
}

const listActiveCarrierConnectionsByOrganizationID = `-- name: ListActiveCarrierConnectionsByOrganizationID :many
SELECT
    id,
    organization_id,
    provider_id,
    scope,
    name,
    status,
    outbound_auth_method,
    auth_username,
    auth_secret_ciphertext IS NOT NULL AS has_outbound_credentials,
    inbound_enabled,
    inbound_auth_method,
    inbound_username,
    inbound_secret_ciphertext IS NOT NULL AS has_inbound_credentials,
    max_cps,
    max_concurrent_calls,
    max_daily_minutes,
    codecs,
    supports_video,
    supports_fax,
    created_at,
    updated_at
FROM carrier_connections
WHERE scope = 'organization'
  AND organization_id = $1
  AND status = 'active'
ORDER BY created_at DESC
`

type ListActiveCarrierConnectionsByOrganizationIDRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	OrganizationID         *uuid.UUID         `db:"organization_id" json:"organization_id"`
	ProviderID             uuid.UUID          `db:"provider_id" json:"provider_id"`
	Scope                  string             `db:"scope" json:"scope"`
	Name                   string             `db:"name" json:"name"`
	Status                 string             `db:"status" json:"status"`
	OutboundAuthMethod     string             `db:"outbound_auth_method" json:"outbound_auth_method"`
	AuthUsername           *string            `db:"auth_username" json:"auth_username"`
	HasOutboundCredentials interface{}        `db:"has_outbound_credentials" json:"has_outbound_credentials"`
	InboundEnabled         bool               `db:"inbound_enabled" json:"inbound_enabled"`
	InboundAuthMethod      string             `db:"inbound_auth_method" json:"inbound_auth_method"`
	InboundUsername        *string            `db:"inbound_username" json:"inbound_username"`
	HasInboundCredentials  interface{}        `db:"has_inbound_credentials" json:"has_inbound_credentials"`
	MaxCps                 int32              `db:"max_cps" json:"max_cps"`
	MaxConcurrentCalls     int32              `db:"max_concurrent_calls" json:"max_concurrent_calls"`
	MaxDailyMinutes        *int64             `db:"max_daily_minutes" json:"max_daily_minutes"`
	Codecs                 []string           `db:"codecs" json:"codecs"`
	SupportsVideo          bool               `db:"supports_video" json:"supports_video"`
	SupportsFax            bool               `db:"supports_fax" json:"supports_fax"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListActiveCarrierConnectionsByOrganizationID(ctx context.Context, organizationID *uuid.UUID) ([]ListActiveCarrierConnectionsByOrganizationIDRow, error) {
	rows, err := q.db.Query(ctx, listActiveCarrierConnectionsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCarrierConnectionsByOrganizationIDRow{}
	for rows.Next() {
		var i ListActiveCarrierConnectionsByOrganizationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProviderID,
			&i.Scope,
			&i.Name,
			&i.Status,
			&i.OutboundAuthMethod,
			&i.AuthUsername,
			&i.HasOutboundCredentials,
			&i.InboundEnabled,
			&i.InboundAuthMethod,
			&i.InboundUsername,
			&i.HasInboundCredentials,
			&i.MaxCps,
			&i.MaxConcurrentCalls,
			&i.MaxDailyMinutes,
			&i.Codecs,
			&i.SupportsVideo,
			&i.SupportsFax,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePlatformCarrierConnections = `-- name: ListActivePlatformCarrierConnections :many
SELECT id, organization_id, provider_id, scope, name, status, outbound_auth_method, auth_username, auth_secret_ciphertext, inbound_enabled, inbound_auth_method, inbound_username, inbound_secret_ciphertext, max_cps, max_concurrent_calls, max_daily_minutes, codecs, supports_video, supports_fax, created_at, updated_at
FROM carrier_connections
WHERE scope = 'platform'
  AND organization_id IS NULL
  AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListActivePlatformCarrierConnections(ctx context.Context) ([]CarrierConnection, error) {
	rows, err := q.db.Query(ctx, listActivePlatformCarrierConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CarrierConnection{}
	for rows.Next() {
		var i CarrierConnection
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProviderID,
			&i.Scope,
			&i.Name,
			&i.Status,
			&i.OutboundAuthMethod,
			&i.AuthUsername,
			&i.AuthSecretCiphertext,
			&i.InboundEnabled,
			&i.InboundAuthMethod,
			&i.InboundUsername,
			&i.InboundSecretCiphertext,
			&i.MaxCps,
			&i.MaxConcurrentCalls,
			&i.MaxDailyMinutes,
			&i.Codecs,
			&i.SupportsVideo,
			&i.SupportsFax,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarrierConnectionSourceIPs = `-- name: ListCarrierConnectionSourceIPs :many
SELECT src.id, src.organization_id, src.carrier_connection_id, src.cidr, src.created_at
FROM carrier_connection_source_ips AS src
JOIN carrier_connections AS cc
  ON cc.id = src.carrier_connection_id
 AND cc.organization_id = src.organization_id
WHERE src.carrier_connection_id = $1
  AND src.organization_id = $2
  AND cc.scope = 'organization'
ORDER BY src.cidr ASC
`

type ListCarrierConnectionSourceIPsParams struct {
	CarrierConnectionID uuid.UUID  `db:"carrier_connection_id" json:"carrier_connection_id"`
	OrganizationID      *uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ListCarrierConnectionSourceIPs(ctx context.Context, arg ListCarrierConnectionSourceIPsParams) ([]CarrierConnectionSourceIp, error) {
	rows, err := q.db.Query(ctx, listCarrierConnectionSourceIPs, arg.CarrierConnectionID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CarrierConnectionSourceIp{}
	for rows.Next() {
		var i CarrierConnectionSourceIp
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CarrierConnectionID,
			&i.Cidr,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarrierConnectionsByOrganizationID = `-- name: ListCarrierConnectionsByOrganizationID :many
SELECT
    id,
    organization_id,
    provider_id,
    scope,
    name,
    status,
    outbound_auth_method,
    auth_username,
    auth_secret_ciphertext IS NOT NULL AS has_outbound_credentials,
    inbound_enabled,
    inbound_auth_method,
    inbound_username,
    inbound_secret_ciphertext IS NOT NULL AS has_inbound_credentials,
    max_cps,
    max_concurrent_calls,
    max_daily_minutes,
    codecs,
    supports_video,
    supports_fax,
    created_at,
    updated_at
FROM carrier_connections
WHERE scope = 'organization'
  AND organization_id = $1
ORDER BY created_at DESC
`

type ListCarrierConnectionsByOrganizationIDRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	OrganizationID         *uuid.UUID         `db:"organization_id" json:"organization_id"`
	ProviderID             uuid.UUID          `db:"provider_id" json:"provider_id"`
	Scope                  string             `db:"scope" json:"scope"`
	Name                   string             `db:"name" json:"name"`
	Status                 string             `db:"status" json:"status"`
	OutboundAuthMethod     string             `db:"outbound_auth_method" json:"outbound_auth_method"`
	AuthUsername           *string            `db:"auth_username" json:"auth_username"`
	HasOutboundCredentials interface{}        `db:"has_outbound_credentials" json:"has_outbound_credentials"`
	InboundEnabled         bool               `db:"inbound_enabled" json:"inbound_enabled"`
	InboundAuthMethod      string             `db:"inbound_auth_method" json:"inbound_auth_method"`
	InboundUsername        *string            `db:"inbound_username" json:"inbound_username"`
	HasInboundCredentials  interface{}        `db:"has_inbound_credentials" json:"has_inbound_credentials"`
	MaxCps                 int32              `db:"max_cps" json:"max_cps"`
	MaxConcurrentCalls     int32              `db:"max_concurrent_calls" json:"max_concurrent_calls"`
	MaxDailyMinutes        *int64             `db:"max_daily_minutes" json:"max_daily_minutes"`
	Codecs                 []string           `db:"codecs" json:"codecs"`
	SupportsVideo          bool               `db:"supports_video" json:"supports_video"`
	SupportsFax            bool               `db:"supports_fax" json:"supports_fax"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListCarrierConnectionsByOrganizationID(ctx context.Context, organizationID *uuid.UUID) ([]ListCarrierConnectionsByOrganizationIDRow, error) {
	rows, err := q.db.Query(ctx, listCarrierConnectionsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCarrierConnectionsByOrganizationIDRow{}
	for rows.Next() {
		var i ListCarrierConnectionsByOrganizationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProviderID,
			&i.Scope,
			&i.Name,
			&i.Status,
			&i.OutboundAuthMethod,
			&i.AuthUsername,
			&i.HasOutboundCredentials,
			&i.InboundEnabled,
			&i.InboundAuthMethod,
			&i.InboundUsername,
			&i.HasInboundCredentials,
			&i.MaxCps,
			&i.MaxConcurrentCalls,
			&i.MaxDailyMinutes,
			&i.Codecs,
			&i.SupportsVideo,
			&i.SupportsFax,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformCarrierConnections = `-- name: ListPlatformCarrierConnections :many
SELECT id, organization_id, provider_id, scope, name, status, outbound_auth_method, auth_username, auth_secret_ciphertext, inbound_enabled, inbound_auth_method, inbound_username, inbound_secret_ciphertext, max_cps, max_concurrent_calls, max_daily_minutes, codecs, supports_video, supports_fax, created_at, updated_at
FROM carrier_connections
WHERE scope = 'platform'
  AND organization_id IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPlatformCarrierConnections(ctx context.Context) ([]CarrierConnection, error) {
	rows, err := q.db.Query(ctx, listPlatformCarrierConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CarrierConnection{}
	for rows.Next() {
		var i CarrierConnection
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProviderID,
			&i.Scope,
			&i.Name,
			&i.Status,
			&i.OutboundAuthMethod,
			&i.AuthUsername,
			&i.AuthSecretCiphertext,
			&i.InboundEnabled,
			&i.InboundAuthMethod,
			&i.InboundUsername,
			&i.InboundSecretCiphertext,
			&i.MaxCps,
			&i.MaxConcurrentCalls,
			&i.MaxDailyMinutes,
			&i.Codecs,
			&i.SupportsVideo,
			&i.SupportsFax,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderRoutingTargets = `-- name: ListProviderRoutingTargets :many
SELECT
    cc.id AS carrier_connection_id,
    resource.provider_resource_id
FROM carrier_connections AS cc
JOIN carrier_connection_provider_resources AS resource
  ON resource.carrier_connection_id = cc.id
 AND resource.provider_id = cc.provider_id
 AND resource.resource_type = 'voice_in_trunk'
WHERE cc.provider_id = $1
  AND cc.scope = 'platform'
  AND cc.organization_id IS NULL
  AND cc.status = 'active'
  AND cc.inbound_enabled = true
ORDER BY cc.created_at ASC
LIMIT 2
`

type ListProviderRoutingTargetsRow struct {
	CarrierConnectionID uuid.UUID `db:"carrier_connection_id" json:"carrier_connection_id"`
	ProviderResourceID  string    `db:"provider_resource_id" json:"provider_resource_id"`
}

func (q *Queries) ListProviderRoutingTargets(ctx context.Context, providerID uuid.UUID) ([]ListProviderRoutingTargetsRow, error) {
	rows, err := q.db.Query(ctx, listProviderRoutingTargets, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderRoutingTargetsRow{}
	for rows.Next() {
		var i ListProviderRoutingTargetsRow
		if err := rows.Scan(&i.CarrierConnectionID, &i.ProviderResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCarrierConnectionBySourceIP = `-- name: ResolveCarrierConnectionBySourceIP :one
SELECT cc.id, cc.organization_id, cc.provider_id, cc.scope, cc.name, cc.status, cc.outbound_auth_method, cc.auth_username, cc.auth_secret_ciphertext, cc.inbound_enabled, cc.inbound_auth_method, cc.inbound_username, cc.inbound_secret_ciphertext, cc.max_cps, cc.max_concurrent_calls, cc.max_daily_minutes, cc.codecs, cc.supports_video, cc.supports_fax, cc.created_at, cc.updated_at
FROM carrier_connection_source_ips AS src
JOIN carrier_connections AS cc
  ON cc.id = src.carrier_connection_id
 AND cc.organization_id = src.organization_id
WHERE $1::INET <<= src.cidr
  AND cc.scope = 'organization'
  AND cc.status = 'active'
  AND cc.inbound_enabled = true
  AND cc.inbound_auth_method = 'ip'
ORDER BY masklen(src.cidr) DESC
LIMIT 1
`

func (q *Queries) ResolveCarrierConnectionBySourceIP(ctx context.Context, sourceIp netip.Addr) (CarrierConnection, error) {
	row := q.db.QueryRow(ctx, resolveCarrierConnectionBySourceIP, sourceIp)
	var i CarrierConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.Scope,
		&i.Name,
		&i.Status,
		&i.OutboundAuthMethod,
		&i.AuthUsername,
		&i.AuthSecretCiphertext,
		&i.InboundEnabled,
		&i.InboundAuthMethod,
		&i.InboundUsername,
		&i.InboundSecretCiphertext,
		&i.MaxCps,
		&i.MaxConcurrentCalls,
		&i.MaxDailyMinutes,
		&i.Codecs,
		&i.SupportsVideo,
		&i.SupportsFax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCarrierConnectionInboundDigestAuth = `-- name: SetCarrierConnectionInboundDigestAuth :exec
UPDATE carrier_connections
SET
    inbound_auth_method = 'digest',
    inbound_username = $1,
    inbound_secret_ciphertext = $2,
    updated_at = NOW()
WHERE id = $3
  AND scope = 'organization'
  AND organization_id = $4
`

type SetCarrierConnectionInboundDigestAuthParams struct {
	InboundUsername         *string    `db:"inbound_username" json:"inbound_username"`
	InboundSecretCiphertext *string    `db:"inbound_secret_ciphertext" json:"inbound_secret_ciphertext"`
	ID                      uuid.UUID  `db:"id" json:"id"`
	OrganizationID          *uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) SetCarrierConnectionInboundDigestAuth(ctx context.Context, arg SetCarrierConnectionInboundDigestAuthParams) error {
	_, err := q.db.Exec(ctx, setCarrierConnectionInboundDigestAuth,
		arg.InboundUsername,
		arg.InboundSecretCiphertext,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}

const setCarrierConnectionInboundIPAuth = `-- name: SetCarrierConnectionInboundIPAuth :exec
UPDATE carrier_connections
SET
    inbound_auth_method = 'ip',
    inbound_username = NULL,
    inbound_secret_ciphertext = NULL,
    updated_at = NOW()
WHERE id = $1
  AND scope = 'organization'
  AND organization_id = $2
`

type SetCarrierConnectionInboundIPAuthParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	OrganizationID *uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) SetCarrierConnectionInboundIPAuth(ctx context.Context, arg SetCarrierConnectionInboundIPAuthParams) error {
	_, err := q.db.Exec(ctx, setCarrierConnectionInboundIPAuth, arg.ID, arg.OrganizationID)
	return err
}

const setCarrierConnectionInboundNoAuth = `-- name: SetCarrierConnectionInboundNoAuth :exec
UPDATE carrier_connections
SET
    inbound_auth_method = 'none',
    inbound_username = NULL,
    inbound_secret_ciphertext = NULL,
    updated_at = NOW()
WHERE id = $1
  AND scope = 'organization'
  AND organization_id = $2
`

type SetCarrierConnectionInboundNoAuthParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	OrganizationID *uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) SetCarrierConnectionInboundNoAuth(ctx context.Context, arg SetCarrierConnectionInboundNoAuthParams) error {
	_, err := q.db.Exec(ctx, setCarrierConnectionInboundNoAuth, arg.ID, arg.OrganizationID)
	return err
}

const setCarrierConnectionOutboundDigestAuth = `-- name: SetCarrierConnectionOutboundDigestAuth :exec
UPDATE carrier_connections
SET
    outbound_auth_method = 'digest',
    auth_username = $1,
    auth_secret_ciphertext = $2,
    updated_at = NOW()
WHERE id = $3
  AND scope = 'organization'
  AND organization_id = $4
`

type SetCarrierConnectionOutboundDigestAuthParams struct {
	AuthUsername         *string    `db:"auth_username" json:"auth_username"`
	AuthSecretCiphertext *string    `db:"auth_secret_ciphertext" json:"auth_secret_ciphertext"`
	ID                   uuid.UUID  `db:"id" json:"id"`
	OrganizationID       *uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) SetCarrierConnectionOutboundDigestAuth(ctx context.Context, arg SetCarrierConnectionOutboundDigestAuthParams) error {
	_, err := q.db.Exec(ctx, setCarrierConnectionOutboundDigestAuth,
		arg.AuthUsername,
		arg.AuthSecretCiphertext,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}

const updateCarrierConnection = `-- name: UpdateCarrierConnection :one
UPDATE carrier_connections
SET
    name = COALESCE($1, name),
    status = COALESCE($2, status),
    inbound_enabled = COALESCE($3, inbound_enabled),
    max_cps = COALESCE($4, max_cps),
    max_concurrent_calls = COALESCE($5, max_concurrent_calls),
    max_daily_minutes = COALESCE($6, max_daily_minutes),
    codecs = COALESCE($7, codecs),
    supports_video = COALESCE($8, supports_video),
    supports_fax = COALESCE($9, supports_fax),
    updated_at = NOW()
WHERE id = $10
  AND scope = 'organization'
  AND organization_id = $11
RETURNING id, organization_id, provider_id, scope, name, status, outbound_auth_method, auth_username, auth_secret_ciphertext, inbound_enabled, inbound_auth_method, inbound_username, inbound_secret_ciphertext, max_cps, max_concurrent_calls, max_daily_minutes, codecs, supports_video, supports_fax, created_at, updated_at
`

type UpdateCarrierConnectionParams struct {
	Name               *string    `db:"name" json:"name"`
	Status             *string    `db:"status" json:"status"`
	InboundEnabled     *bool      `db:"inbound_enabled" json:"inbound_enabled"`
	MaxCps             *int32     `db:"max_cps" json:"max_cps"`
	MaxConcurrentCalls *int32     `db:"max_concurrent_calls" json:"max_concurrent_calls"`
	MaxDailyMinutes    *int64     `db:"max_daily_minutes" json:"max_daily_minutes"`
	Codecs             []string   `db:"codecs" json:"codecs"`
	SupportsVideo      *bool      `db:"supports_video" json:"supports_video"`
	SupportsFax        *bool      `db:"supports_fax" json:"supports_fax"`
	ID                 uuid.UUID  `db:"id" json:"id"`
	OrganizationID     *uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdateCarrierConnection(ctx context.Context, arg UpdateCarrierConnectionParams) (CarrierConnection, error) {
	row := q.db.QueryRow(ctx, updateCarrierConnection,
		arg.Name,
		arg.Status,
		arg.InboundEnabled,
		arg.MaxCps,
		arg.MaxConcurrentCalls,
		arg.MaxDailyMinutes,
		arg.Codecs,
		arg.SupportsVideo,
		arg.SupportsFax,
		arg.ID,
		arg.OrganizationID,
	)
	var i CarrierConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.Scope,
		&i.Name,
		&i.Status,
		&i.OutboundAuthMethod,
		&i.AuthUsername,
		&i.AuthSecretCiphertext,
		&i.InboundEnabled,
		&i.InboundAuthMethod,
		&i.InboundUsername,
		&i.InboundSecretCiphertext,
		&i.MaxCps,
		&i.MaxConcurrentCalls,
		&i.MaxDailyMinutes,
		&i.Codecs,
		&i.SupportsVideo,
		&i.SupportsFax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlatformCarrierConnection = `-- name: UpdatePlatformCarrierConnection :one
UPDATE carrier_connections
SET
    name = COALESCE($1, name),
    status = COALESCE($2, status),
    inbound_enabled = COALESCE($3, inbound_enabled),
    max_cps = COALESCE($4, max_cps),
    max_concurrent_calls = COALESCE($5, max_concurrent_calls),
    max_daily_minutes = COALESCE($6, max_daily_minutes),
    codecs = COALESCE($7, codecs),
    supports_video = COALESCE($8, supports_video),
    supports_fax = COALESCE($9, supports_fax),
    updated_at = NOW()
WHERE id = $10
  AND scope = 'platform'
  AND organization_id IS NULL
RETURNING id, organization_id, provider_id, scope, name, status, outbound_auth_method, auth_username, auth_secret_ciphertext, inbound_enabled, inbound_auth_method, inbound_username, inbound_secret_ciphertext, max_cps, max_concurrent_calls, max_daily_minutes, codecs, supports_video, supports_fax, created_at, updated_at
`

type UpdatePlatformCarrierConnectionParams struct {
	Name               *string   `db:"name" json:"name"`
	Status             *string   `db:"status" json:"status"`
	InboundEnabled     *bool     `db:"inbound_enabled" json:"inbound_enabled"`
	MaxCps             *int32    `db:"max_cps" json:"max_cps"`
	MaxConcurrentCalls *int32    `db:"max_concurrent_calls" json:"max_concurrent_calls"`
	MaxDailyMinutes    *int64    `db:"max_daily_minutes" json:"max_daily_minutes"`
	Codecs             []string  `db:"codecs" json:"codecs"`
	SupportsVideo      *bool     `db:"supports_video" json:"supports_video"`
	SupportsFax        *bool     `db:"supports_fax" json:"supports_fax"`
	ID                 uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdatePlatformCarrierConnection(ctx context.Context, arg UpdatePlatformCarrierConnectionParams) (CarrierConnection, error) {
	row := q.db.QueryRow(ctx, updatePlatformCarrierConnection,
		arg.Name,
		arg.Status,
		arg.InboundEnabled,
		arg.MaxCps,
		arg.MaxConcurrentCalls,
		arg.MaxDailyMinutes,
		arg.Codecs,
		arg.SupportsVideo,
		arg.SupportsFax,
		arg.ID,
	)
	var i CarrierConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.Scope,
		&i.Name,
		&i.Status,
		&i.OutboundAuthMethod,
		&i.AuthUsername,
		&i.AuthSecretCiphertext,
		&i.InboundEnabled,
		&i.InboundAuthMethod,
		&i.InboundUsername,
		&i.InboundSecretCiphertext,
		&i.MaxCps,
		&i.MaxConcurrentCalls,
		&i.MaxDailyMinutes,
		&i.Codecs,
		&i.SupportsVideo,
		&i.SupportsFax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
