// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkout_orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimCheckoutOrderRefresh = `-- name: ClaimCheckoutOrderRefresh :one
UPDATE checkout_orders
SET updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
  AND provider = 'paystack'
  AND status = 'processing'
  AND updated_at <= $3
RETURNING id, organization_id, wallet_id, price_id, order_type, provider, payment_method, reference, amount_minor, currency, status, next_action, provider_message, expires_at, completed_at, metadata, created_at, updated_at
`

type ClaimCheckoutOrderRefreshParams struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID          `db:"id" json:"id"`
	RefreshBefore  pgtype.Timestamptz `db:"refresh_before" json:"refresh_before"`
}

func (q *Queries) ClaimCheckoutOrderRefresh(ctx context.Context, arg ClaimCheckoutOrderRefreshParams) (CheckoutOrder, error) {
	row := q.db.QueryRow(ctx, claimCheckoutOrderRefresh, arg.OrganizationID, arg.ID, arg.RefreshBefore)
	var i CheckoutOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WalletID,
		&i.PriceID,
		&i.OrderType,
		&i.Provider,
		&i.PaymentMethod,
		&i.Reference,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const compareAndSetCheckoutOrderState = `-- name: CompareAndSetCheckoutOrderState :one
UPDATE checkout_orders
SET status = $1,
    next_action = $2,
    provider_message = $3,
    completed_at = $4,
    updated_at = NOW()
WHERE organization_id = $5
  AND id = $6
  AND status = $7
RETURNING id, organization_id, wallet_id, price_id, order_type, provider, payment_method, reference, amount_minor, currency, status, next_action, provider_message, expires_at, completed_at, metadata, created_at, updated_at
`

type CompareAndSetCheckoutOrderStateParams struct {
	Status          string             `db:"status" json:"status"`
	NextAction      string             `db:"next_action" json:"next_action"`
	ProviderMessage *string            `db:"provider_message" json:"provider_message"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	ID              uuid.UUID          `db:"id" json:"id"`
	ExpectedStatus  string             `db:"expected_status" json:"expected_status"`
}

func (q *Queries) CompareAndSetCheckoutOrderState(ctx context.Context, arg CompareAndSetCheckoutOrderStateParams) (CheckoutOrder, error) {
	row := q.db.QueryRow(ctx, compareAndSetCheckoutOrderState,
		arg.Status,
		arg.NextAction,
		arg.ProviderMessage,
		arg.CompletedAt,
		arg.OrganizationID,
		arg.ID,
		arg.ExpectedStatus,
	)
	var i CheckoutOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WalletID,
		&i.PriceID,
		&i.OrderType,
		&i.Provider,
		&i.PaymentMethod,
		&i.Reference,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCheckoutOrder = `-- name: CreateCheckoutOrder :one
INSERT INTO checkout_orders (
    organization_id, wallet_id, price_id, order_type,
    provider, payment_method, reference, amount_minor, currency, expires_at, metadata
)
SELECT
    $1 AS organization_id,
    $2::UUID AS wallet_id,
    $3::UUID AS price_id,
    $4 AS order_type,
    $5 AS provider,
    $6 AS payment_method,
    $7 AS reference,
    $8 AS amount_minor,
    $9 AS currency,
    $10 AS expires_at,
    COALESCE($11, '{}'::jsonb) AS metadata
FROM organizations AS o
WHERE o.id = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
RETURNING id, organization_id, wallet_id, price_id, order_type, provider, payment_method, reference, amount_minor, currency, status, next_action, provider_message, expires_at, completed_at, metadata, created_at, updated_at
`

type CreateCheckoutOrderParams struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	WalletID       *uuid.UUID         `db:"wallet_id" json:"wallet_id"`
	PriceID        *uuid.UUID         `db:"price_id" json:"price_id"`
	OrderType      string             `db:"order_type" json:"order_type"`
	Provider       string             `db:"provider" json:"provider"`
	PaymentMethod  string             `db:"payment_method" json:"payment_method"`
	Reference      string             `db:"reference" json:"reference"`
	AmountMinor    int64              `db:"amount_minor" json:"amount_minor"`
	Currency       string             `db:"currency" json:"currency"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateCheckoutOrder(ctx context.Context, arg CreateCheckoutOrderParams) (CheckoutOrder, error) {
	row := q.db.QueryRow(ctx, createCheckoutOrder,
		arg.OrganizationID,
		arg.WalletID,
		arg.PriceID,
		arg.OrderType,
		arg.Provider,
		arg.PaymentMethod,
		arg.Reference,
		arg.AmountMinor,
		arg.Currency,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i CheckoutOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WalletID,
		&i.PriceID,
		&i.OrderType,
		&i.Provider,
		&i.PaymentMethod,
		&i.Reference,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireCheckoutOrders = `-- name: ExpireCheckoutOrders :many
UPDATE checkout_orders
SET status = 'expired', next_action = 'none', completed_at = NOW(), updated_at = NOW()
WHERE status IN ('pending', 'processing')
  AND expires_at <= NOW()
RETURNING id, organization_id, wallet_id, price_id, order_type, provider, payment_method, reference, amount_minor, currency, status, next_action, provider_message, expires_at, completed_at, metadata, created_at, updated_at
`

func (q *Queries) ExpireCheckoutOrders(ctx context.Context) ([]CheckoutOrder, error) {
	rows, err := q.db.Query(ctx, expireCheckoutOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckoutOrder{}
	for rows.Next() {
		var i CheckoutOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WalletID,
			&i.PriceID,
			&i.OrderType,
			&i.Provider,
			&i.PaymentMethod,
			&i.Reference,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.NextAction,
			&i.ProviderMessage,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckoutOrder = `-- name: GetCheckoutOrder :one
SELECT co.id, co.organization_id, co.wallet_id, co.price_id, co.order_type, co.provider, co.payment_method, co.reference, co.amount_minor, co.currency, co.status, co.next_action, co.provider_message, co.expires_at, co.completed_at, co.metadata, co.created_at, co.updated_at
FROM checkout_orders AS co
JOIN organizations AS o ON o.id = co.organization_id
WHERE co.organization_id = $1
  AND co.id = $2
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetCheckoutOrderParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetCheckoutOrder(ctx context.Context, arg GetCheckoutOrderParams) (CheckoutOrder, error) {
	row := q.db.QueryRow(ctx, getCheckoutOrder, arg.OrganizationID, arg.ID)
	var i CheckoutOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WalletID,
		&i.PriceID,
		&i.OrderType,
		&i.Provider,
		&i.PaymentMethod,
		&i.Reference,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckoutOrderByReference = `-- name: GetCheckoutOrderByReference :one
SELECT co.id, co.organization_id, co.wallet_id, co.price_id, co.order_type, co.provider, co.payment_method, co.reference, co.amount_minor, co.currency, co.status, co.next_action, co.provider_message, co.expires_at, co.completed_at, co.metadata, co.created_at, co.updated_at
FROM checkout_orders AS co
JOIN organizations AS o ON o.id = co.organization_id
WHERE co.reference = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetCheckoutOrderByReference(ctx context.Context, reference string) (CheckoutOrder, error) {
	row := q.db.QueryRow(ctx, getCheckoutOrderByReference, reference)
	var i CheckoutOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WalletID,
		&i.PriceID,
		&i.OrderType,
		&i.Provider,
		&i.PaymentMethod,
		&i.Reference,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
