// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conferences.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConference = `-- name: CreateConference :one
INSERT INTO conferences (
    tenant_id,
    application_id,
    name,
    state,
    started_at
) VALUES (
    $1,
    $2,
    $3,
    COALESCE($4, 'active'),
    $5
)
RETURNING id, tenant_id, application_id, name, state, started_at, ended_at, created_at, updated_at
`

type CreateConferenceParams struct {
	TenantID      uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	ApplicationID *uuid.UUID         `db:"application_id" json:"application_id"`
	Name          string             `db:"name" json:"name"`
	State         interface{}        `db:"state" json:"state"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
}

func (q *Queries) CreateConference(ctx context.Context, arg CreateConferenceParams) (Conference, error) {
	row := q.db.QueryRow(ctx, createConference,
		arg.TenantID,
		arg.ApplicationID,
		arg.Name,
		arg.State,
		arg.StartedAt,
	)
	var i Conference
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationID,
		&i.Name,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConference = `-- name: GetConference :one
SELECT id, tenant_id, application_id, name, state, started_at, ended_at, created_at, updated_at
FROM conferences
WHERE tenant_id = $1
  AND id = $2
LIMIT 1
`

type GetConferenceParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetConference(ctx context.Context, arg GetConferenceParams) (Conference, error) {
	row := q.db.QueryRow(ctx, getConference, arg.TenantID, arg.ID)
	var i Conference
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationID,
		&i.Name,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConferenceByName = `-- name: GetConferenceByName :one
SELECT id, tenant_id, application_id, name, state, started_at, ended_at, created_at, updated_at
FROM conferences
WHERE tenant_id = $1
  AND name = $2
LIMIT 1
`

type GetConferenceByNameParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name     string    `db:"name" json:"name"`
}

func (q *Queries) GetConferenceByName(ctx context.Context, arg GetConferenceByNameParams) (Conference, error) {
	row := q.db.QueryRow(ctx, getConferenceByName, arg.TenantID, arg.Name)
	var i Conference
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationID,
		&i.Name,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConferences = `-- name: ListConferences :many
SELECT id, tenant_id, application_id, name, state, started_at, ended_at, created_at, updated_at
FROM conferences
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListConferencesParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListConferences(ctx context.Context, arg ListConferencesParams) ([]Conference, error) {
	rows, err := q.db.Query(ctx, listConferences, arg.TenantID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conference{}
	for rows.Next() {
		var i Conference
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ApplicationID,
			&i.Name,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConferenceState = `-- name: UpdateConferenceState :one
UPDATE conferences
SET
    state = $1,
    ended_at = CASE
        WHEN $1::text = 'ended' THEN COALESCE(ended_at, NOW())
        ELSE ended_at
    END,
    updated_at = NOW()
WHERE tenant_id = $2
  AND id = $3
RETURNING id, tenant_id, application_id, name, state, started_at, ended_at, created_at, updated_at
`

type UpdateConferenceStateParams struct {
	State    string    `db:"state" json:"state"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateConferenceState(ctx context.Context, arg UpdateConferenceStateParams) (Conference, error) {
	row := q.db.QueryRow(ctx, updateConferenceState, arg.State, arg.TenantID, arg.ID)
	var i Conference
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApplicationID,
		&i.Name,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
