// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_credentials.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeploymentCredential = `-- name: CreateDeploymentCredential :one
INSERT INTO deployment_credentials (
    deployment_id,
    purpose,
    token_hash,
    token_prefix,
    scopes,
    expires_at
)
SELECT
    d.id,
    $1,
    $2,
    $3,
    $4::jsonb,
    $5
FROM deployments AS d
JOIN licenses AS l ON l.id = d.license_id
JOIN organizations AS o ON o.id = l.organization_id
WHERE d.id = $6
  AND d.status = 'active'
  AND l.status = 'active'
  AND (l.expires_at IS NULL OR l.expires_at > now())
  AND o.status = 'active'
  AND o.deleted_at IS NULL
RETURNING deployment_credentials.id, deployment_credentials.deployment_id, deployment_credentials.purpose, deployment_credentials.token_hash, deployment_credentials.token_prefix, deployment_credentials.scopes, deployment_credentials.expires_at, deployment_credentials.last_used_at, deployment_credentials.disabled_at, deployment_credentials.created_at, deployment_credentials.updated_at
`

type CreateDeploymentCredentialParams struct {
	Purpose      string             `db:"purpose" json:"purpose"`
	TokenHash    string             `db:"token_hash" json:"token_hash"`
	TokenPrefix  string             `db:"token_prefix" json:"token_prefix"`
	Scopes       []byte             `db:"scopes" json:"scopes"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	DeploymentID uuid.UUID          `db:"deployment_id" json:"deployment_id"`
}

func (q *Queries) CreateDeploymentCredential(ctx context.Context, arg CreateDeploymentCredentialParams) (DeploymentCredential, error) {
	row := q.db.QueryRow(ctx, createDeploymentCredential,
		arg.Purpose,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scopes,
		arg.ExpiresAt,
		arg.DeploymentID,
	)
	var i DeploymentCredential
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Purpose,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableActiveDeploymentCredentials = `-- name: DisableActiveDeploymentCredentials :exec
UPDATE deployment_credentials
SET disabled_at = COALESCE(disabled_at, now())
WHERE deployment_id = $1
  AND purpose = $2
  AND disabled_at IS NULL
`

type DisableActiveDeploymentCredentialsParams struct {
	DeploymentID uuid.UUID `db:"deployment_id" json:"deployment_id"`
	Purpose      string    `db:"purpose" json:"purpose"`
}

func (q *Queries) DisableActiveDeploymentCredentials(ctx context.Context, arg DisableActiveDeploymentCredentialsParams) error {
	_, err := q.db.Exec(ctx, disableActiveDeploymentCredentials, arg.DeploymentID, arg.Purpose)
	return err
}

const getDeploymentCredentialByTokenHash = `-- name: GetDeploymentCredentialByTokenHash :one
SELECT
    dc.id AS credential_id,
    dc.deployment_id AS deployment_row_id,
    dc.purpose,
    dc.token_hash,
    dc.token_prefix,
    dc.scopes,
    dc.expires_at AS credential_expires_at,
    dc.last_used_at,
    dc.disabled_at,
    dc.created_at,
    dc.updated_at,
    d.deployment_id,
    d.status AS deployment_status,
    d.license_id,
    l.organization_id,
    l.status AS license_status,
    l.expires_at AS license_expires_at
FROM deployment_credentials AS dc
JOIN deployments AS d ON d.id = dc.deployment_id
JOIN licenses AS l ON l.id = d.license_id
JOIN organizations AS o ON o.id = l.organization_id
WHERE dc.token_hash = $1
  AND dc.disabled_at IS NULL
  AND (dc.expires_at IS NULL OR dc.expires_at > now())
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetDeploymentCredentialByTokenHashRow struct {
	CredentialID        uuid.UUID          `db:"credential_id" json:"credential_id"`
	DeploymentRowID     uuid.UUID          `db:"deployment_row_id" json:"deployment_row_id"`
	Purpose             string             `db:"purpose" json:"purpose"`
	TokenHash           string             `db:"token_hash" json:"token_hash"`
	TokenPrefix         string             `db:"token_prefix" json:"token_prefix"`
	Scopes              []byte             `db:"scopes" json:"scopes"`
	CredentialExpiresAt pgtype.Timestamptz `db:"credential_expires_at" json:"credential_expires_at"`
	LastUsedAt          pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	DisabledAt          pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeploymentID        string             `db:"deployment_id" json:"deployment_id"`
	DeploymentStatus    string             `db:"deployment_status" json:"deployment_status"`
	LicenseID           uuid.UUID          `db:"license_id" json:"license_id"`
	OrganizationID      uuid.UUID          `db:"organization_id" json:"organization_id"`
	LicenseStatus       string             `db:"license_status" json:"license_status"`
	LicenseExpiresAt    pgtype.Timestamptz `db:"license_expires_at" json:"license_expires_at"`
}

func (q *Queries) GetDeploymentCredentialByTokenHash(ctx context.Context, tokenHash string) (GetDeploymentCredentialByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getDeploymentCredentialByTokenHash, tokenHash)
	var i GetDeploymentCredentialByTokenHashRow
	err := row.Scan(
		&i.CredentialID,
		&i.DeploymentRowID,
		&i.Purpose,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.CredentialExpiresAt,
		&i.LastUsedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeploymentID,
		&i.DeploymentStatus,
		&i.LicenseID,
		&i.OrganizationID,
		&i.LicenseStatus,
		&i.LicenseExpiresAt,
	)
	return i, err
}

const touchDeploymentCredential = `-- name: TouchDeploymentCredential :one
UPDATE deployment_credentials
SET last_used_at = now()
WHERE id = $1
  AND disabled_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
RETURNING id
`

func (q *Queries) TouchDeploymentCredential(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, touchDeploymentCredential, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}
