// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entitlements.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEntitlement = `-- name: CreateEntitlement :one
INSERT INTO entitlements (
    plan_id,
    organization_id,
    license_id,
    entitlement_key,
    kind,
    enabled,
    limit_value,
    starts_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, plan_id, organization_id, license_id, entitlement_key, kind, enabled, limit_value, starts_at, expires_at, created_at, updated_at
`

type CreateEntitlementParams struct {
	PlanID         *uuid.UUID         `db:"plan_id" json:"plan_id"`
	OrganizationID *uuid.UUID         `db:"organization_id" json:"organization_id"`
	LicenseID      *uuid.UUID         `db:"license_id" json:"license_id"`
	EntitlementKey string             `db:"entitlement_key" json:"entitlement_key"`
	Kind           string             `db:"kind" json:"kind"`
	Enabled        *bool              `db:"enabled" json:"enabled"`
	LimitValue     *int64             `db:"limit_value" json:"limit_value"`
	StartsAt       pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateEntitlement(ctx context.Context, arg CreateEntitlementParams) (Entitlement, error) {
	row := q.db.QueryRow(ctx, createEntitlement,
		arg.PlanID,
		arg.OrganizationID,
		arg.LicenseID,
		arg.EntitlementKey,
		arg.Kind,
		arg.Enabled,
		arg.LimitValue,
		arg.StartsAt,
		arg.ExpiresAt,
	)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.OrganizationID,
		&i.LicenseID,
		&i.EntitlementKey,
		&i.Kind,
		&i.Enabled,
		&i.LimitValue,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEntitlement = `-- name: DeleteEntitlement :exec
DELETE FROM entitlements
WHERE id = $1
`

func (q *Queries) DeleteEntitlement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntitlement, id)
	return err
}

const getEntitlement = `-- name: GetEntitlement :one
SELECT id, plan_id, organization_id, license_id, entitlement_key, kind, enabled, limit_value, starts_at, expires_at, created_at, updated_at
FROM entitlements
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEntitlement(ctx context.Context, id uuid.UUID) (Entitlement, error) {
	row := q.db.QueryRow(ctx, getEntitlement, id)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.OrganizationID,
		&i.LicenseID,
		&i.EntitlementKey,
		&i.Kind,
		&i.Enabled,
		&i.LimitValue,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLicenseEntitlements = `-- name: ListLicenseEntitlements :many
SELECT id, plan_id, organization_id, license_id, entitlement_key, kind, enabled, limit_value, starts_at, expires_at, created_at, updated_at
FROM entitlements
WHERE license_id = $1
ORDER BY entitlement_key
`

func (q *Queries) ListLicenseEntitlements(ctx context.Context, licenseID *uuid.UUID) ([]Entitlement, error) {
	rows, err := q.db.Query(ctx, listLicenseEntitlements, licenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entitlement{}
	for rows.Next() {
		var i Entitlement
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.OrganizationID,
			&i.LicenseID,
			&i.EntitlementKey,
			&i.Kind,
			&i.Enabled,
			&i.LimitValue,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationEntitlements = `-- name: ListOrganizationEntitlements :many
SELECT id, plan_id, organization_id, license_id, entitlement_key, kind, enabled, limit_value, starts_at, expires_at, created_at, updated_at
FROM entitlements
WHERE organization_id = $1
ORDER BY entitlement_key
`

func (q *Queries) ListOrganizationEntitlements(ctx context.Context, organizationID *uuid.UUID) ([]Entitlement, error) {
	rows, err := q.db.Query(ctx, listOrganizationEntitlements, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entitlement{}
	for rows.Next() {
		var i Entitlement
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.OrganizationID,
			&i.LicenseID,
			&i.EntitlementKey,
			&i.Kind,
			&i.Enabled,
			&i.LimitValue,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanEntitlements = `-- name: ListPlanEntitlements :many
SELECT id, plan_id, organization_id, license_id, entitlement_key, kind, enabled, limit_value, starts_at, expires_at, created_at, updated_at
FROM entitlements
WHERE plan_id = $1
ORDER BY entitlement_key
`

func (q *Queries) ListPlanEntitlements(ctx context.Context, planID *uuid.UUID) ([]Entitlement, error) {
	rows, err := q.db.Query(ctx, listPlanEntitlements, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entitlement{}
	for rows.Next() {
		var i Entitlement
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.OrganizationID,
			&i.LicenseID,
			&i.EntitlementKey,
			&i.Kind,
			&i.Enabled,
			&i.LimitValue,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
