// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO idempotency (
    scope, idempotency_key, method, path, request_hash,
    locked_until, expires_at
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7
)
ON CONFLICT (scope, idempotency_key) DO UPDATE
SET
    method = EXCLUDED.method,
    path = EXCLUDED.path,
    request_hash = EXCLUDED.request_hash,
    status = 'processing',
    response_status = NULL,
    response_body = NULL,
    response_content_type = NULL,
    response_headers = '{}'::JSONB,
    locked_until = EXCLUDED.locked_until,
    completed_at = NULL,
    expires_at = EXCLUDED.expires_at,
    updated_at = NOW()
WHERE idempotency.expires_at <= NOW()
   OR (
       idempotency.status = 'processing'
       AND idempotency.locked_until <= NOW()
       AND idempotency.method = EXCLUDED.method
       AND idempotency.path = EXCLUDED.path
       AND idempotency.request_hash = EXCLUDED.request_hash
   )
RETURNING scope, idempotency_key, method, path, request_hash, status, response_status, response_body, response_content_type, response_headers, locked_until, completed_at, expires_at, created_at, updated_at
`

type ClaimIdempotencyKeyParams struct {
	Scope          string             `db:"scope" json:"scope"`
	IdempotencyKey string             `db:"idempotency_key" json:"idempotency_key"`
	Method         string             `db:"method" json:"method"`
	Path           string             `db:"path" json:"path"`
	RequestHash    string             `db:"request_hash" json:"request_hash"`
	LockedUntil    pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (Idempotency, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.Scope,
		arg.IdempotencyKey,
		arg.Method,
		arg.Path,
		arg.RequestHash,
		arg.LockedUntil,
		arg.ExpiresAt,
	)
	var i Idempotency
	err := row.Scan(
		&i.Scope,
		&i.IdempotencyKey,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResponseContentType,
		&i.ResponseHeaders,
		&i.LockedUntil,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :one
UPDATE idempotency
SET
    status = 'completed',
    response_status = $1,
    response_body = $2,
    response_content_type = $3,
    response_headers = $4,
    completed_at = NOW(),
    locked_until = NOW(),
    updated_at = NOW()
WHERE scope = $5
  AND idempotency_key = $6
  AND method = $7
  AND path = $8
  AND request_hash = $9
  AND status = 'processing'
  AND locked_until = $10
RETURNING scope, idempotency_key, method, path, request_hash, status, response_status, response_body, response_content_type, response_headers, locked_until, completed_at, expires_at, created_at, updated_at
`

type CompleteIdempotencyKeyParams struct {
	ResponseStatus      *int32             `db:"response_status" json:"response_status"`
	ResponseBody        []byte             `db:"response_body" json:"response_body"`
	ResponseContentType *string            `db:"response_content_type" json:"response_content_type"`
	ResponseHeaders     []byte             `db:"response_headers" json:"response_headers"`
	Scope               string             `db:"scope" json:"scope"`
	IdempotencyKey      string             `db:"idempotency_key" json:"idempotency_key"`
	Method              string             `db:"method" json:"method"`
	Path                string             `db:"path" json:"path"`
	RequestHash         string             `db:"request_hash" json:"request_hash"`
	LockedUntil         pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (Idempotency, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ResponseContentType,
		arg.ResponseHeaders,
		arg.Scope,
		arg.IdempotencyKey,
		arg.Method,
		arg.Path,
		arg.RequestHash,
		arg.LockedUntil,
	)
	var i Idempotency
	err := row.Scan(
		&i.Scope,
		&i.IdempotencyKey,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResponseContentType,
		&i.ResponseHeaders,
		&i.LockedUntil,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT scope, idempotency_key, method, path, request_hash, status, response_status, response_body, response_content_type, response_headers, locked_until, completed_at, expires_at, created_at, updated_at
FROM idempotency
WHERE scope = $1
  AND idempotency_key = $2
LIMIT 1
`

type GetIdempotencyKeyParams struct {
	Scope          string `db:"scope" json:"scope"`
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (Idempotency, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Scope, arg.IdempotencyKey)
	var i Idempotency
	err := row.Scan(
		&i.Scope,
		&i.IdempotencyKey,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResponseContentType,
		&i.ResponseHeaders,
		&i.LockedUntil,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
