// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_items.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoiceItem = `-- name: CreateInvoiceItem :one
INSERT INTO invoice_items (
    invoice_id,
    meter_id,
    carrier_rate_id,
    type,
    description,
    quantity,
    unit_amount_micros,
    amount,
    period_start,
    period_end,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE($6, 1),
    $7,
    $8,
    $9,
    $10,
    COALESCE($11, '{}'::jsonb)
)
RETURNING id, invoice_id, meter_id, carrier_rate_id, type, description, quantity, unit_amount_micros, amount, period_start, period_end, metadata, created_at
`

type CreateInvoiceItemParams struct {
	InvoiceID        uuid.UUID          `db:"invoice_id" json:"invoice_id"`
	MeterID          *uuid.UUID         `db:"meter_id" json:"meter_id"`
	CarrierRateID    *uuid.UUID         `db:"carrier_rate_id" json:"carrier_rate_id"`
	Type             string             `db:"type" json:"type"`
	Description      string             `db:"description" json:"description"`
	Quantity         interface{}        `db:"quantity" json:"quantity"`
	UnitAmountMicros *int64             `db:"unit_amount_micros" json:"unit_amount_micros"`
	Amount           int64              `db:"amount" json:"amount"`
	PeriodStart      pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd        pgtype.Timestamptz `db:"period_end" json:"period_end"`
	Metadata         interface{}        `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceItem,
		arg.InvoiceID,
		arg.MeterID,
		arg.CarrierRateID,
		arg.Type,
		arg.Description,
		arg.Quantity,
		arg.UnitAmountMicros,
		arg.Amount,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Metadata,
	)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.MeterID,
		&i.CarrierRateID,
		&i.Type,
		&i.Description,
		&i.Quantity,
		&i.UnitAmountMicros,
		&i.Amount,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvoiceItems = `-- name: DeleteInvoiceItems :exec
DELETE FROM invoice_items
WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoiceItems(ctx context.Context, invoiceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoiceItems, invoiceID)
	return err
}

const listInvoiceItems = `-- name: ListInvoiceItems :many
SELECT id, invoice_id, meter_id, carrier_rate_id, type, description, quantity, unit_amount_micros, amount, period_start, period_end, metadata, created_at
FROM invoice_items
WHERE invoice_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListInvoiceItems(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceItem{}
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.MeterID,
			&i.CarrierRateID,
			&i.Type,
			&i.Description,
			&i.Quantity,
			&i.UnitAmountMicros,
			&i.Amount,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
