// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	TenantID    uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CreatedBy   uuid.UUID          `db:"created_by" json:"created_by"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	TokenHash   string             `db:"token_hash" json:"token_hash"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	Scopes      []byte             `db:"scopes" json:"scopes"`
	LastUsedAt  pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	LastUsedIp  *netip.Addr        `db:"last_used_ip" json:"last_used_ip"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AuthChallenge struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	AuthTransactionID *uuid.UUID         `db:"auth_transaction_id" json:"auth_transaction_id"`
	Identifier        string             `db:"identifier" json:"identifier"`
	SecretHash        string             `db:"secret_hash" json:"secret_hash"`
	Purpose           string             `db:"purpose" json:"purpose"`
	State             []byte             `db:"state" json:"state"`
	Attempts          int32              `db:"attempts" json:"attempts"`
	MaxAttempts       int32              `db:"max_attempts" json:"max_attempts"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuthTransaction struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	Identifier     string             `db:"identifier" json:"identifier"`
	UserID         *uuid.UUID         `db:"user_id" json:"user_id"`
	State          string             `db:"state" json:"state"`
	SelectedMethod *string            `db:"selected_method" json:"selected_method"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Call struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	TenantID      uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	ApplicationID *uuid.UUID         `db:"application_id" json:"application_id"`
	Direction     string             `db:"direction" json:"direction"`
	State         string             `db:"state" json:"state"`
	FromUri       string             `db:"from_uri" json:"from_uri"`
	ToUri         string             `db:"to_uri" json:"to_uri"`
	SipCallID     *string            `db:"sip_call_id" json:"sip_call_id"`
	ProviderID    *uuid.UUID         `db:"provider_id" json:"provider_id"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	AnsweredAt    pgtype.Timestamptz `db:"answered_at" json:"answered_at"`
	EndedAt       pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	HangupReason  *string            `db:"hangup_reason" json:"hangup_reason"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CallParticipant struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	TenantID     uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CallID       uuid.UUID          `db:"call_id" json:"call_id"`
	SubscriberID *uuid.UUID         `db:"subscriber_id" json:"subscriber_id"`
	Role         string             `db:"role" json:"role"`
	Address      *string            `db:"address" json:"address"`
	Direction    *string            `db:"direction" json:"direction"`
	State        string             `db:"state" json:"state"`
	JoinedAt     pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	LeftAt       pgtype.Timestamptz `db:"left_at" json:"left_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Conference struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	TenantID      uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	ApplicationID *uuid.UUID         `db:"application_id" json:"application_id"`
	Name          string             `db:"name" json:"name"`
	State         string             `db:"state" json:"state"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt       pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ConferenceParticipant struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	TenantID          uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	ConferenceID      uuid.UUID          `db:"conference_id" json:"conference_id"`
	CallParticipantID *uuid.UUID         `db:"call_participant_id" json:"call_participant_id"`
	State             string             `db:"state" json:"state"`
	Muted             bool               `db:"muted" json:"muted"`
	JoinedAt          pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	LeftAt            pgtype.Timestamptz `db:"left_at" json:"left_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Subject       string             `db:"subject" json:"subject"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	Payload       []byte             `db:"payload" json:"payload"`
	Headers       []byte             `db:"headers" json:"headers"`
	AvailableAt   pgtype.Timestamptz `db:"available_at" json:"available_at"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Attempts      int32              `db:"attempts" json:"attempts"`
	LastError     *string            `db:"last_error" json:"last_error"`
	LockedAt      pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy      *string            `db:"locked_by" json:"locked_by"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProcessedEvent struct {
	ConsumerName string             `db:"consumer_name" json:"consumer_name"`
	EventID      uuid.UUID          `db:"event_id" json:"event_id"`
	ProcessedAt  pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	Metadata     []byte             `db:"metadata" json:"metadata"`
}

type Recording struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	TenantID        uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CallID          uuid.UUID          `db:"call_id" json:"call_id"`
	Status          string             `db:"status" json:"status"`
	StorageKey      *string            `db:"storage_key" json:"storage_key"`
	Format          *string            `db:"format" json:"format"`
	DurationSeconds *int32             `db:"duration_seconds" json:"duration_seconds"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	IpAddress  *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent  *string            `db:"user_agent" json:"user_agent"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SipDomain struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	TenantID  uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	Domain    string             `db:"domain" json:"domain"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Subscriber struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	TenantID     uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	SipDomainID  uuid.UUID          `db:"sip_domain_id" json:"sip_domain_id"`
	Username     string             `db:"username" json:"username"`
	Domain       string             `db:"domain" json:"domain"`
	Ha1Md5       *string            `db:"ha1_md5" json:"ha1_md5"`
	Ha1Sha256    *string            `db:"ha1_sha256" json:"ha1_sha256"`
	Ha1Sha512256 *string            `db:"ha1_sha512_256" json:"ha1_sha512_256"`
	DisplayName  *string            `db:"display_name" json:"display_name"`
	Status       string             `db:"status" json:"status"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Tenant struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Slug      string             `db:"slug" json:"slug"`
	Name      string             `db:"name" json:"name"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type TenantInvitation struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TenantID   uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	InvitedBy  uuid.UUID          `db:"invited_by" json:"invited_by"`
	Email      string             `db:"email" json:"email"`
	Role       string             `db:"role" json:"role"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	Status     string             `db:"status" json:"status"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	DeclinedAt pgtype.Timestamptz `db:"declined_at" json:"declined_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TenantMember struct {
	TenantID  uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Role      string             `db:"role" json:"role"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Email         string             `db:"email" json:"email"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	Name          *string            `db:"name" json:"name"`
	PasswordHash  *string            `db:"password_hash" json:"password_hash"`
	DisabledAt    pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type VoiceApplication struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	TenantID    uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	EndpointID     uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	Status         string             `db:"status" json:"status"`
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	ReplayCount    int32              `db:"replay_count" json:"replay_count"`
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastAttemptAt  pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	LastReplayedAt pgtype.Timestamptz `db:"last_replayed_at" json:"last_replayed_at"`
	ResponseStatus *int32             `db:"response_status" json:"response_status"`
	ResponseBody   *string            `db:"response_body" json:"response_body"`
	LastError      *string            `db:"last_error" json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	LockedAt       pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy       *string            `db:"locked_by" json:"locked_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WebhookEndpoint struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	TenantID            uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	Url                 string             `db:"url" json:"url"`
	SigningSecret       []byte             `db:"signing_secret" json:"signing_secret"`
	Enabled             bool               `db:"enabled" json:"enabled"`
	SubscribedEvents    []string           `db:"subscribed_events" json:"subscribed_events"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt          pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	ConsecutiveFailures int32              `db:"consecutive_failures" json:"consecutive_failures"`
	LastFailureAt       pgtype.Timestamptz `db:"last_failure_at" json:"last_failure_at"`
	DisabledReason      *string            `db:"disabled_reason" json:"disabled_reason"`
}

type WebhookEvent struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TenantID   uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	EventType  string             `db:"event_type" json:"event_type"`
	ObjectType string             `db:"object_type" json:"object_type"`
	ObjectID   *uuid.UUID         `db:"object_id" json:"object_id"`
	Payload    []byte             `db:"payload" json:"payload"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
