// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: networking.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const createNetworkPolicy = `-- name: CreateNetworkPolicy :one
INSERT INTO network_policies (
    id,
    organization_id,
    name,
    action,
    source_cidr
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, organization_id, name, action, source_cidr, status, created_at, updated_at
`

type CreateNetworkPolicyParams struct {
	ID             uuid.UUID    `db:"id" json:"id"`
	OrganizationID uuid.UUID    `db:"organization_id" json:"organization_id"`
	Name           string       `db:"name" json:"name"`
	Action         string       `db:"action" json:"action"`
	SourceCidr     netip.Prefix `db:"source_cidr" json:"source_cidr"`
}

func (q *Queries) CreateNetworkPolicy(ctx context.Context, arg CreateNetworkPolicyParams) (NetworkPolicy, error) {
	row := q.db.QueryRow(ctx, createNetworkPolicy,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Action,
		arg.SourceCidr,
	)
	var i NetworkPolicy
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Action,
		&i.SourceCidr,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNetworkPolicy = `-- name: DeleteNetworkPolicy :exec
DELETE FROM network_policies
WHERE id = $1
  AND organization_id = $2
`

type DeleteNetworkPolicyParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) DeleteNetworkPolicy(ctx context.Context, arg DeleteNetworkPolicyParams) error {
	_, err := q.db.Exec(ctx, deleteNetworkPolicy, arg.ID, arg.OrganizationID)
	return err
}

const getNetworkPolicy = `-- name: GetNetworkPolicy :one
SELECT id, organization_id, name, action, source_cidr, status, created_at, updated_at
FROM network_policies
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetNetworkPolicyParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetNetworkPolicy(ctx context.Context, arg GetNetworkPolicyParams) (NetworkPolicy, error) {
	row := q.db.QueryRow(ctx, getNetworkPolicy, arg.ID, arg.OrganizationID)
	var i NetworkPolicy
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Action,
		&i.SourceCidr,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNetworkPolicies = `-- name: ListNetworkPolicies :many
SELECT id, organization_id, name, action, source_cidr, status, created_at, updated_at
FROM network_policies
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListNetworkPolicies(ctx context.Context, organizationID uuid.UUID) ([]NetworkPolicy, error) {
	rows, err := q.db.Query(ctx, listNetworkPolicies, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetworkPolicy{}
	for rows.Next() {
		var i NetworkPolicy
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Action,
			&i.SourceCidr,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNetworkPolicy = `-- name: UpdateNetworkPolicy :one
UPDATE network_policies
SET name = COALESCE($1, name),
    action = COALESCE($2, action),
    source_cidr = COALESCE($3, source_cidr),
    status = COALESCE($4, status)
WHERE id = $5
  AND organization_id = $6
RETURNING id, organization_id, name, action, source_cidr, status, created_at, updated_at
`

type UpdateNetworkPolicyParams struct {
	Name           *string       `db:"name" json:"name"`
	Action         *string       `db:"action" json:"action"`
	SourceCidr     *netip.Prefix `db:"source_cidr" json:"source_cidr"`
	Status         *string       `db:"status" json:"status"`
	ID             uuid.UUID     `db:"id" json:"id"`
	OrganizationID uuid.UUID     `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdateNetworkPolicy(ctx context.Context, arg UpdateNetworkPolicyParams) (NetworkPolicy, error) {
	row := q.db.QueryRow(ctx, updateNetworkPolicy,
		arg.Name,
		arg.Action,
		arg.SourceCidr,
		arg.Status,
		arg.ID,
		arg.OrganizationID,
	)
	var i NetworkPolicy
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Action,
		&i.SourceCidr,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
