// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOrderFromCheckoutPayment = `-- name: CreateOrderFromCheckoutPayment :one
INSERT INTO orders (
    organization_id,
    checkout_id,
    payment_id,
    wallet_id,
    price_id,
    order_type,
    amount_minor,
    currency,
    completed_at,
    metadata
)
SELECT
    c.organization_id,
    c.id,
    p.id,
    c.wallet_id,
    c.price_id,
    c.checkout_type,
    c.amount_minor,
    c.currency,
    c.completed_at,
    c.metadata
FROM checkouts AS c
JOIN payments AS p
  ON p.checkout_id = c.id
 AND p.organization_id = c.organization_id
WHERE c.id = $1
  AND p.id = $2
  AND c.organization_id = $3
  AND c.status = 'succeeded'
  AND c.completed_at IS NOT NULL
  AND p.status = 'succeeded'
ON CONFLICT (checkout_id) DO NOTHING
RETURNING id, organization_id, checkout_id, payment_id, wallet_id, price_id, order_type, amount_minor, currency, completed_at, metadata, created_at
`

type CreateOrderFromCheckoutPaymentParams struct {
	CheckoutID     uuid.UUID `db:"checkout_id" json:"checkout_id"`
	PaymentID      uuid.UUID `db:"payment_id" json:"payment_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CreateOrderFromCheckoutPayment(ctx context.Context, arg CreateOrderFromCheckoutPaymentParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrderFromCheckoutPayment, arg.CheckoutID, arg.PaymentID, arg.OrganizationID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CheckoutID,
		&i.PaymentID,
		&i.WalletID,
		&i.PriceID,
		&i.OrderType,
		&i.AmountMinor,
		&i.Currency,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT o.id, o.organization_id, o.checkout_id, o.payment_id, o.wallet_id, o.price_id, o.order_type, o.amount_minor, o.currency, o.completed_at, o.metadata, o.created_at
FROM orders AS o
JOIN organizations AS org ON org.id = o.organization_id
WHERE o.organization_id = $1
  AND o.id = $2
  AND org.status = 'active'
  AND org.deleted_at IS NULL
LIMIT 1
`

type GetOrderParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.OrganizationID, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CheckoutID,
		&i.PaymentID,
		&i.WalletID,
		&i.PriceID,
		&i.OrderType,
		&i.AmountMinor,
		&i.Currency,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listOrdersByOrganization = `-- name: ListOrdersByOrganization :many
SELECT o.id, o.organization_id, o.checkout_id, o.payment_id, o.wallet_id, o.price_id, o.order_type, o.amount_minor, o.currency, o.completed_at, o.metadata, o.created_at
FROM orders AS o
JOIN organizations AS org ON org.id = o.organization_id
WHERE o.organization_id = $1
  AND org.status = 'active'
  AND org.deleted_at IS NULL
ORDER BY o.created_at DESC
`

func (q *Queries) ListOrdersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CheckoutID,
			&i.PaymentID,
			&i.WalletID,
			&i.PriceID,
			&i.OrderType,
			&i.AmountMinor,
			&i.Currency,
			&i.CompletedAt,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
