// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_invitations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE organization_invitations
SET
    status = 'accepted',
    accepted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
AND status = 'pending'
AND expires_at > NOW()
RETURNING id, organization_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, declined_at, revoked_at, created_at, updated_at
`

func (q *Queries) AcceptInvitation(ctx context.Context, id uuid.UUID) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, id)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO organization_invitations (
    organization_id,
    invited_by,
    email,
    role,
    token_hash,
    expires_at
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
FROM organizations AS t
JOIN users AS u ON u.id = $2
JOIN organization_members AS tm ON tm.organization_id = t.id AND tm.user_id = u.id
WHERE t.id = $1
AND t.status = 'active'
AND t.deleted_at IS NULL
AND u.disabled_at IS NULL
AND tm.status = 'active'
AND tm.role IN ('owner', 'admin')  -- Only owners and admins can invite
RETURNING id, organization_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, declined_at, revoked_at, created_at, updated_at
`

type CreateInvitationParams struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	InvitedBy      uuid.UUID          `db:"invited_by" json:"invited_by"`
	Email          string             `db:"email" json:"email"`
	Role           string             `db:"role" json:"role"`
	TokenHash      string             `db:"token_hash" json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.InvitedBy,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const declineInvitation = `-- name: DeclineInvitation :one
UPDATE organization_invitations
SET
    status = 'declined',
    declined_at = NOW(),
    updated_at = NOW()
WHERE id = $1
AND status = 'pending'
RETURNING id, organization_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, declined_at, revoked_at, created_at, updated_at
`

func (q *Queries) DeclineInvitation(ctx context.Context, id uuid.UUID) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, declineInvitation, id)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireStaleInvitations = `-- name: ExpireStaleInvitations :exec
UPDATE organization_invitations
SET
    status = 'expired',
    updated_at = NOW()
WHERE status = 'pending'
AND expires_at <= NOW()
`

func (q *Queries) ExpireStaleInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireStaleInvitations)
	return err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT i.id, i.organization_id, i.invited_by, i.email, i.role, i.token_hash, i.status, i.expires_at, i.accepted_at, i.declined_at, i.revoked_at, i.created_at, i.updated_at
FROM organization_invitations AS i
JOIN organizations AS t ON t.id = i.organization_id
WHERE i.token_hash = $1
AND i.status = 'pending'
AND i.expires_at > NOW()
AND t.status = 'active'
AND t.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingInvitationByEmailAndOrganization = `-- name: GetPendingInvitationByEmailAndOrganization :one
SELECT id, organization_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, declined_at, revoked_at, created_at, updated_at
FROM organization_invitations
WHERE organization_id = $1
AND email = $2
AND status = 'pending'
AND expires_at > NOW()
LIMIT 1
`

type GetPendingInvitationByEmailAndOrganizationParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Email          string    `db:"email" json:"email"`
}

func (q *Queries) GetPendingInvitationByEmailAndOrganization(ctx context.Context, arg GetPendingInvitationByEmailAndOrganizationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getPendingInvitationByEmailAndOrganization, arg.OrganizationID, arg.Email)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvitationsForEmail = `-- name: ListInvitationsForEmail :many
SELECT i.id, i.organization_id, i.invited_by, i.email, i.role, i.token_hash, i.status, i.expires_at, i.accepted_at, i.declined_at, i.revoked_at, i.created_at, i.updated_at, t.name AS organization_name
FROM organization_invitations AS i
JOIN organizations AS t ON t.id = i.organization_id
WHERE i.email = $1
AND i.status = 'pending'
AND i.expires_at > NOW()
AND t.status = 'active'
AND t.deleted_at IS NULL
ORDER BY i.created_at DESC
`

type ListInvitationsForEmailRow struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	OrganizationID   uuid.UUID          `db:"organization_id" json:"organization_id"`
	InvitedBy        uuid.UUID          `db:"invited_by" json:"invited_by"`
	Email            string             `db:"email" json:"email"`
	Role             string             `db:"role" json:"role"`
	TokenHash        string             `db:"token_hash" json:"token_hash"`
	Status           string             `db:"status" json:"status"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	AcceptedAt       pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	DeclinedAt       pgtype.Timestamptz `db:"declined_at" json:"declined_at"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OrganizationName string             `db:"organization_name" json:"organization_name"`
}

func (q *Queries) ListInvitationsForEmail(ctx context.Context, email string) ([]ListInvitationsForEmailRow, error) {
	rows, err := q.db.Query(ctx, listInvitationsForEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsForEmailRow{}
	for rows.Next() {
		var i ListInvitationsForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InvitedBy,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.DeclinedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsByOrganizationID = `-- name: ListPendingInvitationsByOrganizationID :many
SELECT i.id, i.organization_id, i.invited_by, i.email, i.role, i.token_hash, i.status, i.expires_at, i.accepted_at, i.declined_at, i.revoked_at, i.created_at, i.updated_at
FROM organization_invitations AS i
WHERE i.organization_id = $1
AND i.status = 'pending'
AND i.expires_at > NOW()
ORDER BY i.created_at DESC
`

func (q *Queries) ListPendingInvitationsByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]OrganizationInvitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationInvitation{}
	for rows.Next() {
		var i OrganizationInvitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InvitedBy,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.DeclinedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE organization_invitations
SET
    status = 'revoked',
    revoked_at = NOW(),
    updated_at = NOW()
WHERE id = $1
AND organization_id = $2
AND status = 'pending'
RETURNING id, organization_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, declined_at, revoked_at, created_at, updated_at
`

type RevokeInvitationParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, arg.ID, arg.OrganizationID)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
