// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    name
) VALUES (
    $1
)
RETURNING id, name, status, created_at, updated_at, deleted_at
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createOrganizationWithOwner = `-- name: CreateOrganizationWithOwner :one
WITH new_organization AS (
    INSERT INTO organizations (
        name
    )
    SELECT $1
    FROM users AS u
    WHERE u.id = $2
    AND u.disabled_at IS NULL
    RETURNING id, name, status, created_at, updated_at, deleted_at
), owner_membership AS (
    INSERT INTO organization_members (
        organization_id,
        user_id,
        role
    )
    SELECT
        o.id,
        $2,
        'owner'
    FROM new_organization AS o
    RETURNING organization_id
)
SELECT o.id, o.name, o.status, o.created_at, o.updated_at, o.deleted_at
FROM new_organization AS o
JOIN owner_membership AS om ON om.organization_id = o.id
`

type CreateOrganizationWithOwnerParams struct {
	Name   string    `db:"name" json:"name"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type CreateOrganizationWithOwnerRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) CreateOrganizationWithOwner(ctx context.Context, arg CreateOrganizationWithOwnerParams) (CreateOrganizationWithOwnerRow, error) {
	row := q.db.QueryRow(ctx, createOrganizationWithOwner, arg.Name, arg.UserID)
	var i CreateOrganizationWithOwnerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
UPDATE organizations
SET
    status = 'disabled',
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) DeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const getBackofficeOrganization = `-- name: GetBackofficeOrganization :one
SELECT
    o.id::TEXT AS id,
    o.name,
    o.status,
    COUNT(DISTINCT om.user_id) FILTER (WHERE om.status = 'active')::BIGINT AS member_count,
    COUNT(DISTINCT w.id) FILTER (WHERE w.status <> 'closed')::BIGINT AS wallet_count,
    COALESCE(string_agg(DISTINCT w.currency, ', ' ORDER BY w.currency) FILTER (WHERE w.status <> 'closed'), '—')::TEXT AS currencies,
    'prepaid'::TEXT AS billing_model,
    to_char(o.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') AS created_at,
    to_char(o.updated_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') AS updated_at
FROM organizations AS o
LEFT JOIN organization_members AS om ON om.organization_id = o.id
LEFT JOIN wallets AS w ON w.organization_id = o.id
WHERE o.id = $1
  AND o.deleted_at IS NULL
GROUP BY
    o.id,
    o.name,
    o.status,
    o.created_at,
    o.updated_at
LIMIT 1
`

type GetBackofficeOrganizationRow struct {
	ID           string `db:"id" json:"id"`
	Name         string `db:"name" json:"name"`
	Status       string `db:"status" json:"status"`
	MemberCount  int64  `db:"member_count" json:"member_count"`
	WalletCount  int64  `db:"wallet_count" json:"wallet_count"`
	Currencies   string `db:"currencies" json:"currencies"`
	BillingModel string `db:"billing_model" json:"billing_model"`
	CreatedAt    string `db:"created_at" json:"created_at"`
	UpdatedAt    string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetBackofficeOrganization(ctx context.Context, id uuid.UUID) (GetBackofficeOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getBackofficeOrganization, id)
	var i GetBackofficeOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MemberCount,
		&i.WalletCount,
		&i.Currencies,
		&i.BillingModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, status, created_at, updated_at, deleted_at
FROM organizations
WHERE id = $1
AND status = 'active'
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBackofficeOrganizationMembers = `-- name: ListBackofficeOrganizationMembers :many
SELECT
    u.id::TEXT AS user_id,
    COALESCE(u.name, '—') AS name,
    u.email::TEXT AS email,
    om.role,
    om.status,
    u.email_verified,
    u.is_platform_admin,
    CASE WHEN u.disabled_at IS NULL THEN 'active' ELSE 'disabled' END AS user_status,
    to_char(om.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') AS joined_at
FROM organization_members AS om
JOIN users AS u ON u.id = om.user_id
WHERE om.organization_id = $1
ORDER BY
    CASE om.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END,
    om.created_at ASC
`

type ListBackofficeOrganizationMembersRow struct {
	UserID          string `db:"user_id" json:"user_id"`
	Name            string `db:"name" json:"name"`
	Email           string `db:"email" json:"email"`
	Role            string `db:"role" json:"role"`
	Status          string `db:"status" json:"status"`
	EmailVerified   bool   `db:"email_verified" json:"email_verified"`
	IsPlatformAdmin bool   `db:"is_platform_admin" json:"is_platform_admin"`
	UserStatus      string `db:"user_status" json:"user_status"`
	JoinedAt        string `db:"joined_at" json:"joined_at"`
}

func (q *Queries) ListBackofficeOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListBackofficeOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listBackofficeOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackofficeOrganizationMembersRow{}
	for rows.Next() {
		var i ListBackofficeOrganizationMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.EmailVerified,
			&i.IsPlatformAdmin,
			&i.UserStatus,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackofficeOrganizations = `-- name: ListBackofficeOrganizations :many
SELECT
    o.id::TEXT AS id,
    o.name,
    o.status,
    COUNT(DISTINCT om.user_id) FILTER (WHERE om.status = 'active')::BIGINT AS member_count,
    COUNT(DISTINCT w.id) FILTER (WHERE w.status <> 'closed')::BIGINT AS wallet_count,
    COALESCE(string_agg(DISTINCT w.currency, ', ' ORDER BY w.currency) FILTER (WHERE w.status <> 'closed'), '—')::TEXT AS currencies,
    to_char(o.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') AS created_at
FROM organizations AS o
LEFT JOIN organization_members AS om ON om.organization_id = o.id
LEFT JOIN wallets AS w ON w.organization_id = o.id
WHERE o.deleted_at IS NULL
GROUP BY o.id, o.name, o.status, o.created_at
ORDER BY o.created_at DESC
LIMIT 100
`

type ListBackofficeOrganizationsRow struct {
	ID          string `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Status      string `db:"status" json:"status"`
	MemberCount int64  `db:"member_count" json:"member_count"`
	WalletCount int64  `db:"wallet_count" json:"wallet_count"`
	Currencies  string `db:"currencies" json:"currencies"`
	CreatedAt   string `db:"created_at" json:"created_at"`
}

func (q *Queries) ListBackofficeOrganizations(ctx context.Context) ([]ListBackofficeOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listBackofficeOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackofficeOrganizationsRow{}
	for rows.Next() {
		var i ListBackofficeOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.MemberCount,
			&i.WalletCount,
			&i.Currencies,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByUserID = `-- name: ListOrganizationsByUserID :many
SELECT t.id, t.name, t.status, t.created_at, t.updated_at, t.deleted_at, tm.role AS member_role
FROM organizations AS t
JOIN organization_members AS tm ON tm.organization_id = t.id
JOIN users AS u ON u.id = tm.user_id
WHERE tm.user_id = $1
AND u.disabled_at IS NULL
AND tm.status = 'active'
AND t.status = 'active'
AND t.deleted_at IS NULL
ORDER BY t.created_at DESC
`

type ListOrganizationsByUserIDRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Status     string             `db:"status" json:"status"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	MemberRole string             `db:"member_role" json:"member_role"`
}

func (q *Queries) ListOrganizationsByUserID(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsByUserIDRow{}
	for rows.Next() {
		var i ListOrganizationsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET
    name = COALESCE($1, name),
    updated_at = NOW()
WHERE id = $2
AND status = 'active'
AND deleted_at IS NULL
RETURNING id, name, status, created_at, updated_at, deleted_at
`

type UpdateOrganizationParams struct {
	Name *string   `db:"name" json:"name"`
	ID   uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.Name, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
