// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_tokens.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganizationToken = `-- name: CreateOrganizationToken :one
INSERT INTO organization_tokens (
    organization_id,
    created_by,
    name,
    description,
    token_hash,
    token_prefix,
    scopes,
    expires_at
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::jsonb,
    $8::timestamptz
FROM organizations AS t
JOIN users AS u ON u.id = $2
JOIN organization_members AS tm ON tm.organization_id = t.id AND tm.user_id = u.id
WHERE t.id = $1
AND t.status = 'active'
AND t.deleted_at IS NULL
AND u.disabled_at IS NULL
AND tm.status = 'active'
AND tm.role IN ('owner', 'admin')
RETURNING id, organization_id, created_by, name, description, token_hash, token_prefix, scopes, last_used_at, last_used_ip, expires_at, disabled_at, created_at, updated_at
`

type CreateOrganizationTokenParams struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	CreatedBy      *uuid.UUID         `db:"created_by" json:"created_by"`
	Name           string             `db:"name" json:"name"`
	Description    *string            `db:"description" json:"description"`
	TokenHash      string             `db:"token_hash" json:"token_hash"`
	TokenPrefix    string             `db:"token_prefix" json:"token_prefix"`
	Scopes         []byte             `db:"scopes" json:"scopes"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateOrganizationToken(ctx context.Context, arg CreateOrganizationTokenParams) (OrganizationToken, error) {
	row := q.db.QueryRow(ctx, createOrganizationToken,
		arg.OrganizationID,
		arg.CreatedBy,
		arg.Name,
		arg.Description,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i OrganizationToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationTokenByID = `-- name: GetOrganizationTokenByID :one
SELECT ak.id, ak.organization_id, ak.created_by, ak.name, ak.description, ak.token_hash, ak.token_prefix, ak.scopes, ak.last_used_at, ak.last_used_ip, ak.expires_at, ak.disabled_at, ak.created_at, ak.updated_at
FROM organization_tokens AS ak
WHERE ak.id = $1
AND ak.organization_id = $2
LIMIT 1
`

type GetOrganizationTokenByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetOrganizationTokenByID(ctx context.Context, arg GetOrganizationTokenByIDParams) (OrganizationToken, error) {
	row := q.db.QueryRow(ctx, getOrganizationTokenByID, arg.ID, arg.OrganizationID)
	var i OrganizationToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationTokenByTokenHash = `-- name: GetOrganizationTokenByTokenHash :one
SELECT ak.id, ak.organization_id, ak.created_by, ak.name, ak.description, ak.token_hash, ak.token_prefix, ak.scopes, ak.last_used_at, ak.last_used_ip, ak.expires_at, ak.disabled_at, ak.created_at, ak.updated_at
FROM organization_tokens AS ak
JOIN organizations AS t ON t.id = ak.organization_id
WHERE ak.token_hash = $1
AND (ak.expires_at IS NULL OR ak.expires_at > NOW())
AND t.status = 'active'
AND t.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetOrganizationTokenByTokenHash(ctx context.Context, tokenHash string) (OrganizationToken, error) {
	row := q.db.QueryRow(ctx, getOrganizationTokenByTokenHash, tokenHash)
	var i OrganizationToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationTokensByOrganizationID = `-- name: ListOrganizationTokensByOrganizationID :many
SELECT
    ak.id,
    ak.name,
    ak.description,
    ak.token_prefix,
    ak.scopes,
    ak.last_used_at,
    ak.last_used_ip,
    ak.expires_at,
    ak.created_at,
    u.name AS created_by
FROM organization_tokens AS ak
JOIN users AS u ON u.id = ak.created_by
WHERE ak.organization_id = $1
ORDER BY ak.created_at DESC
`

type ListOrganizationTokensByOrganizationIDRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	Scopes      []byte             `db:"scopes" json:"scopes"`
	LastUsedAt  pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	LastUsedIp  *netip.Addr        `db:"last_used_ip" json:"last_used_ip"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy   *string            `db:"created_by" json:"created_by"`
}

func (q *Queries) ListOrganizationTokensByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationTokensByOrganizationIDRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationTokensByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationTokensByOrganizationIDRow{}
	for rows.Next() {
		var i ListOrganizationTokensByOrganizationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TokenPrefix,
			&i.Scopes,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchOrganizationToken = `-- name: TouchOrganizationToken :exec
UPDATE organization_tokens
SET
    last_used_at = NOW(),
    last_used_ip = $1::inet,
    updated_at = NOW()
WHERE id = $2
AND (last_used_at IS NULL OR last_used_at < NOW() - INTERVAL '1 minute')
`

type TouchOrganizationTokenParams struct {
	LastUsedIp *netip.Addr `db:"last_used_ip" json:"last_used_ip"`
	ID         uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) TouchOrganizationToken(ctx context.Context, arg TouchOrganizationTokenParams) error {
	_, err := q.db.Exec(ctx, touchOrganizationToken, arg.LastUsedIp, arg.ID)
	return err
}

const updateOrganizationToken = `-- name: UpdateOrganizationToken :one
UPDATE organization_tokens
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    scopes = COALESCE($3::jsonb, scopes),
    expires_at = COALESCE($4, expires_at),
    updated_at = NOW()
WHERE id = $5
AND organization_id = $6
RETURNING id, organization_id, created_by, name, description, token_hash, token_prefix, scopes, last_used_at, last_used_ip, expires_at, disabled_at, created_at, updated_at
`

type UpdateOrganizationTokenParams struct {
	Name           *string            `db:"name" json:"name"`
	Description    *string            `db:"description" json:"description"`
	Scopes         []byte             `db:"scopes" json:"scopes"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdateOrganizationToken(ctx context.Context, arg UpdateOrganizationTokenParams) (OrganizationToken, error) {
	row := q.db.QueryRow(ctx, updateOrganizationToken,
		arg.Name,
		arg.Description,
		arg.Scopes,
		arg.ExpiresAt,
		arg.ID,
		arg.OrganizationID,
	)
	var i OrganizationToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
