// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    organization_id,
    invoice_id,
    provider,
    provider_payment_id,
    amount,
    currency,
    status,
    paid_at,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    COALESCE($7, 'pending'),
    $8,
    COALESCE($9, '{}'::jsonb)
)
RETURNING id, organization_id, invoice_id, provider, provider_payment_id, amount, currency, status, paid_at, metadata, created_at, updated_at
`

type CreatePaymentParams struct {
	OrganizationID    uuid.UUID          `db:"organization_id" json:"organization_id"`
	InvoiceID         *uuid.UUID         `db:"invoice_id" json:"invoice_id"`
	Provider          string             `db:"provider" json:"provider"`
	ProviderPaymentID *string            `db:"provider_payment_id" json:"provider_payment_id"`
	Amount            int64              `db:"amount" json:"amount"`
	Currency          string             `db:"currency" json:"currency"`
	Status            interface{}        `db:"status" json:"status"`
	PaidAt            pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	Metadata          interface{}        `db:"metadata" json:"metadata"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrganizationID,
		arg.InvoiceID,
		arg.Provider,
		arg.ProviderPaymentID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.PaidAt,
		arg.Metadata,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, organization_id, invoice_id, provider, provider_payment_id, amount, currency, status, paid_at, metadata, created_at, updated_at
FROM payments
WHERE organization_id = $1
  AND id = $2
LIMIT 1
`

type GetPaymentParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, arg.OrganizationID, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderID = `-- name: GetPaymentByProviderID :one
SELECT id, organization_id, invoice_id, provider, provider_payment_id, amount, currency, status, paid_at, metadata, created_at, updated_at
FROM payments
WHERE provider = $1
  AND provider_payment_id = $2
LIMIT 1
`

type GetPaymentByProviderIDParams struct {
	Provider          string  `db:"provider" json:"provider"`
	ProviderPaymentID *string `db:"provider_payment_id" json:"provider_payment_id"`
}

func (q *Queries) GetPaymentByProviderID(ctx context.Context, arg GetPaymentByProviderIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderID, arg.Provider, arg.ProviderPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByInvoice = `-- name: ListPaymentsByInvoice :many
SELECT id, organization_id, invoice_id, provider, provider_payment_id, amount, currency, status, paid_at, metadata, created_at, updated_at
FROM payments
WHERE organization_id = $1
  AND invoice_id = $2
ORDER BY created_at DESC
`

type ListPaymentsByInvoiceParams struct {
	OrganizationID uuid.UUID  `db:"organization_id" json:"organization_id"`
	InvoiceID      *uuid.UUID `db:"invoice_id" json:"invoice_id"`
}

func (q *Queries) ListPaymentsByInvoice(ctx context.Context, arg ListPaymentsByInvoiceParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByInvoice, arg.OrganizationID, arg.InvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InvoiceID,
			&i.Provider,
			&i.ProviderPaymentID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaidAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByOrganization = `-- name: ListPaymentsByOrganization :many
SELECT id, organization_id, invoice_id, provider, provider_payment_id, amount, currency, status, paid_at, metadata, created_at, updated_at
FROM payments
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InvoiceID,
			&i.Provider,
			&i.ProviderPaymentID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaidAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET
    status = $1,
    paid_at = COALESCE($2, paid_at),
    metadata = COALESCE($3, metadata),
    updated_at = NOW()
WHERE organization_id = $4
  AND id = $5
RETURNING id, organization_id, invoice_id, provider, provider_payment_id, amount, currency, status, paid_at, metadata, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	Status         string             `db:"status" json:"status"`
	PaidAt         pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus,
		arg.Status,
		arg.PaidAt,
		arg.Metadata,
		arg.OrganizationID,
		arg.ID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
