// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    checkout_order_id,
    organization_id,
    provider,
    provider_payment_id,
    amount,
    currency,
    status,
    paid_at,
    metadata
)
SELECT
    co.id AS checkout_order_id,
    co.organization_id,
    co.provider,
    $1 AS provider_payment_id,
    $2 AS amount,
    $3 AS currency,
    COALESCE($4, 'pending') AS status,
    $5 AS paid_at,
    COALESCE($6, '{}'::jsonb) AS metadata
FROM checkout_orders AS co
JOIN organizations AS o ON o.id = co.organization_id
WHERE co.id = $7
  AND co.organization_id = $8
  AND co.provider = $9
  AND co.amount = $2
  AND co.currency = $3
  AND o.status = 'active'
  AND o.deleted_at IS NULL
RETURNING id, checkout_order_id, organization_id, provider, provider_payment_id, amount, currency, status, paid_at, metadata, created_at, updated_at
`

type CreatePaymentParams struct {
	ProviderPaymentID *string            `db:"provider_payment_id" json:"provider_payment_id"`
	Amount            int64              `db:"amount" json:"amount"`
	Currency          string             `db:"currency" json:"currency"`
	Status            *string            `db:"status" json:"status"`
	PaidAt            pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
	CheckoutOrderID   uuid.UUID          `db:"checkout_order_id" json:"checkout_order_id"`
	OrganizationID    uuid.UUID          `db:"organization_id" json:"organization_id"`
	Provider          string             `db:"provider" json:"provider"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ProviderPaymentID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.PaidAt,
		arg.Metadata,
		arg.CheckoutOrderID,
		arg.OrganizationID,
		arg.Provider,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutOrderID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT p.id, p.checkout_order_id, p.organization_id, p.provider, p.provider_payment_id, p.amount, p.currency, p.status, p.paid_at, p.metadata, p.created_at, p.updated_at
FROM payments AS p
JOIN organizations AS o ON o.id = p.organization_id
WHERE p.organization_id = $1
  AND p.id = $2
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetPaymentParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, arg.OrganizationID, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutOrderID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderID = `-- name: GetPaymentByProviderID :one
SELECT p.id, p.checkout_order_id, p.organization_id, p.provider, p.provider_payment_id, p.amount, p.currency, p.status, p.paid_at, p.metadata, p.created_at, p.updated_at
FROM payments AS p
JOIN organizations AS o ON o.id = p.organization_id
WHERE p.provider = $1
  AND p.provider_payment_id = $2
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetPaymentByProviderIDParams struct {
	Provider          string  `db:"provider" json:"provider"`
	ProviderPaymentID *string `db:"provider_payment_id" json:"provider_payment_id"`
}

func (q *Queries) GetPaymentByProviderID(ctx context.Context, arg GetPaymentByProviderIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderID, arg.Provider, arg.ProviderPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutOrderID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByOrganization = `-- name: ListPaymentsByOrganization :many
SELECT p.id, p.checkout_order_id, p.organization_id, p.provider, p.provider_payment_id, p.amount, p.currency, p.status, p.paid_at, p.metadata, p.created_at, p.updated_at
FROM payments AS p
JOIN organizations AS o ON o.id = p.organization_id
WHERE p.organization_id = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
ORDER BY p.created_at DESC
`

func (q *Queries) ListPaymentsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutOrderID,
			&i.OrganizationID,
			&i.Provider,
			&i.ProviderPaymentID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaidAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments AS p
SET
    status = $1,
    paid_at = COALESCE($2, p.paid_at),
    metadata = COALESCE($3, p.metadata),
    updated_at = NOW()
FROM organizations AS o
WHERE p.organization_id = $4
  AND p.id = $5
  AND o.id = p.organization_id
  AND o.status = 'active'
  AND o.deleted_at IS NULL
RETURNING o.id, name, o.status, o.created_at, o.updated_at, deleted_at, p.id, checkout_order_id, organization_id, provider, provider_payment_id, amount, currency, p.status, paid_at, metadata, p.created_at, p.updated_at
`

type UpdatePaymentStatusParams struct {
	Status         string             `db:"status" json:"status"`
	PaidAt         pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID          `db:"id" json:"id"`
}

type UpdatePaymentStatusRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Status            string             `db:"status" json:"status"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	ID_2              uuid.UUID          `db:"id_2" json:"id_2"`
	CheckoutOrderID   uuid.UUID          `db:"checkout_order_id" json:"checkout_order_id"`
	OrganizationID    uuid.UUID          `db:"organization_id" json:"organization_id"`
	Provider          string             `db:"provider" json:"provider"`
	ProviderPaymentID *string            `db:"provider_payment_id" json:"provider_payment_id"`
	Amount            int64              `db:"amount" json:"amount"`
	Currency          string             `db:"currency" json:"currency"`
	Status_2          string             `db:"status_2" json:"status_2"`
	PaidAt            pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
	CreatedAt_2       pgtype.Timestamptz `db:"created_at_2" json:"created_at_2"`
	UpdatedAt_2       pgtype.Timestamptz `db:"updated_at_2" json:"updated_at_2"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (UpdatePaymentStatusRow, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus,
		arg.Status,
		arg.PaidAt,
		arg.Metadata,
		arg.OrganizationID,
		arg.ID,
	)
	var i UpdatePaymentStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ID_2,
		&i.CheckoutOrderID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status_2,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}
