// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    checkout_id,
    organization_id,
    provider,
    provider_payment_id,
    amount_minor,
    currency,
    status,
    paid_at,
    metadata
)
SELECT
    c.id AS checkout_id,
    c.organization_id,
    c.provider,
    $1 AS provider_payment_id,
    $2 AS amount_minor,
    $3 AS currency,
    COALESCE($4, 'pending') AS status,
    $5 AS paid_at,
    COALESCE($6, '{}'::jsonb) AS metadata
FROM checkouts AS c
JOIN organizations AS o ON o.id = c.organization_id
WHERE c.id = $7
  AND c.organization_id = $8
  AND c.provider = $9
  AND c.amount_minor = $2
  AND c.currency = $3
  AND o.status = 'active'
  AND o.deleted_at IS NULL
RETURNING id, checkout_id, organization_id, provider, provider_payment_id, amount_minor, currency, status, paid_at, metadata, created_at, updated_at
`

type CreatePaymentParams struct {
	ProviderPaymentID *string            `db:"provider_payment_id" json:"provider_payment_id"`
	AmountMinor       int64              `db:"amount_minor" json:"amount_minor"`
	Currency          string             `db:"currency" json:"currency"`
	Status            *string            `db:"status" json:"status"`
	PaidAt            pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
	CheckoutID        uuid.UUID          `db:"checkout_id" json:"checkout_id"`
	OrganizationID    uuid.UUID          `db:"organization_id" json:"organization_id"`
	Provider          string             `db:"provider" json:"provider"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ProviderPaymentID,
		arg.AmountMinor,
		arg.Currency,
		arg.Status,
		arg.PaidAt,
		arg.Metadata,
		arg.CheckoutID,
		arg.OrganizationID,
		arg.Provider,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT p.id, p.checkout_id, p.organization_id, p.provider, p.provider_payment_id, p.amount_minor, p.currency, p.status, p.paid_at, p.metadata, p.created_at, p.updated_at
FROM payments AS p
JOIN organizations AS o ON o.id = p.organization_id
WHERE p.organization_id = $1
  AND p.id = $2
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetPaymentParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, arg.OrganizationID, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByCheckoutOrder = `-- name: GetPaymentByCheckoutOrder :one
SELECT p.id, p.checkout_id, p.organization_id, p.provider, p.provider_payment_id, p.amount_minor, p.currency, p.status, p.paid_at, p.metadata, p.created_at, p.updated_at
FROM payments AS p
JOIN organizations AS o ON o.id = p.organization_id
WHERE p.organization_id = $1
  AND p.checkout_id = $2
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetPaymentByCheckoutOrderParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	CheckoutID     uuid.UUID `db:"checkout_id" json:"checkout_id"`
}

func (q *Queries) GetPaymentByCheckoutOrder(ctx context.Context, arg GetPaymentByCheckoutOrderParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByCheckoutOrder, arg.OrganizationID, arg.CheckoutID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderID = `-- name: GetPaymentByProviderID :one
SELECT p.id, p.checkout_id, p.organization_id, p.provider, p.provider_payment_id, p.amount_minor, p.currency, p.status, p.paid_at, p.metadata, p.created_at, p.updated_at
FROM payments AS p
JOIN organizations AS o ON o.id = p.organization_id
WHERE p.provider = $1
  AND p.provider_payment_id = $2
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetPaymentByProviderIDParams struct {
	Provider          string  `db:"provider" json:"provider"`
	ProviderPaymentID *string `db:"provider_payment_id" json:"provider_payment_id"`
}

func (q *Queries) GetPaymentByProviderID(ctx context.Context, arg GetPaymentByProviderIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderID, arg.Provider, arg.ProviderPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByOrganization = `-- name: ListPaymentsByOrganization :many
SELECT p.id, p.checkout_id, p.organization_id, p.provider, p.provider_payment_id, p.amount_minor, p.currency, p.status, p.paid_at, p.metadata, p.created_at, p.updated_at
FROM payments AS p
JOIN organizations AS o ON o.id = p.organization_id
WHERE p.organization_id = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
ORDER BY p.created_at DESC
`

func (q *Queries) ListPaymentsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutID,
			&i.OrganizationID,
			&i.Provider,
			&i.ProviderPaymentID,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.PaidAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentProviderID = `-- name: SetPaymentProviderID :one
UPDATE payments AS p
SET provider_payment_id = $1,
    status = $2,
    updated_at = NOW()
FROM organizations AS o
WHERE p.organization_id = $3
  AND p.id = $4
  AND p.provider_payment_id IS NULL
  AND o.id = p.organization_id
  AND o.status = 'active'
  AND o.deleted_at IS NULL
RETURNING p.id, p.checkout_id, p.organization_id, p.provider, p.provider_payment_id, p.amount_minor, p.currency, p.status, p.paid_at, p.metadata, p.created_at, p.updated_at
`

type SetPaymentProviderIDParams struct {
	ProviderPaymentID *string   `db:"provider_payment_id" json:"provider_payment_id"`
	Status            string    `db:"status" json:"status"`
	OrganizationID    uuid.UUID `db:"organization_id" json:"organization_id"`
	ID                uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) SetPaymentProviderID(ctx context.Context, arg SetPaymentProviderIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, setPaymentProviderID,
		arg.ProviderPaymentID,
		arg.Status,
		arg.OrganizationID,
		arg.ID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments AS p
SET
    status = $1,
    paid_at = COALESCE($2, p.paid_at),
    metadata = COALESCE($3, p.metadata),
    updated_at = NOW()
FROM organizations AS o
WHERE p.organization_id = $4
  AND p.id = $5
  AND o.id = p.organization_id
  AND o.status = 'active'
  AND o.deleted_at IS NULL
RETURNING p.id, p.checkout_id, p.organization_id, p.provider, p.provider_payment_id, p.amount_minor, p.currency, p.status, p.paid_at, p.metadata, p.created_at, p.updated_at
`

type UpdatePaymentStatusParams struct {
	Status         string             `db:"status" json:"status"`
	PaidAt         pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus,
		arg.Status,
		arg.PaidAt,
		arg.Metadata,
		arg.OrganizationID,
		arg.ID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
