// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phone_numbers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBYOCPhoneNumber = `-- name: CreateBYOCPhoneNumber :one
INSERT INTO phone_numbers (
    organization_id,
    number,
    country_code,
    provisioning_mode,
    carrier_connection_id,
    provider_id,
    provider_resource_id,
    voice_enabled,
    sms_enabled
)
SELECT
    $1 AS organization_id,
    $2 AS number,
    $3 AS country_code,
    'byoc' AS provisioning_mode,
    $4 AS carrier_connection_id,
    NULL::UUID AS provider_id,
    NULL::TEXT AS provider_resource_id,
    COALESCE($5, true) AS voice_enabled,
    COALESCE($6, false) AS sms_enabled
FROM organizations AS o
LEFT JOIN carrier_connections AS cc
  ON cc.id = $4::UUID
 AND cc.scope = 'organization'
 AND cc.organization_id = $1
 AND cc.status = 'active'
WHERE o.id = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
  AND (
      $4::UUID IS NULL
      OR cc.id IS NOT NULL
  )
RETURNING id, organization_id, number, country_code, provisioning_mode, carrier_connection_id, provider_id, provider_resource_id, voice_enabled, sms_enabled, status, created_at, updated_at
`

type CreateBYOCPhoneNumberParams struct {
	OrganizationID      uuid.UUID  `db:"organization_id" json:"organization_id"`
	Number              string     `db:"number" json:"number"`
	CountryCode         string     `db:"country_code" json:"country_code"`
	CarrierConnectionID *uuid.UUID `db:"carrier_connection_id" json:"carrier_connection_id"`
	VoiceEnabled        *bool      `db:"voice_enabled" json:"voice_enabled"`
	SmsEnabled          *bool      `db:"sms_enabled" json:"sms_enabled"`
}

func (q *Queries) CreateBYOCPhoneNumber(ctx context.Context, arg CreateBYOCPhoneNumberParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, createBYOCPhoneNumber,
		arg.OrganizationID,
		arg.Number,
		arg.CountryCode,
		arg.CarrierConnectionID,
		arg.VoiceEnabled,
		arg.SmsEnabled,
	)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManagedPhoneNumber = `-- name: CreateManagedPhoneNumber :one
INSERT INTO phone_numbers (
    organization_id,
    number,
    country_code,
    provisioning_mode,
    carrier_connection_id,
    provider_id,
    provider_resource_id,
    voice_enabled,
    sms_enabled
)
SELECT
    $1 AS organization_id,
    $2 AS number,
    $3 AS country_code,
    'managed' AS provisioning_mode,
    $4 AS carrier_connection_id,
    $5 AS provider_id,
    $6 AS provider_resource_id,
    COALESCE($7, true) AS voice_enabled,
    COALESCE($8, false) AS sms_enabled
FROM organizations AS o
JOIN carrier_providers AS cp
  ON cp.id = $5
 AND cp.status = 'active'
LEFT JOIN carrier_connections AS cc
  ON cc.id = $4::UUID
 AND cc.scope = 'platform'
 AND cc.organization_id IS NULL
 AND cc.provider_id = cp.id
 AND cc.status = 'active'
WHERE o.id = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
  AND length(btrim($6)) > 0
  AND (
      $4::UUID IS NULL
      OR cc.id IS NOT NULL
  )
RETURNING id, organization_id, number, country_code, provisioning_mode, carrier_connection_id, provider_id, provider_resource_id, voice_enabled, sms_enabled, status, created_at, updated_at
`

type CreateManagedPhoneNumberParams struct {
	OrganizationID      uuid.UUID  `db:"organization_id" json:"organization_id"`
	Number              string     `db:"number" json:"number"`
	CountryCode         string     `db:"country_code" json:"country_code"`
	CarrierConnectionID *uuid.UUID `db:"carrier_connection_id" json:"carrier_connection_id"`
	ProviderID          *uuid.UUID `db:"provider_id" json:"provider_id"`
	ProviderResourceID  *string    `db:"provider_resource_id" json:"provider_resource_id"`
	VoiceEnabled        *bool      `db:"voice_enabled" json:"voice_enabled"`
	SmsEnabled          *bool      `db:"sms_enabled" json:"sms_enabled"`
}

func (q *Queries) CreateManagedPhoneNumber(ctx context.Context, arg CreateManagedPhoneNumberParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, createManagedPhoneNumber,
		arg.OrganizationID,
		arg.Number,
		arg.CountryCode,
		arg.CarrierConnectionID,
		arg.ProviderID,
		arg.ProviderResourceID,
		arg.VoiceEnabled,
		arg.SmsEnabled,
	)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableManagedPhoneNumberForRelease = `-- name: DisableManagedPhoneNumberForRelease :one
UPDATE phone_numbers
SET
    status = 'disabled',
    voice_enabled = false,
    sms_enabled = false,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND provisioning_mode = 'managed'
  AND status IN ('active', 'disabled')
RETURNING id, organization_id, number, country_code, provisioning_mode, carrier_connection_id, provider_id, provider_resource_id, voice_enabled, sms_enabled, status, created_at, updated_at
`

type DisableManagedPhoneNumberForReleaseParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) DisableManagedPhoneNumberForRelease(ctx context.Context, arg DisableManagedPhoneNumberForReleaseParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, disableManagedPhoneNumberForRelease, arg.ID, arg.OrganizationID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureManagedPhoneNumberForProviderOperation = `-- name: EnsureManagedPhoneNumberForProviderOperation :one
INSERT INTO phone_numbers (
    organization_id,
    number,
    country_code,
    provisioning_mode,
    carrier_connection_id,
    provider_id,
    provider_resource_id,
    voice_enabled,
    sms_enabled,
    status
)
SELECT
    $1,
    $2,
    $3,
    'managed',
    cc.id,
    $4,
    $5,
    true,
    false,
    'active'
FROM carrier_connections AS cc
WHERE cc.id = $6
  AND cc.scope = 'platform'
  AND cc.provider_id = $4
  AND cc.status = 'active'
ON CONFLICT (provider_id, provider_resource_id)
    WHERE provider_id IS NOT NULL AND provider_resource_id IS NOT NULL
DO UPDATE SET updated_at = phone_numbers.updated_at
WHERE phone_numbers.organization_id = EXCLUDED.organization_id
  AND phone_numbers.status <> 'released'
RETURNING id, organization_id, number, country_code, provisioning_mode, carrier_connection_id, provider_id, provider_resource_id, voice_enabled, sms_enabled, status, created_at, updated_at
`

type EnsureManagedPhoneNumberForProviderOperationParams struct {
	OrganizationID      uuid.UUID  `db:"organization_id" json:"organization_id"`
	Number              string     `db:"number" json:"number"`
	CountryCode         string     `db:"country_code" json:"country_code"`
	ProviderID          *uuid.UUID `db:"provider_id" json:"provider_id"`
	ProviderResourceID  *string    `db:"provider_resource_id" json:"provider_resource_id"`
	CarrierConnectionID uuid.UUID  `db:"carrier_connection_id" json:"carrier_connection_id"`
}

func (q *Queries) EnsureManagedPhoneNumberForProviderOperation(ctx context.Context, arg EnsureManagedPhoneNumberForProviderOperationParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, ensureManagedPhoneNumberForProviderOperation,
		arg.OrganizationID,
		arg.Number,
		arg.CountryCode,
		arg.ProviderID,
		arg.ProviderResourceID,
		arg.CarrierConnectionID,
	)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureTransitManagedPhoneNumberForProviderOperation = `-- name: EnsureTransitManagedPhoneNumberForProviderOperation :one
INSERT INTO phone_numbers (
    organization_id,
    number,
    country_code,
    provisioning_mode,
    carrier_connection_id,
    provider_id,
    provider_resource_id,
    voice_enabled,
    sms_enabled,
    status
)
SELECT
    $1,
    $2,
    $3,
    'managed',
    NULL,
    NULL,
    NULL,
    true,
    false,
    'active'
FROM organizations AS o
WHERE o.id = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
ON CONFLICT (number)
    WHERE status <> 'released'
DO UPDATE SET updated_at = phone_numbers.updated_at
WHERE phone_numbers.organization_id = EXCLUDED.organization_id
  AND phone_numbers.provisioning_mode = 'managed'
  AND phone_numbers.provider_id IS NULL
  AND phone_numbers.provider_resource_id IS NULL
  AND phone_numbers.status = 'active'
RETURNING id, organization_id, number, country_code, provisioning_mode, carrier_connection_id, provider_id, provider_resource_id, voice_enabled, sms_enabled, status, created_at, updated_at
`

type EnsureTransitManagedPhoneNumberForProviderOperationParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Number         string    `db:"number" json:"number"`
	CountryCode    string    `db:"country_code" json:"country_code"`
}

func (q *Queries) EnsureTransitManagedPhoneNumberForProviderOperation(ctx context.Context, arg EnsureTransitManagedPhoneNumberForProviderOperationParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, ensureTransitManagedPhoneNumberForProviderOperation, arg.OrganizationID, arg.Number, arg.CountryCode)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhoneNumberByID = `-- name: GetPhoneNumberByID :one
SELECT pn.id, pn.organization_id, pn.number, pn.country_code, pn.provisioning_mode, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.created_at, pn.updated_at
FROM phone_numbers AS pn
JOIN organizations AS o ON o.id = pn.organization_id
WHERE pn.id = $1
  AND pn.organization_id = $2
  AND pn.status = 'active'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetPhoneNumberByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetPhoneNumberByID(ctx context.Context, arg GetPhoneNumberByIDParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, getPhoneNumberByID, arg.ID, arg.OrganizationID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhoneNumberByNumber = `-- name: GetPhoneNumberByNumber :one
SELECT pn.id, pn.organization_id, pn.number, pn.country_code, pn.provisioning_mode, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.created_at, pn.updated_at
FROM phone_numbers AS pn
JOIN organizations AS o ON o.id = pn.organization_id
WHERE pn.number = $1
  AND pn.organization_id = $2
  AND pn.status = 'active'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetPhoneNumberByNumberParams struct {
	Number         string    `db:"number" json:"number"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetPhoneNumberByNumber(ctx context.Context, arg GetPhoneNumberByNumberParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, getPhoneNumberByNumber, arg.Number, arg.OrganizationID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhoneNumberForRelease = `-- name: GetPhoneNumberForRelease :one
SELECT pn.id, pn.organization_id, pn.number, pn.country_code, pn.provisioning_mode, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.created_at, pn.updated_at
FROM phone_numbers AS pn
JOIN organizations AS o ON o.id = pn.organization_id
WHERE pn.id = $1
  AND pn.organization_id = $2
  AND pn.status IN ('active', 'disabled')
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetPhoneNumberForReleaseParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetPhoneNumberForRelease(ctx context.Context, arg GetPhoneNumberForReleaseParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, getPhoneNumberForRelease, arg.ID, arg.OrganizationID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoiceBindingByNumber = `-- name: GetVoiceBindingByNumber :one
SELECT
    vb.id AS binding_id,
    vb.voice_application_id,
    va.name AS application_name,
    va.ring_timeout_seconds,
    va.caller_id AS application_caller_id,
    pn.id AS phone_number_id,
    pn.number,
    pn.organization_id
FROM phone_numbers AS pn
JOIN voice_bindings AS vb ON vb.phone_number_id = pn.id
JOIN voice_applications AS va ON va.id = vb.voice_application_id
JOIN organizations AS o ON o.id = pn.organization_id
WHERE pn.number = $1
  AND pn.status = 'active'
  AND pn.voice_enabled = true
  AND va.status = 'active'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetVoiceBindingByNumberRow struct {
	BindingID           uuid.UUID `db:"binding_id" json:"binding_id"`
	VoiceApplicationID  uuid.UUID `db:"voice_application_id" json:"voice_application_id"`
	ApplicationName     string    `db:"application_name" json:"application_name"`
	RingTimeoutSeconds  int32     `db:"ring_timeout_seconds" json:"ring_timeout_seconds"`
	ApplicationCallerID *string   `db:"application_caller_id" json:"application_caller_id"`
	PhoneNumberID       uuid.UUID `db:"phone_number_id" json:"phone_number_id"`
	Number              string    `db:"number" json:"number"`
	OrganizationID      uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetVoiceBindingByNumber(ctx context.Context, number string) (GetVoiceBindingByNumberRow, error) {
	row := q.db.QueryRow(ctx, getVoiceBindingByNumber, number)
	var i GetVoiceBindingByNumberRow
	err := row.Scan(
		&i.BindingID,
		&i.VoiceApplicationID,
		&i.ApplicationName,
		&i.RingTimeoutSeconds,
		&i.ApplicationCallerID,
		&i.PhoneNumberID,
		&i.Number,
		&i.OrganizationID,
	)
	return i, err
}

const listPhoneNumbersByCountry = `-- name: ListPhoneNumbersByCountry :many
SELECT pn.id, pn.organization_id, pn.number, pn.country_code, pn.provisioning_mode, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.created_at, pn.updated_at
FROM phone_numbers AS pn
WHERE pn.organization_id = $1
  AND pn.country_code = $2
  AND pn.status = 'active'
ORDER BY pn.number ASC
`

type ListPhoneNumbersByCountryParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	CountryCode    string    `db:"country_code" json:"country_code"`
}

func (q *Queries) ListPhoneNumbersByCountry(ctx context.Context, arg ListPhoneNumbersByCountryParams) ([]PhoneNumber, error) {
	rows, err := q.db.Query(ctx, listPhoneNumbersByCountry, arg.OrganizationID, arg.CountryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhoneNumber{}
	for rows.Next() {
		var i PhoneNumber
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Number,
			&i.CountryCode,
			&i.ProvisioningMode,
			&i.CarrierConnectionID,
			&i.ProviderID,
			&i.ProviderResourceID,
			&i.VoiceEnabled,
			&i.SmsEnabled,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhoneNumbersByOrganizationID = `-- name: ListPhoneNumbersByOrganizationID :many
SELECT pn.id, pn.organization_id, pn.number, pn.country_code, pn.provisioning_mode, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.created_at, pn.updated_at
FROM phone_numbers AS pn
WHERE pn.organization_id = $1
  AND pn.status = 'active'
ORDER BY pn.created_at DESC
`

func (q *Queries) ListPhoneNumbersByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]PhoneNumber, error) {
	rows, err := q.db.Query(ctx, listPhoneNumbersByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhoneNumber{}
	for rows.Next() {
		var i PhoneNumber
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Number,
			&i.CountryCode,
			&i.ProvisioningMode,
			&i.CarrierConnectionID,
			&i.ProviderID,
			&i.ProviderResourceID,
			&i.VoiceEnabled,
			&i.SmsEnabled,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseBYOCPhoneNumber = `-- name: ReleaseBYOCPhoneNumber :one
UPDATE phone_numbers
SET
    status = 'released',
    updated_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND provisioning_mode = 'byoc'
  AND status IN ('active', 'disabled')
RETURNING id, organization_id, number, country_code, provisioning_mode, carrier_connection_id, provider_id, provider_resource_id, voice_enabled, sms_enabled, status, created_at, updated_at
`

type ReleaseBYOCPhoneNumberParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ReleaseBYOCPhoneNumber(ctx context.Context, arg ReleaseBYOCPhoneNumberParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, releaseBYOCPhoneNumber, arg.ID, arg.OrganizationID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseManagedPhoneNumber = `-- name: ReleaseManagedPhoneNumber :one
UPDATE phone_numbers
SET
    status = 'released',
    carrier_connection_id = NULL,
    voice_enabled = false,
    sms_enabled = false,
    updated_at = now()
WHERE id = $1
  AND provisioning_mode = 'managed'
  AND status IN ('active', 'disabled')
RETURNING id, organization_id, number, country_code, provisioning_mode, carrier_connection_id, provider_id, provider_resource_id, voice_enabled, sms_enabled, status, created_at, updated_at
`

func (q *Queries) ReleaseManagedPhoneNumber(ctx context.Context, id uuid.UUID) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, releaseManagedPhoneNumber, id)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setBYOCPhoneNumberCarrierConnection = `-- name: SetBYOCPhoneNumberCarrierConnection :one
UPDATE phone_numbers AS pn
SET
    carrier_connection_id = $1,
    updated_at = NOW()
FROM carrier_connections AS cc
WHERE pn.id = $2
  AND pn.organization_id = $3
  AND pn.provisioning_mode = 'byoc'
  AND pn.status = 'active'
  AND cc.id = $1
  AND cc.scope = 'organization'
  AND cc.organization_id = pn.organization_id
  AND cc.status = 'active'
RETURNING pn.id, pn.organization_id, pn.number, pn.country_code, pn.provisioning_mode, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.created_at, pn.updated_at
`

type SetBYOCPhoneNumberCarrierConnectionParams struct {
	CarrierConnectionID *uuid.UUID `db:"carrier_connection_id" json:"carrier_connection_id"`
	ID                  uuid.UUID  `db:"id" json:"id"`
	OrganizationID      uuid.UUID  `db:"organization_id" json:"organization_id"`
}

func (q *Queries) SetBYOCPhoneNumberCarrierConnection(ctx context.Context, arg SetBYOCPhoneNumberCarrierConnectionParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, setBYOCPhoneNumberCarrierConnection, arg.CarrierConnectionID, arg.ID, arg.OrganizationID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setManagedPhoneNumberCarrierConnection = `-- name: SetManagedPhoneNumberCarrierConnection :one
UPDATE phone_numbers AS pn
SET
    carrier_connection_id = $1,
    updated_at = NOW()
FROM carrier_connections AS cc
WHERE pn.id = $2
  AND pn.organization_id = $3
  AND pn.provisioning_mode = 'managed'
  AND pn.status = 'active'
  AND pn.provider_id IS NOT NULL
  AND cc.id = $1
  AND cc.scope = 'platform'
  AND cc.organization_id IS NULL
  AND cc.provider_id = pn.provider_id
  AND cc.status = 'active'
RETURNING pn.id, pn.organization_id, pn.number, pn.country_code, pn.provisioning_mode, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.created_at, pn.updated_at
`

type SetManagedPhoneNumberCarrierConnectionParams struct {
	CarrierConnectionID *uuid.UUID `db:"carrier_connection_id" json:"carrier_connection_id"`
	ID                  uuid.UUID  `db:"id" json:"id"`
	OrganizationID      uuid.UUID  `db:"organization_id" json:"organization_id"`
}

func (q *Queries) SetManagedPhoneNumberCarrierConnection(ctx context.Context, arg SetManagedPhoneNumberCarrierConnectionParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, setManagedPhoneNumberCarrierConnection, arg.CarrierConnectionID, arg.ID, arg.OrganizationID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePhoneNumber = `-- name: UpdatePhoneNumber :one
UPDATE phone_numbers AS pn
SET
    voice_enabled = COALESCE($1, pn.voice_enabled),
    sms_enabled = COALESCE($2, pn.sms_enabled),
    updated_at = NOW()
WHERE pn.id = $3
  AND pn.organization_id = $4
  AND pn.status = 'active'
RETURNING pn.id, pn.organization_id, pn.number, pn.country_code, pn.provisioning_mode, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.created_at, pn.updated_at
`

type UpdatePhoneNumberParams struct {
	VoiceEnabled   *bool     `db:"voice_enabled" json:"voice_enabled"`
	SmsEnabled     *bool     `db:"sms_enabled" json:"sms_enabled"`
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, updatePhoneNumber,
		arg.VoiceEnabled,
		arg.SmsEnabled,
		arg.ID,
		arg.OrganizationID,
	)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.ProvisioningMode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
