// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phone_numbers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCustomerPhoneNumber = `-- name: CreateCustomerPhoneNumber :one
INSERT INTO phone_numbers (
    organization_id,
    number,
    country_code,
    carrier_connection_id,
    provider_connection_id,
    provider_id,
    provider_resource_id,
    voice_enabled,
    sms_enabled
)
SELECT
    $1 AS organization_id,
    $2 AS number,
    $3 AS country_code,
    cc.id AS carrier_connection_id,
    NULL::UUID AS provider_connection_id,
    NULL::UUID AS provider_id,
    NULL::TEXT AS provider_resource_id,
    COALESCE($4, true) AS voice_enabled,
    COALESCE($5, false) AS sms_enabled
FROM organizations AS o
LEFT JOIN carrier_connections AS cc
  ON cc.id = $6::UUID
 AND cc.scope = 'organization'
 AND cc.organization_id = $1
 AND cc.status = 'active'
WHERE o.id = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
  AND (
      $6::UUID IS NULL
      OR cc.id IS NOT NULL
  )
RETURNING id, organization_id, number, country_code, carrier_connection_id, provider_id, provider_resource_id, voice_enabled, sms_enabled, status, error_code, error_message, created_at, updated_at
`

type CreateCustomerPhoneNumberParams struct {
	OrganizationID      uuid.UUID  `db:"organization_id" json:"organization_id"`
	Number              string     `db:"number" json:"number"`
	CountryCode         string     `db:"country_code" json:"country_code"`
	VoiceEnabled        *bool      `db:"voice_enabled" json:"voice_enabled"`
	SmsEnabled          *bool      `db:"sms_enabled" json:"sms_enabled"`
	CarrierConnectionID *uuid.UUID `db:"carrier_connection_id" json:"carrier_connection_id"`
}

func (q *Queries) CreateCustomerPhoneNumber(ctx context.Context, arg CreateCustomerPhoneNumberParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, createCustomerPhoneNumber,
		arg.OrganizationID,
		arg.Number,
		arg.CountryCode,
		arg.VoiceEnabled,
		arg.SmsEnabled,
		arg.CarrierConnectionID,
	)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProvisioningProviderPhoneNumber = `-- name: CreateProvisioningProviderPhoneNumber :one
INSERT INTO phone_numbers (
    organization_id,
    number,
    country_code,
    carrier_connection_id,
    provider_connection_id,
    provider_id,
    provider_resource_id,
    voice_enabled,
    sms_enabled,
    status
)
SELECT
    $1 AS organization_id,
    $2 AS number,
    $3 AS country_code,
    customer_cc.id AS carrier_connection_id,
    provider_cc.id AS provider_connection_id,
    cp.id AS provider_id,
    NULL::TEXT AS provider_resource_id,
    true AS voice_enabled,
    false AS sms_enabled,
    'provisioning' AS status
FROM organizations AS o
JOIN carrier_providers AS cp
  ON cp.id = $4
 AND cp.status = 'active'
JOIN carrier_connections AS provider_cc
  ON provider_cc.id = $5
 AND provider_cc.scope = 'platform'
 AND provider_cc.organization_id IS NULL
 AND provider_cc.provider_id = cp.id
 AND provider_cc.status = 'active'
LEFT JOIN carrier_connections AS customer_cc
  ON customer_cc.id = $6::UUID
 AND customer_cc.scope = 'organization'
 AND customer_cc.organization_id = $1
 AND customer_cc.status = 'active'
WHERE o.id = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
  AND (
      $6::UUID IS NULL
      OR customer_cc.id IS NOT NULL
  )
RETURNING id, organization_id, number, country_code, carrier_connection_id, provider_id, provider_resource_id, voice_enabled, sms_enabled, status, error_code, error_message, created_at, updated_at
`

type CreateProvisioningProviderPhoneNumberParams struct {
	OrganizationID       uuid.UUID  `db:"organization_id" json:"organization_id"`
	Number               string     `db:"number" json:"number"`
	CountryCode          string     `db:"country_code" json:"country_code"`
	ProviderID           uuid.UUID  `db:"provider_id" json:"provider_id"`
	ProviderConnectionID uuid.UUID  `db:"provider_connection_id" json:"provider_connection_id"`
	CarrierConnectionID  *uuid.UUID `db:"carrier_connection_id" json:"carrier_connection_id"`
}

func (q *Queries) CreateProvisioningProviderPhoneNumber(ctx context.Context, arg CreateProvisioningProviderPhoneNumberParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, createProvisioningProviderPhoneNumber,
		arg.OrganizationID,
		arg.Number,
		arg.CountryCode,
		arg.ProviderID,
		arg.ProviderConnectionID,
		arg.CarrierConnectionID,
	)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBackofficePhoneNumber = `-- name: GetBackofficePhoneNumber :one
SELECT
    pn.id::TEXT AS id,
    pn.organization_id::TEXT AS organization_id,
    o.name AS organization_name,
    pn.number,
    pn.country_code::TEXT AS country_code,
    CASE WHEN pn.provider_id IS NULL THEN 'customer' ELSE 'leamout' END::TEXT AS source,
    CAST(COALESCE(pn.carrier_connection_id::TEXT, '—') AS TEXT) AS carrier_connection_id,
    COALESCE(cc.name, '—') AS carrier_connection_name,
    CAST(COALESCE(pn.provider_connection_id::TEXT, '—') AS TEXT) AS provider_connection_id,
    COALESCE(provider_cc.name, '—') AS provider_connection_name,
    CAST(COALESCE(pn.provider_id::TEXT, '—') AS TEXT) AS provider_id,
    COALESCE(cp.name, 'Customer') AS provider_name,
    COALESCE(pn.provider_resource_id, '—') AS provider_resource_id,
    pn.voice_enabled,
    pn.sms_enabled,
    pn.status,
    COALESCE(pn.error_code, '—') AS error_code,
    COALESCE(pn.error_message, '—') AS error_message,
    to_char(pn.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') AS created_at,
    to_char(pn.updated_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') AS updated_at
FROM phone_numbers AS pn
JOIN organizations AS o ON o.id = pn.organization_id
LEFT JOIN carrier_connections AS cc ON cc.id = pn.carrier_connection_id
LEFT JOIN carrier_connections AS provider_cc ON provider_cc.id = pn.provider_connection_id
LEFT JOIN carrier_providers AS cp ON cp.id = pn.provider_id
WHERE pn.id = $1
LIMIT 1
`

type GetBackofficePhoneNumberRow struct {
	ID                     string `db:"id" json:"id"`
	OrganizationID         string `db:"organization_id" json:"organization_id"`
	OrganizationName       string `db:"organization_name" json:"organization_name"`
	Number                 string `db:"number" json:"number"`
	CountryCode            string `db:"country_code" json:"country_code"`
	Source                 string `db:"source" json:"source"`
	CarrierConnectionID    string `db:"carrier_connection_id" json:"carrier_connection_id"`
	CarrierConnectionName  string `db:"carrier_connection_name" json:"carrier_connection_name"`
	ProviderConnectionID   string `db:"provider_connection_id" json:"provider_connection_id"`
	ProviderConnectionName string `db:"provider_connection_name" json:"provider_connection_name"`
	ProviderID             string `db:"provider_id" json:"provider_id"`
	ProviderName           string `db:"provider_name" json:"provider_name"`
	ProviderResourceID     string `db:"provider_resource_id" json:"provider_resource_id"`
	VoiceEnabled           bool   `db:"voice_enabled" json:"voice_enabled"`
	SmsEnabled             bool   `db:"sms_enabled" json:"sms_enabled"`
	Status                 string `db:"status" json:"status"`
	ErrorCode              string `db:"error_code" json:"error_code"`
	ErrorMessage           string `db:"error_message" json:"error_message"`
	CreatedAt              string `db:"created_at" json:"created_at"`
	UpdatedAt              string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetBackofficePhoneNumber(ctx context.Context, id uuid.UUID) (GetBackofficePhoneNumberRow, error) {
	row := q.db.QueryRow(ctx, getBackofficePhoneNumber, id)
	var i GetBackofficePhoneNumberRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrganizationName,
		&i.Number,
		&i.CountryCode,
		&i.Source,
		&i.CarrierConnectionID,
		&i.CarrierConnectionName,
		&i.ProviderConnectionID,
		&i.ProviderConnectionName,
		&i.ProviderID,
		&i.ProviderName,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhoneNumberByID = `-- name: GetPhoneNumberByID :one
SELECT pn.id, pn.organization_id, pn.number, pn.country_code, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.error_code, pn.error_message, pn.created_at, pn.updated_at
FROM phone_numbers AS pn
JOIN organizations AS o ON o.id = pn.organization_id
WHERE pn.id = $1
  AND pn.organization_id = $2
  AND pn.status <> 'released'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetPhoneNumberByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetPhoneNumberByID(ctx context.Context, arg GetPhoneNumberByIDParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, getPhoneNumberByID, arg.ID, arg.OrganizationID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhoneNumberByNumber = `-- name: GetPhoneNumberByNumber :one
SELECT pn.id, pn.organization_id, pn.number, pn.country_code, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.error_code, pn.error_message, pn.created_at, pn.updated_at
FROM phone_numbers AS pn
JOIN organizations AS o ON o.id = pn.organization_id
WHERE pn.number = $1
  AND pn.organization_id = $2
  AND pn.status = 'active'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetPhoneNumberByNumberParams struct {
	Number         string    `db:"number" json:"number"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetPhoneNumberByNumber(ctx context.Context, arg GetPhoneNumberByNumberParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, getPhoneNumberByNumber, arg.Number, arg.OrganizationID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhoneNumberForRelease = `-- name: GetPhoneNumberForRelease :one
SELECT pn.id, pn.organization_id, pn.number, pn.country_code, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.error_code, pn.error_message, pn.created_at, pn.updated_at
FROM phone_numbers AS pn
JOIN organizations AS o ON o.id = pn.organization_id
WHERE pn.id = $1
  AND pn.organization_id = $2
  AND pn.status IN ('active', 'disabled')
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetPhoneNumberForReleaseParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetPhoneNumberForRelease(ctx context.Context, arg GetPhoneNumberForReleaseParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, getPhoneNumberForRelease, arg.ID, arg.OrganizationID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoiceBindingByNumber = `-- name: GetVoiceBindingByNumber :one
SELECT
    vb.id AS binding_id,
    vb.voice_application_id,
    va.name AS application_name,
    va.ring_timeout_seconds,
    va.caller_id AS application_caller_id,
    pn.id AS phone_number_id,
    pn.number,
    pn.organization_id
FROM phone_numbers AS pn
JOIN voice_bindings AS vb ON vb.phone_number_id = pn.id
JOIN voice_applications AS va ON va.id = vb.voice_application_id
JOIN organizations AS o ON o.id = pn.organization_id
WHERE pn.number = $1
  AND pn.status = 'active'
  AND pn.voice_enabled = true
  AND va.status = 'active'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetVoiceBindingByNumberRow struct {
	BindingID           uuid.UUID `db:"binding_id" json:"binding_id"`
	VoiceApplicationID  uuid.UUID `db:"voice_application_id" json:"voice_application_id"`
	ApplicationName     string    `db:"application_name" json:"application_name"`
	RingTimeoutSeconds  int32     `db:"ring_timeout_seconds" json:"ring_timeout_seconds"`
	ApplicationCallerID *string   `db:"application_caller_id" json:"application_caller_id"`
	PhoneNumberID       uuid.UUID `db:"phone_number_id" json:"phone_number_id"`
	Number              string    `db:"number" json:"number"`
	OrganizationID      uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetVoiceBindingByNumber(ctx context.Context, number string) (GetVoiceBindingByNumberRow, error) {
	row := q.db.QueryRow(ctx, getVoiceBindingByNumber, number)
	var i GetVoiceBindingByNumberRow
	err := row.Scan(
		&i.BindingID,
		&i.VoiceApplicationID,
		&i.ApplicationName,
		&i.RingTimeoutSeconds,
		&i.ApplicationCallerID,
		&i.PhoneNumberID,
		&i.Number,
		&i.OrganizationID,
	)
	return i, err
}

const listBackofficePhoneNumbers = `-- name: ListBackofficePhoneNumbers :many
SELECT
    pn.id::TEXT AS id,
    pn.organization_id::TEXT AS organization_id,
    o.name AS organization_name,
    pn.number,
    pn.country_code::TEXT AS country_code,
    CASE WHEN pn.provider_id IS NULL THEN 'customer' ELSE 'leamout' END::TEXT AS source,
    COALESCE(cp.name, 'Customer') AS provider_name,
    pn.voice_enabled,
    pn.sms_enabled,
    pn.status,
    to_char(pn.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') AS created_at
FROM phone_numbers AS pn
JOIN organizations AS o ON o.id = pn.organization_id
LEFT JOIN carrier_providers AS cp ON cp.id = pn.provider_id
ORDER BY pn.created_at DESC
LIMIT 100
`

type ListBackofficePhoneNumbersRow struct {
	ID               string `db:"id" json:"id"`
	OrganizationID   string `db:"organization_id" json:"organization_id"`
	OrganizationName string `db:"organization_name" json:"organization_name"`
	Number           string `db:"number" json:"number"`
	CountryCode      string `db:"country_code" json:"country_code"`
	Source           string `db:"source" json:"source"`
	ProviderName     string `db:"provider_name" json:"provider_name"`
	VoiceEnabled     bool   `db:"voice_enabled" json:"voice_enabled"`
	SmsEnabled       bool   `db:"sms_enabled" json:"sms_enabled"`
	Status           string `db:"status" json:"status"`
	CreatedAt        string `db:"created_at" json:"created_at"`
}

func (q *Queries) ListBackofficePhoneNumbers(ctx context.Context) ([]ListBackofficePhoneNumbersRow, error) {
	rows, err := q.db.Query(ctx, listBackofficePhoneNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackofficePhoneNumbersRow{}
	for rows.Next() {
		var i ListBackofficePhoneNumbersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.Number,
			&i.CountryCode,
			&i.Source,
			&i.ProviderName,
			&i.VoiceEnabled,
			&i.SmsEnabled,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhoneNumbersByCountry = `-- name: ListPhoneNumbersByCountry :many
SELECT pn.id, pn.organization_id, pn.number, pn.country_code, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.error_code, pn.error_message, pn.created_at, pn.updated_at
FROM phone_numbers AS pn
WHERE pn.organization_id = $1
  AND pn.country_code = $2
  AND pn.status <> 'released'
ORDER BY pn.number ASC
`

type ListPhoneNumbersByCountryParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	CountryCode    string    `db:"country_code" json:"country_code"`
}

func (q *Queries) ListPhoneNumbersByCountry(ctx context.Context, arg ListPhoneNumbersByCountryParams) ([]PhoneNumber, error) {
	rows, err := q.db.Query(ctx, listPhoneNumbersByCountry, arg.OrganizationID, arg.CountryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhoneNumber{}
	for rows.Next() {
		var i PhoneNumber
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Number,
			&i.CountryCode,
			&i.CarrierConnectionID,
			&i.ProviderID,
			&i.ProviderResourceID,
			&i.VoiceEnabled,
			&i.SmsEnabled,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhoneNumbersByOrganizationID = `-- name: ListPhoneNumbersByOrganizationID :many
SELECT pn.id, pn.organization_id, pn.number, pn.country_code, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.error_code, pn.error_message, pn.created_at, pn.updated_at
FROM phone_numbers AS pn
WHERE pn.organization_id = $1
  AND pn.status <> 'released'
ORDER BY pn.created_at DESC
`

func (q *Queries) ListPhoneNumbersByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]PhoneNumber, error) {
	rows, err := q.db.Query(ctx, listPhoneNumbersByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhoneNumber{}
	for rows.Next() {
		var i PhoneNumber
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Number,
			&i.CountryCode,
			&i.CarrierConnectionID,
			&i.ProviderID,
			&i.ProviderResourceID,
			&i.VoiceEnabled,
			&i.SmsEnabled,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProviderPhoneNumberForOperation = `-- name: LockProviderPhoneNumberForOperation :one
SELECT id, organization_id, number, country_code, carrier_connection_id, provider_id, provider_resource_id, voice_enabled, sms_enabled, status, error_code, error_message, created_at, updated_at
FROM phone_numbers
WHERE id = $1
  AND organization_id = $2
  AND provider_id = $3
  AND number = $4
  AND country_code = $5
FOR UPDATE
`

type LockProviderPhoneNumberForOperationParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	OrganizationID uuid.UUID  `db:"organization_id" json:"organization_id"`
	ProviderID     *uuid.UUID `db:"provider_id" json:"provider_id"`
	Number         string     `db:"number" json:"number"`
	CountryCode    string     `db:"country_code" json:"country_code"`
}

func (q *Queries) LockProviderPhoneNumberForOperation(ctx context.Context, arg LockProviderPhoneNumberForOperationParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, lockProviderPhoneNumberForOperation,
		arg.ID,
		arg.OrganizationID,
		arg.ProviderID,
		arg.Number,
		arg.CountryCode,
	)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markProviderPhoneNumberActive = `-- name: MarkProviderPhoneNumberActive :one
UPDATE phone_numbers
SET
    provider_resource_id = $1,
    status = 'active',
    error_code = NULL,
    error_message = NULL
WHERE id = $2
  AND organization_id = $3
  AND provider_id = $4
  AND status = 'provisioning'
RETURNING id, organization_id, number, country_code, carrier_connection_id, provider_id, provider_resource_id, voice_enabled, sms_enabled, status, error_code, error_message, created_at, updated_at
`

type MarkProviderPhoneNumberActiveParams struct {
	ProviderResourceID *string    `db:"provider_resource_id" json:"provider_resource_id"`
	ID                 uuid.UUID  `db:"id" json:"id"`
	OrganizationID     uuid.UUID  `db:"organization_id" json:"organization_id"`
	ProviderID         *uuid.UUID `db:"provider_id" json:"provider_id"`
}

func (q *Queries) MarkProviderPhoneNumberActive(ctx context.Context, arg MarkProviderPhoneNumberActiveParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, markProviderPhoneNumberActive,
		arg.ProviderResourceID,
		arg.ID,
		arg.OrganizationID,
		arg.ProviderID,
	)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markProviderPhoneNumberFailed = `-- name: MarkProviderPhoneNumberFailed :exec
UPDATE phone_numbers
SET
    status = 'failed',
    voice_enabled = false,
    sms_enabled = false,
    error_code = 'provider_provision_failed',
    error_message = $1
WHERE id = $2
  AND organization_id = $3
  AND provider_id = $4
  AND status = 'provisioning'
`

type MarkProviderPhoneNumberFailedParams struct {
	ErrorMessage   *string    `db:"error_message" json:"error_message"`
	ID             uuid.UUID  `db:"id" json:"id"`
	OrganizationID uuid.UUID  `db:"organization_id" json:"organization_id"`
	ProviderID     *uuid.UUID `db:"provider_id" json:"provider_id"`
}

func (q *Queries) MarkProviderPhoneNumberFailed(ctx context.Context, arg MarkProviderPhoneNumberFailedParams) error {
	_, err := q.db.Exec(ctx, markProviderPhoneNumberFailed,
		arg.ErrorMessage,
		arg.ID,
		arg.OrganizationID,
		arg.ProviderID,
	)
	return err
}

const releaseCustomerPhoneNumber = `-- name: ReleaseCustomerPhoneNumber :one
UPDATE phone_numbers
SET
    status = 'released',
    updated_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND provider_id IS NULL
  AND status IN ('active', 'disabled')
RETURNING id, organization_id, number, country_code, carrier_connection_id, provider_id, provider_resource_id, voice_enabled, sms_enabled, status, error_code, error_message, created_at, updated_at
`

type ReleaseCustomerPhoneNumberParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ReleaseCustomerPhoneNumber(ctx context.Context, arg ReleaseCustomerPhoneNumberParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, releaseCustomerPhoneNumber, arg.ID, arg.OrganizationID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPhoneNumberCarrierConnection = `-- name: SetPhoneNumberCarrierConnection :one
UPDATE phone_numbers AS pn
SET
    carrier_connection_id = $1,
    updated_at = NOW()
FROM carrier_connections AS cc
WHERE pn.id = $2
  AND pn.organization_id = $3
  AND pn.status = 'active'
  AND cc.id = $1
  AND cc.scope = 'organization'
  AND cc.organization_id = pn.organization_id
  AND cc.status = 'active'
RETURNING pn.id, pn.organization_id, pn.number, pn.country_code, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.error_code, pn.error_message, pn.created_at, pn.updated_at
`

type SetPhoneNumberCarrierConnectionParams struct {
	CarrierConnectionID *uuid.UUID `db:"carrier_connection_id" json:"carrier_connection_id"`
	ID                  uuid.UUID  `db:"id" json:"id"`
	OrganizationID      uuid.UUID  `db:"organization_id" json:"organization_id"`
}

func (q *Queries) SetPhoneNumberCarrierConnection(ctx context.Context, arg SetPhoneNumberCarrierConnectionParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, setPhoneNumberCarrierConnection, arg.CarrierConnectionID, arg.ID, arg.OrganizationID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePhoneNumber = `-- name: UpdatePhoneNumber :one
UPDATE phone_numbers AS pn
SET
    voice_enabled = COALESCE($1, pn.voice_enabled),
    sms_enabled = COALESCE($2, pn.sms_enabled),
    updated_at = NOW()
WHERE pn.id = $3
  AND pn.organization_id = $4
  AND pn.status = 'active'
RETURNING pn.id, pn.organization_id, pn.number, pn.country_code, pn.carrier_connection_id, pn.provider_id, pn.provider_resource_id, pn.voice_enabled, pn.sms_enabled, pn.status, pn.error_code, pn.error_message, pn.created_at, pn.updated_at
`

type UpdatePhoneNumberParams struct {
	VoiceEnabled   *bool     `db:"voice_enabled" json:"voice_enabled"`
	SmsEnabled     *bool     `db:"sms_enabled" json:"sms_enabled"`
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, updatePhoneNumber,
		arg.VoiceEnabled,
		arg.SmsEnabled,
		arg.ID,
		arg.OrganizationID,
	)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Number,
		&i.CountryCode,
		&i.CarrierConnectionID,
		&i.ProviderID,
		&i.ProviderResourceID,
		&i.VoiceEnabled,
		&i.SmsEnabled,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
