// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    product_id,
    code,
    name,
    description,
    active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, true)
)
RETURNING id, product_id, code, name, description, active, created_at, updated_at
`

type CreatePlanParams struct {
	ProductID   uuid.UUID   `db:"product_id" json:"product_id"`
	Code        string      `db:"code" json:"code"`
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	Active      interface{} `db:"active" json:"active"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.ProductID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Active,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByCode = `-- name: GetPlanByCode :one
SELECT id, product_id, code, name, description, active, created_at, updated_at
FROM plans
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetPlanByCode(ctx context.Context, code string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByCode, code)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, product_id, code, name, description, active, created_at, updated_at
FROM plans
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePlansByProduct = `-- name: ListActivePlansByProduct :many
SELECT id, product_id, code, name, description, active, created_at, updated_at
FROM plans
WHERE product_id = $1
  AND active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActivePlansByProduct(ctx context.Context, productID uuid.UUID) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listActivePlansByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByProduct = `-- name: ListPlansByProduct :many
SELECT id, product_id, code, name, description, active, created_at, updated_at
FROM plans
WHERE product_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPlansByProduct(ctx context.Context, productID uuid.UUID) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET
    code = COALESCE($1, code),
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    active = COALESCE($4, active),
    updated_at = NOW()
WHERE id = $5
RETURNING id, product_id, code, name, description, active, created_at, updated_at
`

type UpdatePlanParams struct {
	Code        *string   `db:"code" json:"code"`
	Name        *string   `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
	Active      *bool     `db:"active" json:"active"`
	ID          uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Active,
		arg.ID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
