// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_cdrs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWholesaleCharge = `-- name: CreateWholesaleCharge :one
INSERT INTO wholesale_charges (
    provider_cdr_id,
    organization_id,
    call_id,
    amount_micros,
    currency,
    occurred_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, provider_cdr_id, organization_id, call_id, amount_micros, currency, occurred_at, created_at
`

type CreateWholesaleChargeParams struct {
	ProviderCdrID  uuid.UUID          `db:"provider_cdr_id" json:"provider_cdr_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	CallID         uuid.UUID          `db:"call_id" json:"call_id"`
	AmountMicros   int64              `db:"amount_micros" json:"amount_micros"`
	Currency       string             `db:"currency" json:"currency"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) CreateWholesaleCharge(ctx context.Context, arg CreateWholesaleChargeParams) (WholesaleCharge, error) {
	row := q.db.QueryRow(ctx, createWholesaleCharge,
		arg.ProviderCdrID,
		arg.OrganizationID,
		arg.CallID,
		arg.AmountMicros,
		arg.Currency,
		arg.OccurredAt,
	)
	var i WholesaleCharge
	err := row.Scan(
		&i.ID,
		&i.ProviderCdrID,
		&i.OrganizationID,
		&i.CallID,
		&i.AmountMicros,
		&i.Currency,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const findManagedCallForProviderCDR = `-- name: FindManagedCallForProviderCDR :one
SELECT
    c.id,
    c.organization_id
FROM calls AS c
JOIN carrier_connections AS cc
  ON cc.id = c.carrier_connection_id
WHERE c.sip_call_id = $1
  AND c.direction = 'outbound'
  AND c.carrier_connection_id = $2
  AND cc.scope = 'platform'
  AND cc.provider_id = $3
LIMIT 1
`

type FindManagedCallForProviderCDRParams struct {
	SipCallID           *string    `db:"sip_call_id" json:"sip_call_id"`
	CarrierConnectionID *uuid.UUID `db:"carrier_connection_id" json:"carrier_connection_id"`
	CarrierProviderID   uuid.UUID  `db:"carrier_provider_id" json:"carrier_provider_id"`
}

type FindManagedCallForProviderCDRRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) FindManagedCallForProviderCDR(ctx context.Context, arg FindManagedCallForProviderCDRParams) (FindManagedCallForProviderCDRRow, error) {
	row := q.db.QueryRow(ctx, findManagedCallForProviderCDR, arg.SipCallID, arg.CarrierConnectionID, arg.CarrierProviderID)
	var i FindManagedCallForProviderCDRRow
	err := row.Scan(&i.ID, &i.OrganizationID)
	return i, err
}

const getProviderCDRForUpdate = `-- name: GetProviderCDRForUpdate :one
SELECT id, carrier_provider_id, carrier_connection_id, provider_record_id, direction, sip_call_id, call_id, organization_id, reconciled_at, started_at, duration_seconds, currency, cost_micros, raw, created_at
FROM provider_cdrs
WHERE carrier_provider_id = $1
  AND direction = $2
  AND provider_record_id = $3
FOR UPDATE
`

type GetProviderCDRForUpdateParams struct {
	CarrierProviderID uuid.UUID `db:"carrier_provider_id" json:"carrier_provider_id"`
	Direction         string    `db:"direction" json:"direction"`
	ProviderRecordID  string    `db:"provider_record_id" json:"provider_record_id"`
}

func (q *Queries) GetProviderCDRForUpdate(ctx context.Context, arg GetProviderCDRForUpdateParams) (ProviderCdr, error) {
	row := q.db.QueryRow(ctx, getProviderCDRForUpdate, arg.CarrierProviderID, arg.Direction, arg.ProviderRecordID)
	var i ProviderCdr
	err := row.Scan(
		&i.ID,
		&i.CarrierProviderID,
		&i.CarrierConnectionID,
		&i.ProviderRecordID,
		&i.Direction,
		&i.SipCallID,
		&i.CallID,
		&i.OrganizationID,
		&i.ReconciledAt,
		&i.StartedAt,
		&i.DurationSeconds,
		&i.Currency,
		&i.CostMicros,
		&i.Raw,
		&i.CreatedAt,
	)
	return i, err
}

const insertProviderCDR = `-- name: InsertProviderCDR :one
INSERT INTO provider_cdrs (
    carrier_provider_id,
    carrier_connection_id,
    provider_record_id,
    direction,
    sip_call_id,
    started_at,
    duration_seconds,
    currency,
    cost_micros,
    raw
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (carrier_provider_id, direction, provider_record_id)
DO NOTHING
RETURNING id, carrier_provider_id, carrier_connection_id, provider_record_id, direction, sip_call_id, call_id, organization_id, reconciled_at, started_at, duration_seconds, currency, cost_micros, raw, created_at
`

type InsertProviderCDRParams struct {
	CarrierProviderID   uuid.UUID          `db:"carrier_provider_id" json:"carrier_provider_id"`
	CarrierConnectionID uuid.UUID          `db:"carrier_connection_id" json:"carrier_connection_id"`
	ProviderRecordID    string             `db:"provider_record_id" json:"provider_record_id"`
	Direction           string             `db:"direction" json:"direction"`
	SipCallID           *string            `db:"sip_call_id" json:"sip_call_id"`
	StartedAt           pgtype.Timestamptz `db:"started_at" json:"started_at"`
	DurationSeconds     int64              `db:"duration_seconds" json:"duration_seconds"`
	Currency            string             `db:"currency" json:"currency"`
	CostMicros          int64              `db:"cost_micros" json:"cost_micros"`
	Raw                 []byte             `db:"raw" json:"raw"`
}

func (q *Queries) InsertProviderCDR(ctx context.Context, arg InsertProviderCDRParams) (ProviderCdr, error) {
	row := q.db.QueryRow(ctx, insertProviderCDR,
		arg.CarrierProviderID,
		arg.CarrierConnectionID,
		arg.ProviderRecordID,
		arg.Direction,
		arg.SipCallID,
		arg.StartedAt,
		arg.DurationSeconds,
		arg.Currency,
		arg.CostMicros,
		arg.Raw,
	)
	var i ProviderCdr
	err := row.Scan(
		&i.ID,
		&i.CarrierProviderID,
		&i.CarrierConnectionID,
		&i.ProviderRecordID,
		&i.Direction,
		&i.SipCallID,
		&i.CallID,
		&i.OrganizationID,
		&i.ReconciledAt,
		&i.StartedAt,
		&i.DurationSeconds,
		&i.Currency,
		&i.CostMicros,
		&i.Raw,
		&i.CreatedAt,
	)
	return i, err
}

const markProviderCDRReconciled = `-- name: MarkProviderCDRReconciled :one
UPDATE provider_cdrs
SET
    call_id = $1,
    organization_id = $2,
    reconciled_at = now()
WHERE id = $3
  AND reconciled_at IS NULL
RETURNING id, carrier_provider_id, carrier_connection_id, provider_record_id, direction, sip_call_id, call_id, organization_id, reconciled_at, started_at, duration_seconds, currency, cost_micros, raw, created_at
`

type MarkProviderCDRReconciledParams struct {
	CallID         *uuid.UUID `db:"call_id" json:"call_id"`
	OrganizationID *uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) MarkProviderCDRReconciled(ctx context.Context, arg MarkProviderCDRReconciledParams) (ProviderCdr, error) {
	row := q.db.QueryRow(ctx, markProviderCDRReconciled, arg.CallID, arg.OrganizationID, arg.ID)
	var i ProviderCdr
	err := row.Scan(
		&i.ID,
		&i.CarrierProviderID,
		&i.CarrierConnectionID,
		&i.ProviderRecordID,
		&i.Direction,
		&i.SipCallID,
		&i.CallID,
		&i.OrganizationID,
		&i.ReconciledAt,
		&i.StartedAt,
		&i.DurationSeconds,
		&i.Currency,
		&i.CostMicros,
		&i.Raw,
		&i.CreatedAt,
	)
	return i, err
}

const sumWholesaleChargesForDay = `-- name: SumWholesaleChargesForDay :one
SELECT COALESCE(SUM(amount_micros), 0)::BIGINT
FROM wholesale_charges
WHERE organization_id = $1
  AND occurred_at >= $2::TIMESTAMPTZ
  AND occurred_at < $2::TIMESTAMPTZ + interval '1 day'
`

type SumWholesaleChargesForDayParams struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	Day            pgtype.Timestamptz `db:"day" json:"day"`
}

func (q *Queries) SumWholesaleChargesForDay(ctx context.Context, arg SumWholesaleChargesForDayParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumWholesaleChargesForDay, arg.OrganizationID, arg.Day)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
