// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_cdr_polling.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceProviderCDRPollCursor = `-- name: AdvanceProviderCDRPollCursor :one
UPDATE provider_cdr_poll_cursors
SET
    window_date = $1,
    page = $2,
    attempt_count = 0,
    next_attempt_at = $3,
    last_error = NULL,
    last_success_at = now()
WHERE provider = $4
  AND direction = $5
RETURNING provider, direction, window_date, page, attempt_count, next_attempt_at, last_error, last_success_at, created_at, updated_at
`

type AdvanceProviderCDRPollCursorParams struct {
	WindowDate    pgtype.Date        `db:"window_date" json:"window_date"`
	Page          int32              `db:"page" json:"page"`
	NextAttemptAt pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	Provider      string             `db:"provider" json:"provider"`
	Direction     string             `db:"direction" json:"direction"`
}

func (q *Queries) AdvanceProviderCDRPollCursor(ctx context.Context, arg AdvanceProviderCDRPollCursorParams) (ProviderCdrPollCursor, error) {
	row := q.db.QueryRow(ctx, advanceProviderCDRPollCursor,
		arg.WindowDate,
		arg.Page,
		arg.NextAttemptAt,
		arg.Provider,
		arg.Direction,
	)
	var i ProviderCdrPollCursor
	err := row.Scan(
		&i.Provider,
		&i.Direction,
		&i.WindowDate,
		&i.Page,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimProviderCDRPages = `-- name: ClaimProviderCDRPages :many
WITH ready AS (
    SELECT id
    FROM provider_cdr_pages
    WHERE direction = 'termination'
      AND processed_at IS NULL
      AND next_process_at IS NOT NULL
      AND next_process_at <= now()
    ORDER BY received_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
UPDATE provider_cdr_pages AS p
SET next_process_at = now() + interval '5 minutes'
FROM ready
WHERE p.id = ready.id
RETURNING p.id, p.provider, p.direction, p.window_date, p.page, p.record_count, p.payload_sha256, p.raw, p.received_at, p.process_attempts, p.next_process_at, p.last_process_error, p.processed_at
`

func (q *Queries) ClaimProviderCDRPages(ctx context.Context, limitCount int32) ([]ProviderCdrPage, error) {
	rows, err := q.db.Query(ctx, claimProviderCDRPages, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderCdrPage{}
	for rows.Next() {
		var i ProviderCdrPage
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Direction,
			&i.WindowDate,
			&i.Page,
			&i.RecordCount,
			&i.PayloadSha256,
			&i.Raw,
			&i.ReceivedAt,
			&i.ProcessAttempts,
			&i.NextProcessAt,
			&i.LastProcessError,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureProviderCDRPollCursor = `-- name: EnsureProviderCDRPollCursor :one
INSERT INTO provider_cdr_poll_cursors (
    provider,
    direction,
    window_date,
    page,
    next_attempt_at
)
VALUES (
    $1,
    $2,
    $3,
    1,
    now()
)
ON CONFLICT (provider, direction)
DO UPDATE SET provider = EXCLUDED.provider
RETURNING provider, direction, window_date, page, attempt_count, next_attempt_at, last_error, last_success_at, created_at, updated_at
`

type EnsureProviderCDRPollCursorParams struct {
	Provider   string      `db:"provider" json:"provider"`
	Direction  string      `db:"direction" json:"direction"`
	WindowDate pgtype.Date `db:"window_date" json:"window_date"`
}

func (q *Queries) EnsureProviderCDRPollCursor(ctx context.Context, arg EnsureProviderCDRPollCursorParams) (ProviderCdrPollCursor, error) {
	row := q.db.QueryRow(ctx, ensureProviderCDRPollCursor, arg.Provider, arg.Direction, arg.WindowDate)
	var i ProviderCdrPollCursor
	err := row.Scan(
		&i.Provider,
		&i.Direction,
		&i.WindowDate,
		&i.Page,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failProviderCDRPollCursor = `-- name: FailProviderCDRPollCursor :one
UPDATE provider_cdr_poll_cursors
SET
    attempt_count = attempt_count + 1,
    next_attempt_at = $1,
    last_error = $2
WHERE provider = $3
  AND direction = $4
RETURNING provider, direction, window_date, page, attempt_count, next_attempt_at, last_error, last_success_at, created_at, updated_at
`

type FailProviderCDRPollCursorParams struct {
	NextAttemptAt pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastError     *string            `db:"last_error" json:"last_error"`
	Provider      string             `db:"provider" json:"provider"`
	Direction     string             `db:"direction" json:"direction"`
}

func (q *Queries) FailProviderCDRPollCursor(ctx context.Context, arg FailProviderCDRPollCursorParams) (ProviderCdrPollCursor, error) {
	row := q.db.QueryRow(ctx, failProviderCDRPollCursor,
		arg.NextAttemptAt,
		arg.LastError,
		arg.Provider,
		arg.Direction,
	)
	var i ProviderCdrPollCursor
	err := row.Scan(
		&i.Provider,
		&i.Direction,
		&i.WindowDate,
		&i.Page,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProviderCDRPage = `-- name: InsertProviderCDRPage :one
INSERT INTO provider_cdr_pages (
    provider,
    direction,
    window_date,
    page,
    record_count,
    payload_sha256,
    raw
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (provider, direction, window_date, page, payload_sha256)
DO UPDATE SET received_at = provider_cdr_pages.received_at
RETURNING id, provider, direction, window_date, page, record_count, payload_sha256, raw, received_at, process_attempts, next_process_at, last_process_error, processed_at
`

type InsertProviderCDRPageParams struct {
	Provider      string      `db:"provider" json:"provider"`
	Direction     string      `db:"direction" json:"direction"`
	WindowDate    pgtype.Date `db:"window_date" json:"window_date"`
	Page          int32       `db:"page" json:"page"`
	RecordCount   int32       `db:"record_count" json:"record_count"`
	PayloadSha256 string      `db:"payload_sha256" json:"payload_sha256"`
	Raw           []byte      `db:"raw" json:"raw"`
}

func (q *Queries) InsertProviderCDRPage(ctx context.Context, arg InsertProviderCDRPageParams) (ProviderCdrPage, error) {
	row := q.db.QueryRow(ctx, insertProviderCDRPage,
		arg.Provider,
		arg.Direction,
		arg.WindowDate,
		arg.Page,
		arg.RecordCount,
		arg.PayloadSha256,
		arg.Raw,
	)
	var i ProviderCdrPage
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Direction,
		&i.WindowDate,
		&i.Page,
		&i.RecordCount,
		&i.PayloadSha256,
		&i.Raw,
		&i.ReceivedAt,
		&i.ProcessAttempts,
		&i.NextProcessAt,
		&i.LastProcessError,
		&i.ProcessedAt,
	)
	return i, err
}

const markProviderCDRPageProcessed = `-- name: MarkProviderCDRPageProcessed :one
UPDATE provider_cdr_pages
SET
    processed_at = now(),
    next_process_at = NULL,
    last_process_error = NULL
WHERE id = $1
  AND processed_at IS NULL
RETURNING id, provider, direction, window_date, page, record_count, payload_sha256, raw, received_at, process_attempts, next_process_at, last_process_error, processed_at
`

func (q *Queries) MarkProviderCDRPageProcessed(ctx context.Context, id uuid.UUID) (ProviderCdrPage, error) {
	row := q.db.QueryRow(ctx, markProviderCDRPageProcessed, id)
	var i ProviderCdrPage
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Direction,
		&i.WindowDate,
		&i.Page,
		&i.RecordCount,
		&i.PayloadSha256,
		&i.Raw,
		&i.ReceivedAt,
		&i.ProcessAttempts,
		&i.NextProcessAt,
		&i.LastProcessError,
		&i.ProcessedAt,
	)
	return i, err
}

const recordProviderCDRPageProcessFailure = `-- name: RecordProviderCDRPageProcessFailure :one
UPDATE provider_cdr_pages
SET
    process_attempts = process_attempts + 1,
    next_process_at = $1,
    last_process_error = $2
WHERE id = $3
  AND processed_at IS NULL
RETURNING id, provider, direction, window_date, page, record_count, payload_sha256, raw, received_at, process_attempts, next_process_at, last_process_error, processed_at
`

type RecordProviderCDRPageProcessFailureParams struct {
	NextProcessAt    pgtype.Timestamptz `db:"next_process_at" json:"next_process_at"`
	LastProcessError *string            `db:"last_process_error" json:"last_process_error"`
	ID               uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) RecordProviderCDRPageProcessFailure(ctx context.Context, arg RecordProviderCDRPageProcessFailureParams) (ProviderCdrPage, error) {
	row := q.db.QueryRow(ctx, recordProviderCDRPageProcessFailure, arg.NextProcessAt, arg.LastProcessError, arg.ID)
	var i ProviderCdrPage
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Direction,
		&i.WindowDate,
		&i.Page,
		&i.RecordCount,
		&i.PayloadSha256,
		&i.Raw,
		&i.ReceivedAt,
		&i.ProcessAttempts,
		&i.NextProcessAt,
		&i.LastProcessError,
		&i.ProcessedAt,
	)
	return i, err
}
