// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRetentionPolicy = `-- name: DeleteRetentionPolicy :exec
DELETE FROM retention_policies
WHERE organization_id = $1
  AND resource = $2
`

type DeleteRetentionPolicyParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Resource       string    `db:"resource" json:"resource"`
}

func (q *Queries) DeleteRetentionPolicy(ctx context.Context, arg DeleteRetentionPolicyParams) error {
	_, err := q.db.Exec(ctx, deleteRetentionPolicy, arg.OrganizationID, arg.Resource)
	return err
}

const getRetentionPolicy = `-- name: GetRetentionPolicy :one
SELECT organization_id, resource, retention_days, enabled, created_at, updated_at
FROM retention_policies
WHERE organization_id = $1
  AND resource = $2
LIMIT 1
`

type GetRetentionPolicyParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Resource       string    `db:"resource" json:"resource"`
}

func (q *Queries) GetRetentionPolicy(ctx context.Context, arg GetRetentionPolicyParams) (RetentionPolicy, error) {
	row := q.db.QueryRow(ctx, getRetentionPolicy, arg.OrganizationID, arg.Resource)
	var i RetentionPolicy
	err := row.Scan(
		&i.OrganizationID,
		&i.Resource,
		&i.RetentionDays,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEffectiveRecordingRetention = `-- name: ListEffectiveRecordingRetention :many
WITH effective_plans AS (
    SELECT
        o.id AS organization_id,
        COALESCE(active_plan.limits, free_plan.limits) AS limits
    FROM organizations AS o
    LEFT JOIN subscriptions AS s
      ON s.organization_id = o.id
     AND s.status IN ('trialing', 'active')
    LEFT JOIN plans AS active_plan
      ON active_plan.id = s.plan_id
    CROSS JOIN plans AS free_plan
    WHERE free_plan.code = 'free'
      AND o.status = 'active'
      AND o.deleted_at IS NULL
)
SELECT
    ep.organization_id,
    CASE
        WHEN NULLIF(ep.limits ->> 'retention_days', '') IS NULL
            THEN rp.retention_days
        WHEN rp.enabled
            THEN LEAST(
                rp.retention_days,
                (ep.limits ->> 'retention_days')::INTEGER
            )
        ELSE (ep.limits ->> 'retention_days')::INTEGER
    END::INTEGER AS retention_days
FROM effective_plans AS ep
LEFT JOIN retention_policies AS rp
  ON rp.organization_id = ep.organization_id
 AND rp.resource = 'recordings'
WHERE NULLIF(ep.limits ->> 'retention_days', '') IS NOT NULL
   OR (rp.enabled AND rp.retention_days IS NOT NULL)
ORDER BY ep.organization_id
`

type ListEffectiveRecordingRetentionRow struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	RetentionDays  int32     `db:"retention_days" json:"retention_days"`
}

func (q *Queries) ListEffectiveRecordingRetention(ctx context.Context) ([]ListEffectiveRecordingRetentionRow, error) {
	rows, err := q.db.Query(ctx, listEffectiveRecordingRetention)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEffectiveRecordingRetentionRow{}
	for rows.Next() {
		var i ListEffectiveRecordingRetentionRow
		if err := rows.Scan(&i.OrganizationID, &i.RetentionDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledRetentionPolicies = `-- name: ListEnabledRetentionPolicies :many
SELECT organization_id, resource, retention_days, enabled, created_at, updated_at
FROM retention_policies
WHERE enabled
ORDER BY organization_id, resource
`

func (q *Queries) ListEnabledRetentionPolicies(ctx context.Context) ([]RetentionPolicy, error) {
	rows, err := q.db.Query(ctx, listEnabledRetentionPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetentionPolicy{}
	for rows.Next() {
		var i RetentionPolicy
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Resource,
			&i.RetentionDays,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredRecordingsForRetention = `-- name: ListExpiredRecordingsForRetention :many
SELECT id
FROM recordings
WHERE organization_id = $1
  AND status = 'completed'
  AND created_at < $2
ORDER BY created_at
LIMIT $3
`

type ListExpiredRecordingsForRetentionParams struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	CreatedBefore  pgtype.Timestamptz `db:"created_before" json:"created_before"`
	BatchSize      int32              `db:"batch_size" json:"batch_size"`
}

func (q *Queries) ListExpiredRecordingsForRetention(ctx context.Context, arg ListExpiredRecordingsForRetentionParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredRecordingsForRetention, arg.OrganizationID, arg.CreatedBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetentionPolicies = `-- name: ListRetentionPolicies :many
SELECT organization_id, resource, retention_days, enabled, created_at, updated_at
FROM retention_policies
WHERE organization_id = $1
ORDER BY resource
`

func (q *Queries) ListRetentionPolicies(ctx context.Context, organizationID uuid.UUID) ([]RetentionPolicy, error) {
	rows, err := q.db.Query(ctx, listRetentionPolicies, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetentionPolicy{}
	for rows.Next() {
		var i RetentionPolicy
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Resource,
			&i.RetentionDays,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRetentionPolicy = `-- name: UpsertRetentionPolicy :one
INSERT INTO retention_policies (
    organization_id,
    resource,
    retention_days,
    enabled
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (organization_id, resource)
DO UPDATE SET
    retention_days = EXCLUDED.retention_days,
    enabled = EXCLUDED.enabled
RETURNING organization_id, resource, retention_days, enabled, created_at, updated_at
`

type UpsertRetentionPolicyParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Resource       string    `db:"resource" json:"resource"`
	RetentionDays  int32     `db:"retention_days" json:"retention_days"`
	Enabled        bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) UpsertRetentionPolicy(ctx context.Context, arg UpsertRetentionPolicyParams) (RetentionPolicy, error) {
	row := q.db.QueryRow(ctx, upsertRetentionPolicy,
		arg.OrganizationID,
		arg.Resource,
		arg.RetentionDays,
		arg.Enabled,
	)
	var i RetentionPolicy
	err := row.Scan(
		&i.OrganizationID,
		&i.Resource,
		&i.RetentionDays,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
