// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_attachments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const resolveManagedInboundRuntimeAttachment = `-- name: ResolveManagedInboundRuntimeAttachment :one
WITH candidates AS (
    SELECT
        ra.id AS runtime_attachment_id,
        d.id AS deployment_id,
        d.deployment_id AS deployment_identity,
        ra.ingress_host,
        ra.ingress_port,
        ra.transport
    FROM runtime_attachments AS ra
    JOIN deployments AS d ON d.id = ra.deployment_id
    JOIN licenses AS l ON l.id = d.license_id
    JOIN organizations AS o ON o.id = l.organization_id
    WHERE l.organization_id = $1
      AND o.status = 'active'
      AND o.deleted_at IS NULL
      AND l.status = 'active'
      AND d.status = 'active'
      AND ra.verification_status = 'verified'
      AND ra.health_status = 'healthy'
)
SELECT runtime_attachment_id, deployment_id, deployment_identity, ingress_host, ingress_port, transport
FROM candidates
WHERE (SELECT count(*) FROM candidates) = 1
LIMIT 1
`

type ResolveManagedInboundRuntimeAttachmentRow struct {
	RuntimeAttachmentID uuid.UUID `db:"runtime_attachment_id" json:"runtime_attachment_id"`
	DeploymentID        uuid.UUID `db:"deployment_id" json:"deployment_id"`
	DeploymentIdentity  string    `db:"deployment_identity" json:"deployment_identity"`
	IngressHost         string    `db:"ingress_host" json:"ingress_host"`
	IngressPort         int32     `db:"ingress_port" json:"ingress_port"`
	Transport           string    `db:"transport" json:"transport"`
}

func (q *Queries) ResolveManagedInboundRuntimeAttachment(ctx context.Context, organizationID uuid.UUID) (ResolveManagedInboundRuntimeAttachmentRow, error) {
	row := q.db.QueryRow(ctx, resolveManagedInboundRuntimeAttachment, organizationID)
	var i ResolveManagedInboundRuntimeAttachmentRow
	err := row.Scan(
		&i.RuntimeAttachmentID,
		&i.DeploymentID,
		&i.DeploymentIdentity,
		&i.IngressHost,
		&i.IngressPort,
		&i.Transport,
	)
	return i, err
}

const setRuntimeAttachmentState = `-- name: SetRuntimeAttachmentState :one
UPDATE runtime_attachments
SET
    verification_status = $1,
    health_status = $2,
    verified_at = CASE
        WHEN $1::TEXT = 'verified' THEN COALESCE(verified_at, NOW())
        ELSE NULL
    END,
    last_checked_at = NOW(),
    updated_at = NOW()
WHERE id = $3
RETURNING id, deployment_id, ingress_host, ingress_port, transport, verification_status, health_status, verified_at, last_checked_at, created_at, updated_at
`

type SetRuntimeAttachmentStateParams struct {
	VerificationStatus string    `db:"verification_status" json:"verification_status"`
	HealthStatus       string    `db:"health_status" json:"health_status"`
	ID                 uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) SetRuntimeAttachmentState(ctx context.Context, arg SetRuntimeAttachmentStateParams) (RuntimeAttachment, error) {
	row := q.db.QueryRow(ctx, setRuntimeAttachmentState, arg.VerificationStatus, arg.HealthStatus, arg.ID)
	var i RuntimeAttachment
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.IngressHost,
		&i.IngressPort,
		&i.Transport,
		&i.VerificationStatus,
		&i.HealthStatus,
		&i.VerifiedAt,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRuntimeAttachment = `-- name: UpsertRuntimeAttachment :one
INSERT INTO runtime_attachments (
    deployment_id,
    ingress_host,
    ingress_port,
    transport
)
SELECT
    d.id,
    $1,
    $2,
    $3
FROM deployments AS d
JOIN licenses AS l ON l.id = d.license_id
WHERE d.id = $4
  AND d.status = 'active'
  AND l.status = 'active'
ON CONFLICT (deployment_id) DO UPDATE SET
    ingress_host = EXCLUDED.ingress_host,
    ingress_port = EXCLUDED.ingress_port,
    transport = EXCLUDED.transport,
    verification_status = 'pending',
    health_status = 'unknown',
    verified_at = NULL,
    last_checked_at = NULL,
    updated_at = NOW()
RETURNING id, deployment_id, ingress_host, ingress_port, transport, verification_status, health_status, verified_at, last_checked_at, created_at, updated_at
`

type UpsertRuntimeAttachmentParams struct {
	IngressHost  string    `db:"ingress_host" json:"ingress_host"`
	IngressPort  int32     `db:"ingress_port" json:"ingress_port"`
	Transport    string    `db:"transport" json:"transport"`
	DeploymentID uuid.UUID `db:"deployment_id" json:"deployment_id"`
}

func (q *Queries) UpsertRuntimeAttachment(ctx context.Context, arg UpsertRuntimeAttachmentParams) (RuntimeAttachment, error) {
	row := q.db.QueryRow(ctx, upsertRuntimeAttachment,
		arg.IngressHost,
		arg.IngressPort,
		arg.Transport,
		arg.DeploymentID,
	)
	var i RuntimeAttachment
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.IngressHost,
		&i.IngressPort,
		&i.Transport,
		&i.VerificationStatus,
		&i.HealthStatus,
		&i.VerifiedAt,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
