// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEffectiveOrganizationEntitlement = `-- name: GetEffectiveOrganizationEntitlement :one
SELECT
    COALESCE(oe.enabled, pe.enabled, FALSE)::boolean AS enabled
FROM organizations o
LEFT JOIN entitlements oe
  ON oe.organization_id = o.id
 AND oe.capability = $1
LEFT JOIN subscriptions s
  ON s.organization_id = o.id
 AND s.status IN ('trialing', 'active')
LEFT JOIN subscription_plan_entitlements pe
  ON pe.plan_id = s.plan_id
 AND pe.capability = $1
WHERE o.id = $2
LIMIT 1
`

type GetEffectiveOrganizationEntitlementParams struct {
	Capability     string    `db:"capability" json:"capability"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetEffectiveOrganizationEntitlement(ctx context.Context, arg GetEffectiveOrganizationEntitlementParams) (bool, error) {
	row := q.db.QueryRow(ctx, getEffectiveOrganizationEntitlement, arg.Capability, arg.OrganizationID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const getOrganizationSubscription = `-- name: GetOrganizationSubscription :one
SELECT id, organization_id, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancel_at_period_end, canceled_at, created_at, updated_at
FROM subscriptions
WHERE organization_id = $1
LIMIT 1
`

func (q *Queries) GetOrganizationSubscription(ctx context.Context, organizationID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getOrganizationSubscription, organizationID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEndsAt,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganizationSubscription = `-- name: UpsertOrganizationSubscription :one
INSERT INTO subscriptions (
    id,
    organization_id,
    plan_id,
    status,
    current_period_start,
    current_period_end,
    trial_ends_at,
    cancel_at_period_end,
    canceled_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (organization_id)
DO UPDATE SET
    plan_id = EXCLUDED.plan_id,
    status = EXCLUDED.status,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    trial_ends_at = EXCLUDED.trial_ends_at,
    cancel_at_period_end = EXCLUDED.cancel_at_period_end,
    canceled_at = EXCLUDED.canceled_at
RETURNING id, organization_id, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancel_at_period_end, canceled_at, created_at, updated_at
`

type UpsertOrganizationSubscriptionParams struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	OrganizationID     uuid.UUID          `db:"organization_id" json:"organization_id"`
	PlanID             uuid.UUID          `db:"plan_id" json:"plan_id"`
	Status             string             `db:"status" json:"status"`
	CurrentPeriodStart pgtype.Timestamptz `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	TrialEndsAt        pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
	CancelAtPeriodEnd  bool               `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	CanceledAt         pgtype.Timestamptz `db:"canceled_at" json:"canceled_at"`
}

func (q *Queries) UpsertOrganizationSubscription(ctx context.Context, arg UpsertOrganizationSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationSubscription,
		arg.ID,
		arg.OrganizationID,
		arg.PlanID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.TrialEndsAt,
		arg.CancelAtPeriodEnd,
		arg.CanceledAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEndsAt,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
