// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEffectiveOrganizationEntitlement = `-- name: GetEffectiveOrganizationEntitlement :one
SELECT
    COALESCE(
        oe.enabled,
        CASE
            WHEN jsonb_typeof(p.entitlements -> ($1::text)) = 'boolean'
                THEN (p.entitlements ->> ($1::text))::boolean
            ELSE FALSE
        END,
        FALSE
    )::boolean AS enabled
FROM organizations o
LEFT JOIN entitlements oe
  ON oe.organization_id = o.id
 AND oe.capability = ($1::text)
LEFT JOIN subscriptions s
  ON s.organization_id = o.id
 AND s.status IN ('trialing', 'active')
LEFT JOIN plans p
  ON p.id = s.plan_id
WHERE o.id = $2
LIMIT 1
`

type GetEffectiveOrganizationEntitlementParams struct {
	Capability     string    `db:"capability" json:"capability"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetEffectiveOrganizationEntitlement(ctx context.Context, arg GetEffectiveOrganizationEntitlementParams) (bool, error) {
	row := q.db.QueryRow(ctx, getEffectiveOrganizationEntitlement, arg.Capability, arg.OrganizationID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const getOrganizationSubscription = `-- name: GetOrganizationSubscription :one
SELECT id, organization_id, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancel_at_period_end, canceled_at, created_at, updated_at, provider, provider_customer_id, provider_subscription_id, provider_event_created_at
FROM subscriptions
WHERE organization_id = $1
LIMIT 1
`

func (q *Queries) GetOrganizationSubscription(ctx context.Context, organizationID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getOrganizationSubscription, organizationID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEndsAt,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.ProviderEventCreatedAt,
	)
	return i, err
}

const upsertOrganizationSubscription = `-- name: UpsertOrganizationSubscription :one
INSERT INTO subscriptions (
    id,
    organization_id,
    plan_id,
    status,
    current_period_start,
    current_period_end,
    trial_ends_at,
    cancel_at_period_end,
    canceled_at,
    provider,
    provider_customer_id,
    provider_subscription_id,
    provider_event_created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
ON CONFLICT (organization_id)
DO UPDATE SET
    plan_id = EXCLUDED.plan_id,
    status = EXCLUDED.status,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    trial_ends_at = EXCLUDED.trial_ends_at,
    cancel_at_period_end = EXCLUDED.cancel_at_period_end,
    canceled_at = EXCLUDED.canceled_at,
    provider = EXCLUDED.provider,
    provider_customer_id = EXCLUDED.provider_customer_id,
    provider_subscription_id = EXCLUDED.provider_subscription_id,
    provider_event_created_at = EXCLUDED.provider_event_created_at
WHERE subscriptions.provider_event_created_at IS NULL
   OR EXCLUDED.provider_event_created_at IS NULL
   OR EXCLUDED.provider_event_created_at >= subscriptions.provider_event_created_at
RETURNING id, organization_id, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancel_at_period_end, canceled_at, created_at, updated_at, provider, provider_customer_id, provider_subscription_id, provider_event_created_at
`

type UpsertOrganizationSubscriptionParams struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	OrganizationID         uuid.UUID          `db:"organization_id" json:"organization_id"`
	PlanID                 uuid.UUID          `db:"plan_id" json:"plan_id"`
	Status                 string             `db:"status" json:"status"`
	CurrentPeriodStart     pgtype.Timestamptz `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd       pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	TrialEndsAt            pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
	CancelAtPeriodEnd      bool               `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	CanceledAt             pgtype.Timestamptz `db:"canceled_at" json:"canceled_at"`
	Provider               *string            `db:"provider" json:"provider"`
	ProviderCustomerID     *string            `db:"provider_customer_id" json:"provider_customer_id"`
	ProviderSubscriptionID *string            `db:"provider_subscription_id" json:"provider_subscription_id"`
	ProviderEventCreatedAt pgtype.Timestamptz `db:"provider_event_created_at" json:"provider_event_created_at"`
}

func (q *Queries) UpsertOrganizationSubscription(ctx context.Context, arg UpsertOrganizationSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationSubscription,
		arg.ID,
		arg.OrganizationID,
		arg.PlanID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.TrialEndsAt,
		arg.CancelAtPeriodEnd,
		arg.CanceledAt,
		arg.Provider,
		arg.ProviderCustomerID,
		arg.ProviderSubscriptionID,
		arg.ProviderEventCreatedAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEndsAt,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.ProviderEventCreatedAt,
	)
	return i, err
}
