// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_invitations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE tenant_invitations
SET
    status = 'accepted',
    accepted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
AND status = 'pending'
AND expires_at > NOW()
RETURNING id, tenant_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, declined_at, revoked_at, created_at, updated_at
`

func (q *Queries) AcceptInvitation(ctx context.Context, id uuid.UUID) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, id)
	var i TenantInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO tenant_invitations (
    tenant_id,
    invited_by,
    email,
    role,
    token_hash,
    expires_at
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
FROM tenants AS t
JOIN users AS u ON u.id = $2
JOIN tenant_members AS tm ON tm.tenant_id = t.id AND tm.user_id = u.id
WHERE t.id = $1
AND t.status = 'active'
AND t.deleted_at IS NULL
AND u.disabled_at IS NULL
AND tm.status = 'active'
AND tm.role = 'admin'  -- Only admins can invite
RETURNING id, tenant_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, declined_at, revoked_at, created_at, updated_at
`

type CreateInvitationParams struct {
	TenantID  uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	InvitedBy uuid.UUID          `db:"invited_by" json:"invited_by"`
	Email     string             `db:"email" json:"email"`
	Role      string             `db:"role" json:"role"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.TenantID,
		arg.InvitedBy,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i TenantInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const declineInvitation = `-- name: DeclineInvitation :one
UPDATE tenant_invitations
SET
    status = 'declined',
    declined_at = NOW(),
    updated_at = NOW()
WHERE id = $1
AND status = 'pending'
RETURNING id, tenant_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, declined_at, revoked_at, created_at, updated_at
`

func (q *Queries) DeclineInvitation(ctx context.Context, id uuid.UUID) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, declineInvitation, id)
	var i TenantInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireStaleInvitations = `-- name: ExpireStaleInvitations :exec
UPDATE tenant_invitations
SET
    status = 'expired',
    updated_at = NOW()
WHERE status = 'pending'
AND expires_at <= NOW()
`

func (q *Queries) ExpireStaleInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireStaleInvitations)
	return err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT i.id, i.tenant_id, i.invited_by, i.email, i.role, i.token_hash, i.status, i.expires_at, i.accepted_at, i.declined_at, i.revoked_at, i.created_at, i.updated_at
FROM tenant_invitations AS i
JOIN tenants AS t ON t.id = i.tenant_id
WHERE i.token_hash = $1
AND i.status = 'pending'
AND i.expires_at > NOW()
AND t.status = 'active'
AND t.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i TenantInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingInvitationByEmailAndTenant = `-- name: GetPendingInvitationByEmailAndTenant :one
SELECT id, tenant_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, declined_at, revoked_at, created_at, updated_at
FROM tenant_invitations
WHERE tenant_id = $1
AND email = $2
AND status = 'pending'
AND expires_at > NOW()
LIMIT 1
`

type GetPendingInvitationByEmailAndTenantParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Email    string    `db:"email" json:"email"`
}

func (q *Queries) GetPendingInvitationByEmailAndTenant(ctx context.Context, arg GetPendingInvitationByEmailAndTenantParams) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, getPendingInvitationByEmailAndTenant, arg.TenantID, arg.Email)
	var i TenantInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvitationsForEmail = `-- name: ListInvitationsForEmail :many
SELECT i.id, i.tenant_id, i.invited_by, i.email, i.role, i.token_hash, i.status, i.expires_at, i.accepted_at, i.declined_at, i.revoked_at, i.created_at, i.updated_at, t.slug AS tenant_slug, t.name AS tenant_name
FROM tenant_invitations AS i
JOIN tenants AS t ON t.id = i.tenant_id
WHERE i.email = $1
AND i.status = 'pending'
AND i.expires_at > NOW()
AND t.status = 'active'
AND t.deleted_at IS NULL
ORDER BY i.created_at DESC
`

type ListInvitationsForEmailRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TenantID   uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	InvitedBy  uuid.UUID          `db:"invited_by" json:"invited_by"`
	Email      string             `db:"email" json:"email"`
	Role       string             `db:"role" json:"role"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	Status     string             `db:"status" json:"status"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	DeclinedAt pgtype.Timestamptz `db:"declined_at" json:"declined_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	TenantSlug string             `db:"tenant_slug" json:"tenant_slug"`
	TenantName string             `db:"tenant_name" json:"tenant_name"`
}

func (q *Queries) ListInvitationsForEmail(ctx context.Context, email string) ([]ListInvitationsForEmailRow, error) {
	rows, err := q.db.Query(ctx, listInvitationsForEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsForEmailRow{}
	for rows.Next() {
		var i ListInvitationsForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvitedBy,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.DeclinedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantSlug,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsByTenantID = `-- name: ListPendingInvitationsByTenantID :many
SELECT i.id, i.tenant_id, i.invited_by, i.email, i.role, i.token_hash, i.status, i.expires_at, i.accepted_at, i.declined_at, i.revoked_at, i.created_at, i.updated_at
FROM tenant_invitations AS i
WHERE i.tenant_id = $1
AND i.status = 'pending'
AND i.expires_at > NOW()
ORDER BY i.created_at DESC
`

func (q *Queries) ListPendingInvitationsByTenantID(ctx context.Context, tenantID uuid.UUID) ([]TenantInvitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantInvitation{}
	for rows.Next() {
		var i TenantInvitation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvitedBy,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.DeclinedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE tenant_invitations
SET
    status = 'revoked',
    revoked_at = NOW(),
    updated_at = NOW()
WHERE id = $1
AND tenant_id = $2
AND status = 'pending'
RETURNING id, tenant_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, declined_at, revoked_at, created_at, updated_at
`

type RevokeInvitationParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, arg.ID, arg.TenantID)
	var i TenantInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
