// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_agent_sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeVoiceAgentSession = `-- name: CompleteVoiceAgentSession :one
UPDATE voice_agent_sessions AS session
SET
    state = $1,
    turn_count = $2,
    interruption_count = $3,
    first_response_latency_ms = $4,
    avg_turn_latency_ms = $5,
    ended_at = $6,
    updated_at = NOW()
WHERE session.id = $7
  AND session.organization_id = $8
  AND session.state = 'active'
RETURNING session.id, session.organization_id, session.call_id, session.voice_agent_id, session.configuration_revision, session.configuration_snapshot, session.state, session.turn_count, session.interruption_count, session.first_response_latency_ms, session.avg_turn_latency_ms, session.started_at, session.ended_at, session.created_at, session.updated_at
`

type CompleteVoiceAgentSessionParams struct {
	State                  string             `db:"state" json:"state"`
	TurnCount              int32              `db:"turn_count" json:"turn_count"`
	InterruptionCount      int32              `db:"interruption_count" json:"interruption_count"`
	FirstResponseLatencyMs *int32             `db:"first_response_latency_ms" json:"first_response_latency_ms"`
	AvgTurnLatencyMs       *int32             `db:"avg_turn_latency_ms" json:"avg_turn_latency_ms"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	ID                     uuid.UUID          `db:"id" json:"id"`
	OrganizationID         uuid.UUID          `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CompleteVoiceAgentSession(ctx context.Context, arg CompleteVoiceAgentSessionParams) (VoiceAgentSession, error) {
	row := q.db.QueryRow(ctx, completeVoiceAgentSession,
		arg.State,
		arg.TurnCount,
		arg.InterruptionCount,
		arg.FirstResponseLatencyMs,
		arg.AvgTurnLatencyMs,
		arg.EndedAt,
		arg.ID,
		arg.OrganizationID,
	)
	var i VoiceAgentSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CallID,
		&i.VoiceAgentID,
		&i.ConfigurationRevision,
		&i.ConfigurationSnapshot,
		&i.State,
		&i.TurnCount,
		&i.InterruptionCount,
		&i.FirstResponseLatencyMs,
		&i.AvgTurnLatencyMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVoiceAgentSession = `-- name: CreateVoiceAgentSession :one
INSERT INTO voice_agent_sessions (
    organization_id,
    call_id,
    voice_agent_id,
    configuration_revision,
    configuration_snapshot
)
SELECT
    $1,
    c.id,
    agent.id,
    agent.configuration_revision,
    jsonb_build_object(
        'engine', agent.engine,
        'instructions', agent.instructions,
        'voice', agent.voice,
        'language', agent.language,
        'engine_config', agent.engine_config,
        'interruption_policy', agent.interruption_policy,
        'recording_policy', agent.recording_policy,
        'providers', COALESCE((
            SELECT jsonb_agg(
                jsonb_build_object(
                    'role', binding.role,
                    'provider', binding.provider,
                    'credential_id', binding.credential_id,
                    'config', binding.config
                )
                ORDER BY binding.role
            )
            FROM voice_agent_provider_bindings AS binding
            WHERE binding.organization_id = agent.organization_id
              AND binding.voice_agent_id = agent.id
        ), '[]'::jsonb),
        'tools', COALESCE((
            SELECT jsonb_agg(
                jsonb_build_object(
                    'id', tool.id,
                    'name', tool.name,
                    'description', tool.description,
                    'parameters', tool.parameters
                )
                ORDER BY tool.name
            )
            FROM voice_agent_tools AS tool
            WHERE tool.organization_id = agent.organization_id
              AND tool.voice_agent_id = agent.id
              AND tool.enabled = TRUE
        ), '[]'::jsonb)
    )
FROM calls AS c
JOIN organizations AS o
  ON o.id = c.organization_id
JOIN voice_agents AS agent
  ON agent.id = c.voice_agent_id
 AND agent.organization_id = c.organization_id
WHERE c.id = $2
  AND c.organization_id = $1
  AND agent.id = $3
  AND c.state IN ('answered', 'active')
  AND c.ended_at IS NULL
  AND agent.status = 'active'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
RETURNING id, organization_id, call_id, voice_agent_id, configuration_revision, configuration_snapshot, state, turn_count, interruption_count, first_response_latency_ms, avg_turn_latency_ms, started_at, ended_at, created_at, updated_at
`

type CreateVoiceAgentSessionParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	CallID         uuid.UUID `db:"call_id" json:"call_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
}

func (q *Queries) CreateVoiceAgentSession(ctx context.Context, arg CreateVoiceAgentSessionParams) (VoiceAgentSession, error) {
	row := q.db.QueryRow(ctx, createVoiceAgentSession, arg.OrganizationID, arg.CallID, arg.VoiceAgentID)
	var i VoiceAgentSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CallID,
		&i.VoiceAgentID,
		&i.ConfigurationRevision,
		&i.ConfigurationSnapshot,
		&i.State,
		&i.TurnCount,
		&i.InterruptionCount,
		&i.FirstResponseLatencyMs,
		&i.AvgTurnLatencyMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveVoiceAgentSessionByCallID = `-- name: GetActiveVoiceAgentSessionByCallID :one
SELECT session.id, session.organization_id, session.call_id, session.voice_agent_id, session.configuration_revision, session.configuration_snapshot, session.state, session.turn_count, session.interruption_count, session.first_response_latency_ms, session.avg_turn_latency_ms, session.started_at, session.ended_at, session.created_at, session.updated_at
FROM voice_agent_sessions AS session
JOIN organizations AS o ON o.id = session.organization_id
WHERE session.organization_id = $1
  AND session.call_id = $2
  AND session.state = 'active'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetActiveVoiceAgentSessionByCallIDParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	CallID         uuid.UUID `db:"call_id" json:"call_id"`
}

func (q *Queries) GetActiveVoiceAgentSessionByCallID(ctx context.Context, arg GetActiveVoiceAgentSessionByCallIDParams) (VoiceAgentSession, error) {
	row := q.db.QueryRow(ctx, getActiveVoiceAgentSessionByCallID, arg.OrganizationID, arg.CallID)
	var i VoiceAgentSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CallID,
		&i.VoiceAgentID,
		&i.ConfigurationRevision,
		&i.ConfigurationSnapshot,
		&i.State,
		&i.TurnCount,
		&i.InterruptionCount,
		&i.FirstResponseLatencyMs,
		&i.AvgTurnLatencyMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoiceAgentSessionByID = `-- name: GetVoiceAgentSessionByID :one
SELECT session.id, session.organization_id, session.call_id, session.voice_agent_id, session.configuration_revision, session.configuration_snapshot, session.state, session.turn_count, session.interruption_count, session.first_response_latency_ms, session.avg_turn_latency_ms, session.started_at, session.ended_at, session.created_at, session.updated_at
FROM voice_agent_sessions AS session
WHERE session.id = $1
  AND session.organization_id = $2
LIMIT 1
`

type GetVoiceAgentSessionByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetVoiceAgentSessionByID(ctx context.Context, arg GetVoiceAgentSessionByIDParams) (VoiceAgentSession, error) {
	row := q.db.QueryRow(ctx, getVoiceAgentSessionByID, arg.ID, arg.OrganizationID)
	var i VoiceAgentSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CallID,
		&i.VoiceAgentID,
		&i.ConfigurationRevision,
		&i.ConfigurationSnapshot,
		&i.State,
		&i.TurnCount,
		&i.InterruptionCount,
		&i.FirstResponseLatencyMs,
		&i.AvgTurnLatencyMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
