// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_applications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createVoiceApplication = `-- name: CreateVoiceApplication :one
INSERT INTO voice_applications (
    organization_id,
    name,
    ring_timeout_seconds,
    caller_id,
    voice_url,
    callback_url
)
SELECT
    $1 as organization_id,
    $2 as name,
    COALESCE($3, 30) as ring_timeout_seconds,
    $4 as caller_id,
    $5 as voice_url,
    $6 as callback_url
FROM organizations AS t
WHERE t.id = $1
  AND t.status = 'active'
  AND t.deleted_at IS NULL
RETURNING id, organization_id, name, ring_timeout_seconds, caller_id, status, voice_url, callback_url, created_at, updated_at
`

type CreateVoiceApplicationParams struct {
	OrganizationID     uuid.UUID `db:"organization_id" json:"organization_id"`
	Name               string    `db:"name" json:"name"`
	RingTimeoutSeconds *int32    `db:"ring_timeout_seconds" json:"ring_timeout_seconds"`
	CallerID           *string   `db:"caller_id" json:"caller_id"`
	VoiceUrl           *string   `db:"voice_url" json:"voice_url"`
	CallbackUrl        *string   `db:"callback_url" json:"callback_url"`
}

func (q *Queries) CreateVoiceApplication(ctx context.Context, arg CreateVoiceApplicationParams) (VoiceApplication, error) {
	row := q.db.QueryRow(ctx, createVoiceApplication,
		arg.OrganizationID,
		arg.Name,
		arg.RingTimeoutSeconds,
		arg.CallerID,
		arg.VoiceUrl,
		arg.CallbackUrl,
	)
	var i VoiceApplication
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.RingTimeoutSeconds,
		&i.CallerID,
		&i.Status,
		&i.VoiceUrl,
		&i.CallbackUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVoiceBinding = `-- name: CreateVoiceBinding :one
INSERT INTO voice_bindings (
    voice_application_id,
    phone_number_id,
    sip_domain_id,
    subscriber_id
)
SELECT
    $1,
    $2::uuid,
    $3::uuid,
    $4::uuid
FROM voice_applications AS va
JOIN organizations AS t ON t.id = va.organization_id
WHERE va.id = $1
  AND va.organization_id = $5
  AND va.status = 'active'
  AND t.status = 'active'
  AND t.deleted_at IS NULL
RETURNING id, voice_application_id, phone_number_id, sip_domain_id, subscriber_id, created_at
`

type CreateVoiceBindingParams struct {
	VoiceApplicationID uuid.UUID  `db:"voice_application_id" json:"voice_application_id"`
	PhoneNumberID      *uuid.UUID `db:"phone_number_id" json:"phone_number_id"`
	SipDomainID        *uuid.UUID `db:"sip_domain_id" json:"sip_domain_id"`
	SubscriberID       *uuid.UUID `db:"subscriber_id" json:"subscriber_id"`
	OrganizationID     uuid.UUID  `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CreateVoiceBinding(ctx context.Context, arg CreateVoiceBindingParams) (VoiceBinding, error) {
	row := q.db.QueryRow(ctx, createVoiceBinding,
		arg.VoiceApplicationID,
		arg.PhoneNumberID,
		arg.SipDomainID,
		arg.SubscriberID,
		arg.OrganizationID,
	)
	var i VoiceBinding
	err := row.Scan(
		&i.ID,
		&i.VoiceApplicationID,
		&i.PhoneNumberID,
		&i.SipDomainID,
		&i.SubscriberID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVoiceBinding = `-- name: DeleteVoiceBinding :exec
DELETE FROM voice_bindings
WHERE voice_bindings.id = $1
  AND voice_bindings.voice_application_id = $2
  AND voice_application_id IN (
      SELECT va.id FROM voice_applications AS va
      WHERE va.organization_id = $3
  )
`

type DeleteVoiceBindingParams struct {
	ID                 uuid.UUID `db:"id" json:"id"`
	VoiceApplicationID uuid.UUID `db:"voice_application_id" json:"voice_application_id"`
	OrganizationID     uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) DeleteVoiceBinding(ctx context.Context, arg DeleteVoiceBindingParams) error {
	_, err := q.db.Exec(ctx, deleteVoiceBinding, arg.ID, arg.VoiceApplicationID, arg.OrganizationID)
	return err
}

const disableVoiceApplication = `-- name: DisableVoiceApplication :exec
UPDATE voice_applications
SET
    status = 'disabled',
    updated_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND status = 'active'
`

type DisableVoiceApplicationParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) DisableVoiceApplication(ctx context.Context, arg DisableVoiceApplicationParams) error {
	_, err := q.db.Exec(ctx, disableVoiceApplication, arg.ID, arg.OrganizationID)
	return err
}

const enableVoiceApplication = `-- name: EnableVoiceApplication :exec
UPDATE voice_applications
SET
    status = 'active',
    updated_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND status = 'disabled'
`

type EnableVoiceApplicationParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) EnableVoiceApplication(ctx context.Context, arg EnableVoiceApplicationParams) error {
	_, err := q.db.Exec(ctx, enableVoiceApplication, arg.ID, arg.OrganizationID)
	return err
}

const getVoiceApplicationByID = `-- name: GetVoiceApplicationByID :one
SELECT va.id, va.organization_id, va.name, va.ring_timeout_seconds, va.caller_id, va.status, va.voice_url, va.callback_url, va.created_at, va.updated_at
FROM voice_applications AS va
JOIN organizations AS t ON t.id = va.organization_id
WHERE va.id = $1
  AND va.organization_id = $2
  AND va.status = 'active'
  AND t.status = 'active'
  AND t.deleted_at IS NULL
LIMIT 1
`

type GetVoiceApplicationByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetVoiceApplicationByID(ctx context.Context, arg GetVoiceApplicationByIDParams) (VoiceApplication, error) {
	row := q.db.QueryRow(ctx, getVoiceApplicationByID, arg.ID, arg.OrganizationID)
	var i VoiceApplication
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.RingTimeoutSeconds,
		&i.CallerID,
		&i.Status,
		&i.VoiceUrl,
		&i.CallbackUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoiceApplicationByName = `-- name: GetVoiceApplicationByName :one
SELECT va.id, va.organization_id, va.name, va.ring_timeout_seconds, va.caller_id, va.status, va.voice_url, va.callback_url, va.created_at, va.updated_at
FROM voice_applications AS va
JOIN organizations AS t ON t.id = va.organization_id
WHERE va.organization_id = $1
  AND va.name = $2
  AND va.status = 'active'
  AND t.status = 'active'
  AND t.deleted_at IS NULL
LIMIT 1
`

type GetVoiceApplicationByNameParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Name           string    `db:"name" json:"name"`
}

func (q *Queries) GetVoiceApplicationByName(ctx context.Context, arg GetVoiceApplicationByNameParams) (VoiceApplication, error) {
	row := q.db.QueryRow(ctx, getVoiceApplicationByName, arg.OrganizationID, arg.Name)
	var i VoiceApplication
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.RingTimeoutSeconds,
		&i.CallerID,
		&i.Status,
		&i.VoiceUrl,
		&i.CallbackUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoiceBindingByID = `-- name: GetVoiceBindingByID :one
SELECT vb.id, vb.voice_application_id, vb.phone_number_id, vb.sip_domain_id, vb.subscriber_id, vb.created_at
FROM voice_bindings AS vb
JOIN voice_applications AS va ON va.id = vb.voice_application_id
JOIN organizations AS t ON t.id = va.organization_id
WHERE vb.id = $1
  AND va.organization_id = $2
  AND va.status = 'active'
  AND t.status = 'active'
  AND t.deleted_at IS NULL
LIMIT 1
`

type GetVoiceBindingByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetVoiceBindingByID(ctx context.Context, arg GetVoiceBindingByIDParams) (VoiceBinding, error) {
	row := q.db.QueryRow(ctx, getVoiceBindingByID, arg.ID, arg.OrganizationID)
	var i VoiceBinding
	err := row.Scan(
		&i.ID,
		&i.VoiceApplicationID,
		&i.PhoneNumberID,
		&i.SipDomainID,
		&i.SubscriberID,
		&i.CreatedAt,
	)
	return i, err
}

const getVoiceBindingByPhoneNumberID = `-- name: GetVoiceBindingByPhoneNumberID :one
SELECT vb.id, vb.voice_application_id, vb.phone_number_id, vb.sip_domain_id, vb.subscriber_id, vb.created_at
FROM voice_bindings AS vb
JOIN voice_applications AS va ON va.id = vb.voice_application_id
JOIN organizations AS t ON t.id = va.organization_id
WHERE vb.phone_number_id = $1
  AND va.organization_id = $2
  AND va.status = 'active'
  AND t.status = 'active'
  AND t.deleted_at IS NULL
LIMIT 1
`

type GetVoiceBindingByPhoneNumberIDParams struct {
	PhoneNumberID  *uuid.UUID `db:"phone_number_id" json:"phone_number_id"`
	OrganizationID uuid.UUID  `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetVoiceBindingByPhoneNumberID(ctx context.Context, arg GetVoiceBindingByPhoneNumberIDParams) (VoiceBinding, error) {
	row := q.db.QueryRow(ctx, getVoiceBindingByPhoneNumberID, arg.PhoneNumberID, arg.OrganizationID)
	var i VoiceBinding
	err := row.Scan(
		&i.ID,
		&i.VoiceApplicationID,
		&i.PhoneNumberID,
		&i.SipDomainID,
		&i.SubscriberID,
		&i.CreatedAt,
	)
	return i, err
}

const getVoiceBindingBySipDomainID = `-- name: GetVoiceBindingBySipDomainID :one
SELECT vb.id, vb.voice_application_id, vb.phone_number_id, vb.sip_domain_id, vb.subscriber_id, vb.created_at
FROM voice_bindings AS vb
JOIN voice_applications AS va ON va.id = vb.voice_application_id
JOIN organizations AS t ON t.id = va.organization_id
WHERE vb.sip_domain_id = $1
  AND va.organization_id = $2
  AND va.status = 'active'
  AND t.status = 'active'
  AND t.deleted_at IS NULL
LIMIT 1
`

type GetVoiceBindingBySipDomainIDParams struct {
	SipDomainID    *uuid.UUID `db:"sip_domain_id" json:"sip_domain_id"`
	OrganizationID uuid.UUID  `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetVoiceBindingBySipDomainID(ctx context.Context, arg GetVoiceBindingBySipDomainIDParams) (VoiceBinding, error) {
	row := q.db.QueryRow(ctx, getVoiceBindingBySipDomainID, arg.SipDomainID, arg.OrganizationID)
	var i VoiceBinding
	err := row.Scan(
		&i.ID,
		&i.VoiceApplicationID,
		&i.PhoneNumberID,
		&i.SipDomainID,
		&i.SubscriberID,
		&i.CreatedAt,
	)
	return i, err
}

const getVoiceBindingBySubscriberID = `-- name: GetVoiceBindingBySubscriberID :one
SELECT vb.id, vb.voice_application_id, vb.phone_number_id, vb.sip_domain_id, vb.subscriber_id, vb.created_at
FROM voice_bindings AS vb
JOIN voice_applications AS va ON va.id = vb.voice_application_id
JOIN organizations AS t ON t.id = va.organization_id
WHERE vb.subscriber_id = $1
  AND va.organization_id = $2
  AND va.status = 'active'
  AND t.status = 'active'
  AND t.deleted_at IS NULL
LIMIT 1
`

type GetVoiceBindingBySubscriberIDParams struct {
	SubscriberID   *uuid.UUID `db:"subscriber_id" json:"subscriber_id"`
	OrganizationID uuid.UUID  `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetVoiceBindingBySubscriberID(ctx context.Context, arg GetVoiceBindingBySubscriberIDParams) (VoiceBinding, error) {
	row := q.db.QueryRow(ctx, getVoiceBindingBySubscriberID, arg.SubscriberID, arg.OrganizationID)
	var i VoiceBinding
	err := row.Scan(
		&i.ID,
		&i.VoiceApplicationID,
		&i.PhoneNumberID,
		&i.SipDomainID,
		&i.SubscriberID,
		&i.CreatedAt,
	)
	return i, err
}

const listVoiceApplicationsByOrganizationID = `-- name: ListVoiceApplicationsByOrganizationID :many
SELECT va.id, va.organization_id, va.name, va.ring_timeout_seconds, va.caller_id, va.status, va.voice_url, va.callback_url, va.created_at, va.updated_at
FROM voice_applications AS va
WHERE va.organization_id = $1
  AND va.status = 'active'
ORDER BY va.created_at DESC
`

func (q *Queries) ListVoiceApplicationsByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]VoiceApplication, error) {
	rows, err := q.db.Query(ctx, listVoiceApplicationsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceApplication{}
	for rows.Next() {
		var i VoiceApplication
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.RingTimeoutSeconds,
			&i.CallerID,
			&i.Status,
			&i.VoiceUrl,
			&i.CallbackUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoiceBindingsByApplicationID = `-- name: ListVoiceBindingsByApplicationID :many
SELECT vb.id, vb.voice_application_id, vb.phone_number_id, vb.sip_domain_id, vb.subscriber_id, vb.created_at
FROM voice_bindings AS vb
JOIN voice_applications AS va ON va.id = vb.voice_application_id
WHERE vb.voice_application_id = $1
  AND va.organization_id = $2
ORDER BY vb.created_at DESC
`

type ListVoiceBindingsByApplicationIDParams struct {
	VoiceApplicationID uuid.UUID `db:"voice_application_id" json:"voice_application_id"`
	OrganizationID     uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ListVoiceBindingsByApplicationID(ctx context.Context, arg ListVoiceBindingsByApplicationIDParams) ([]VoiceBinding, error) {
	rows, err := q.db.Query(ctx, listVoiceBindingsByApplicationID, arg.VoiceApplicationID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceBinding{}
	for rows.Next() {
		var i VoiceBinding
		if err := rows.Scan(
			&i.ID,
			&i.VoiceApplicationID,
			&i.PhoneNumberID,
			&i.SipDomainID,
			&i.SubscriberID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoiceApplication = `-- name: UpdateVoiceApplication :one
UPDATE voice_applications
SET
    name = COALESCE($1, name),
    ring_timeout_seconds = COALESCE($2, ring_timeout_seconds),
    caller_id = COALESCE($3, caller_id),
    voice_url = COALESCE($4, voice_url),
    callback_url = COALESCE($5, callback_url),
    updated_at = NOW()
WHERE id = $6
  AND organization_id = $7
  AND status = 'active'
RETURNING id, organization_id, name, ring_timeout_seconds, caller_id, status, voice_url, callback_url, created_at, updated_at
`

type UpdateVoiceApplicationParams struct {
	Name               *string   `db:"name" json:"name"`
	RingTimeoutSeconds *int32    `db:"ring_timeout_seconds" json:"ring_timeout_seconds"`
	CallerID           *string   `db:"caller_id" json:"caller_id"`
	VoiceUrl           *string   `db:"voice_url" json:"voice_url"`
	CallbackUrl        *string   `db:"callback_url" json:"callback_url"`
	ID                 uuid.UUID `db:"id" json:"id"`
	OrganizationID     uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdateVoiceApplication(ctx context.Context, arg UpdateVoiceApplicationParams) (VoiceApplication, error) {
	row := q.db.QueryRow(ctx, updateVoiceApplication,
		arg.Name,
		arg.RingTimeoutSeconds,
		arg.CallerID,
		arg.VoiceUrl,
		arg.CallbackUrl,
		arg.ID,
		arg.OrganizationID,
	)
	var i VoiceApplication
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.RingTimeoutSeconds,
		&i.CallerID,
		&i.Status,
		&i.VoiceUrl,
		&i.CallbackUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
