// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_agent_turns.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVoiceAgentTurn = `-- name: CreateVoiceAgentTurn :one
INSERT INTO voice_agent_turns (
    organization_id,
    session_id,
    sequence,
    role,
    content,
    provider_id,
    tool_name,
    tool_call_id,
    metadata,
    speech_started_at,
    speech_ended_at,
    stt_latency_ms,
    llm_ttft_ms,
    tts_ttfb_ms,
    turn_latency_ms
)
SELECT
    $1,
    session.id,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
FROM voice_agent_sessions AS session
JOIN organizations AS o ON o.id = session.organization_id
WHERE session.id = $15
  AND session.organization_id = $1
  AND session.state = 'active'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
RETURNING id, organization_id, session_id, sequence, role, content, provider_id, tool_name, tool_call_id, metadata, speech_started_at, speech_ended_at, stt_latency_ms, llm_ttft_ms, tts_ttfb_ms, turn_latency_ms, created_at
`

type CreateVoiceAgentTurnParams struct {
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	Sequence        int32              `db:"sequence" json:"sequence"`
	Role            string             `db:"role" json:"role"`
	Content         string             `db:"content" json:"content"`
	ProviderID      *string            `db:"provider_id" json:"provider_id"`
	ToolName        *string            `db:"tool_name" json:"tool_name"`
	ToolCallID      *string            `db:"tool_call_id" json:"tool_call_id"`
	Metadata        []byte             `db:"metadata" json:"metadata"`
	SpeechStartedAt pgtype.Timestamptz `db:"speech_started_at" json:"speech_started_at"`
	SpeechEndedAt   pgtype.Timestamptz `db:"speech_ended_at" json:"speech_ended_at"`
	SttLatencyMs    *int32             `db:"stt_latency_ms" json:"stt_latency_ms"`
	LlmTtftMs       *int32             `db:"llm_ttft_ms" json:"llm_ttft_ms"`
	TtsTtfbMs       *int32             `db:"tts_ttfb_ms" json:"tts_ttfb_ms"`
	TurnLatencyMs   *int32             `db:"turn_latency_ms" json:"turn_latency_ms"`
	SessionID       uuid.UUID          `db:"session_id" json:"session_id"`
}

func (q *Queries) CreateVoiceAgentTurn(ctx context.Context, arg CreateVoiceAgentTurnParams) (VoiceAgentTurn, error) {
	row := q.db.QueryRow(ctx, createVoiceAgentTurn,
		arg.OrganizationID,
		arg.Sequence,
		arg.Role,
		arg.Content,
		arg.ProviderID,
		arg.ToolName,
		arg.ToolCallID,
		arg.Metadata,
		arg.SpeechStartedAt,
		arg.SpeechEndedAt,
		arg.SttLatencyMs,
		arg.LlmTtftMs,
		arg.TtsTtfbMs,
		arg.TurnLatencyMs,
		arg.SessionID,
	)
	var i VoiceAgentTurn
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.Sequence,
		&i.Role,
		&i.Content,
		&i.ProviderID,
		&i.ToolName,
		&i.ToolCallID,
		&i.Metadata,
		&i.SpeechStartedAt,
		&i.SpeechEndedAt,
		&i.SttLatencyMs,
		&i.LlmTtftMs,
		&i.TtsTtfbMs,
		&i.TurnLatencyMs,
		&i.CreatedAt,
	)
	return i, err
}

const listVoiceAgentTurnsBySessionID = `-- name: ListVoiceAgentTurnsBySessionID :many
SELECT turn.id, turn.organization_id, turn.session_id, turn.sequence, turn.role, turn.content, turn.provider_id, turn.tool_name, turn.tool_call_id, turn.metadata, turn.speech_started_at, turn.speech_ended_at, turn.stt_latency_ms, turn.llm_ttft_ms, turn.tts_ttfb_ms, turn.turn_latency_ms, turn.created_at
FROM voice_agent_turns AS turn
JOIN voice_agent_sessions AS session
  ON session.id = turn.session_id
 AND session.organization_id = turn.organization_id
WHERE turn.organization_id = $1
  AND turn.session_id = $2
ORDER BY turn.sequence ASC
`

type ListVoiceAgentTurnsBySessionIDParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	SessionID      uuid.UUID `db:"session_id" json:"session_id"`
}

func (q *Queries) ListVoiceAgentTurnsBySessionID(ctx context.Context, arg ListVoiceAgentTurnsBySessionIDParams) ([]VoiceAgentTurn, error) {
	rows, err := q.db.Query(ctx, listVoiceAgentTurnsBySessionID, arg.OrganizationID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceAgentTurn{}
	for rows.Next() {
		var i VoiceAgentTurn
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SessionID,
			&i.Sequence,
			&i.Role,
			&i.Content,
			&i.ProviderID,
			&i.ToolName,
			&i.ToolCallID,
			&i.Metadata,
			&i.SpeechStartedAt,
			&i.SpeechEndedAt,
			&i.SttLatencyMs,
			&i.LlmTtftMs,
			&i.TtsTtfbMs,
			&i.TurnLatencyMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
