// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet_topups.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertPaymentProviderEvent = `-- name: InsertPaymentProviderEvent :one
INSERT INTO payment_provider_events (
    payment_id, organization_id, provider, provider_event_id,
    event_type, payload_sha256, payload
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
ON CONFLICT (provider, provider_event_id) DO NOTHING
RETURNING id, payment_id, organization_id, provider, provider_event_id, event_type, payload_sha256, payload, received_at, processed_at
`

type InsertPaymentProviderEventParams struct {
	PaymentID       uuid.UUID `db:"payment_id" json:"payment_id"`
	OrganizationID  uuid.UUID `db:"organization_id" json:"organization_id"`
	Provider        string    `db:"provider" json:"provider"`
	ProviderEventID string    `db:"provider_event_id" json:"provider_event_id"`
	EventType       string    `db:"event_type" json:"event_type"`
	PayloadSha256   string    `db:"payload_sha256" json:"payload_sha256"`
	Payload         []byte    `db:"payload" json:"payload"`
}

func (q *Queries) InsertPaymentProviderEvent(ctx context.Context, arg InsertPaymentProviderEventParams) (PaymentProviderEvent, error) {
	row := q.db.QueryRow(ctx, insertPaymentProviderEvent,
		arg.PaymentID,
		arg.OrganizationID,
		arg.Provider,
		arg.ProviderEventID,
		arg.EventType,
		arg.PayloadSha256,
		arg.Payload,
	)
	var i PaymentProviderEvent
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.PayloadSha256,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const lockWalletTopupByReference = `-- name: LockWalletTopupByReference :one
SELECT
    c.id AS checkout_order_id,
    c.organization_id,
    c.wallet_id,
    c.provider,
    c.reference,
    c.amount_minor,
    c.currency,
    c.status AS checkout_status,
    p.id AS payment_id,
    p.provider_payment_id,
    p.status AS payment_status
FROM checkouts AS c
JOIN payments AS p ON p.checkout_id = c.id
WHERE c.reference = $1
  AND c.checkout_type = 'wallet_topup'
FOR UPDATE OF c, p
`

type LockWalletTopupByReferenceRow struct {
	CheckoutOrderID   uuid.UUID  `db:"checkout_order_id" json:"checkout_order_id"`
	OrganizationID    uuid.UUID  `db:"organization_id" json:"organization_id"`
	WalletID          *uuid.UUID `db:"wallet_id" json:"wallet_id"`
	Provider          string     `db:"provider" json:"provider"`
	Reference         string     `db:"reference" json:"reference"`
	AmountMinor       int64      `db:"amount_minor" json:"amount_minor"`
	Currency          string     `db:"currency" json:"currency"`
	CheckoutStatus    string     `db:"checkout_status" json:"checkout_status"`
	PaymentID         uuid.UUID  `db:"payment_id" json:"payment_id"`
	ProviderPaymentID *string    `db:"provider_payment_id" json:"provider_payment_id"`
	PaymentStatus     string     `db:"payment_status" json:"payment_status"`
}

func (q *Queries) LockWalletTopupByReference(ctx context.Context, reference string) (LockWalletTopupByReferenceRow, error) {
	row := q.db.QueryRow(ctx, lockWalletTopupByReference, reference)
	var i LockWalletTopupByReferenceRow
	err := row.Scan(
		&i.CheckoutOrderID,
		&i.OrganizationID,
		&i.WalletID,
		&i.Provider,
		&i.Reference,
		&i.AmountMinor,
		&i.Currency,
		&i.CheckoutStatus,
		&i.PaymentID,
		&i.ProviderPaymentID,
		&i.PaymentStatus,
	)
	return i, err
}

const markPaymentProviderEventProcessed = `-- name: MarkPaymentProviderEventProcessed :exec
UPDATE payment_provider_events
SET processed_at = NOW()
WHERE id = $1
  AND processed_at IS NULL
`

func (q *Queries) MarkPaymentProviderEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPaymentProviderEventProcessed, id)
	return err
}
