// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelWebhookDeliveriesForEndpoint = `-- name: CancelWebhookDeliveriesForEndpoint :execrows
UPDATE webhook_deliveries
SET status = 'canceled',
    last_error = 'Webhook endpoint disabled before delivery',
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
FROM webhook_endpoints
WHERE webhook_deliveries.endpoint_id = webhook_endpoints.id
  AND webhook_deliveries.endpoint_id = $1
  AND webhook_endpoints.tenant_id = $2
  AND webhook_deliveries.status IN ('pending', 'retrying')
`

type CancelWebhookDeliveriesForEndpointParams struct {
	EndpointID uuid.UUID `db:"endpoint_id" json:"endpoint_id"`
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) CancelWebhookDeliveriesForEndpoint(ctx context.Context, arg CancelWebhookDeliveriesForEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelWebhookDeliveriesForEndpoint, arg.EndpointID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimWebhookDeliveries = `-- name: ClaimWebhookDeliveries :many
WITH candidates AS (
    SELECT webhook_deliveries.id
    FROM webhook_deliveries
    JOIN webhook_endpoints ON webhook_endpoints.id = webhook_deliveries.endpoint_id
    JOIN webhook_events ON webhook_events.id = webhook_deliveries.event_id
    JOIN tenants ON tenants.id = webhook_events.tenant_id
    WHERE webhook_deliveries.status IN ('pending', 'retrying')
      AND webhook_deliveries.next_attempt_at <= now()
      AND webhook_endpoints.enabled = true
      AND webhook_endpoints.disabled_at IS NULL
      AND tenants.status = 'active'
      AND (
          webhook_deliveries.locked_at IS NULL
          OR webhook_deliveries.locked_at < $2
      )
    ORDER BY webhook_deliveries.next_attempt_at, webhook_deliveries.created_at
    FOR UPDATE OF webhook_deliveries SKIP LOCKED
    LIMIT $3
)
UPDATE webhook_deliveries
SET locked_at = now(),
    locked_by = $1,
    attempt_count = webhook_deliveries.attempt_count + 1,
    last_attempt_at = now(),
    updated_at = now()
FROM candidates,
     webhook_events,
     webhook_endpoints
WHERE webhook_deliveries.id = candidates.id
  AND webhook_events.id = webhook_deliveries.event_id
  AND webhook_endpoints.id = webhook_deliveries.endpoint_id
RETURNING
    webhook_deliveries.id,
    webhook_deliveries.event_id,
    webhook_deliveries.endpoint_id,
    webhook_deliveries.attempt_count,
    webhook_events.tenant_id,
    webhook_events.event_type,
    webhook_events.payload,
    webhook_events.occurred_at,
    webhook_endpoints.url,
    webhook_endpoints.signing_secret
`

type ClaimWebhookDeliveriesParams struct {
	WorkerID    *string            `db:"worker_id" json:"worker_id"`
	StaleBefore pgtype.Timestamptz `db:"stale_before" json:"stale_before"`
	LimitCount  int32              `db:"limit_count" json:"limit_count"`
}

type ClaimWebhookDeliveriesRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EventID       uuid.UUID          `db:"event_id" json:"event_id"`
	EndpointID    uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	AttemptCount  int32              `db:"attempt_count" json:"attempt_count"`
	TenantID      uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	Payload       []byte             `db:"payload" json:"payload"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	Url           string             `db:"url" json:"url"`
	SigningSecret []byte             `db:"signing_secret" json:"signing_secret"`
}

func (q *Queries) ClaimWebhookDeliveries(ctx context.Context, arg ClaimWebhookDeliveriesParams) ([]ClaimWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimWebhookDeliveries, arg.WorkerID, arg.StaleBefore, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimWebhookDeliveriesRow{}
	for rows.Next() {
		var i ClaimWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.AttemptCount,
			&i.TenantID,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
			&i.Url,
			&i.SigningSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWebhookDeliveriesForEvent = `-- name: CreateWebhookDeliveriesForEvent :execrows
INSERT INTO webhook_deliveries (event_id, endpoint_id, status, next_attempt_at)
SELECT
    $1,
    webhook_endpoints.id,
    'pending',
    $2
FROM webhook_endpoints
JOIN webhook_events ON webhook_events.id = $1
JOIN tenants ON tenants.id = webhook_events.tenant_id
WHERE webhook_endpoints.enabled = true
  AND webhook_endpoints.disabled_at IS NULL
  AND webhook_events.event_type = ANY(webhook_endpoints.subscribed_events)
  AND tenants.status = 'active'
ON CONFLICT (event_id, endpoint_id) DO NOTHING
`

type CreateWebhookDeliveriesForEventParams struct {
	EventID       uuid.UUID          `db:"event_id" json:"event_id"`
	NextAttemptAt pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
}

func (q *Queries) CreateWebhookDeliveriesForEvent(ctx context.Context, arg CreateWebhookDeliveriesForEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, createWebhookDeliveriesForEvent, arg.EventID, arg.NextAttemptAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (
    event_id,
    endpoint_id,
    status,
    next_attempt_at
)
SELECT
    webhook_events.id,
    webhook_endpoints.id,
    'pending',
    $1
FROM webhook_events
JOIN webhook_endpoints ON webhook_endpoints.id = $2
JOIN tenants ON tenants.id = webhook_events.tenant_id
WHERE webhook_events.id = $3
  AND webhook_endpoints.enabled = true
  AND webhook_endpoints.disabled_at IS NULL
  AND tenants.status = 'active'
ON CONFLICT (event_id, endpoint_id) DO UPDATE
SET status = EXCLUDED.status
RETURNING id, event_id, endpoint_id, status, attempt_count, replay_count, next_attempt_at, last_attempt_at, last_replayed_at, response_status, response_body, last_error, delivered_at, locked_at, locked_by, created_at, updated_at
`

type CreateWebhookDeliveryParams struct {
	NextAttemptAt pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	EndpointID    uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	EventID       uuid.UUID          `db:"event_id" json:"event_id"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery, arg.NextAttemptAt, arg.EndpointID, arg.EventID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT webhook_deliveries.id, webhook_deliveries.event_id, webhook_deliveries.endpoint_id, webhook_deliveries.status, webhook_deliveries.attempt_count, webhook_deliveries.replay_count, webhook_deliveries.next_attempt_at, webhook_deliveries.last_attempt_at, webhook_deliveries.last_replayed_at, webhook_deliveries.response_status, webhook_deliveries.response_body, webhook_deliveries.last_error, webhook_deliveries.delivered_at, webhook_deliveries.locked_at, webhook_deliveries.locked_by, webhook_deliveries.created_at, webhook_deliveries.updated_at
FROM webhook_deliveries
JOIN webhook_events ON webhook_events.id = webhook_deliveries.event_id
JOIN tenants ON tenants.id = webhook_events.tenant_id
WHERE webhook_deliveries.id = $1
  AND webhook_events.tenant_id = $2
  AND tenants.status = 'active'
LIMIT 1
`

type GetWebhookDeliveryParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetWebhookDelivery(ctx context.Context, arg GetWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, arg.ID, arg.TenantID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookDeliveriesForEvent = `-- name: ListWebhookDeliveriesForEvent :many
SELECT webhook_deliveries.id, webhook_deliveries.event_id, webhook_deliveries.endpoint_id, webhook_deliveries.status, webhook_deliveries.attempt_count, webhook_deliveries.replay_count, webhook_deliveries.next_attempt_at, webhook_deliveries.last_attempt_at, webhook_deliveries.last_replayed_at, webhook_deliveries.response_status, webhook_deliveries.response_body, webhook_deliveries.last_error, webhook_deliveries.delivered_at, webhook_deliveries.locked_at, webhook_deliveries.locked_by, webhook_deliveries.created_at, webhook_deliveries.updated_at
FROM webhook_deliveries
JOIN webhook_events ON webhook_events.id = webhook_deliveries.event_id
JOIN tenants ON tenants.id = webhook_events.tenant_id
WHERE webhook_deliveries.event_id = $1
  AND webhook_events.tenant_id = $2
  AND tenants.status = 'active'
ORDER BY webhook_deliveries.created_at DESC
LIMIT $4
OFFSET $3
`

type ListWebhookDeliveriesForEventParams struct {
	EventID     uuid.UUID `db:"event_id" json:"event_id"`
	TenantID    uuid.UUID `db:"tenant_id" json:"tenant_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListWebhookDeliveriesForEvent(ctx context.Context, arg ListWebhookDeliveriesForEventParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesForEvent,
		arg.EventID,
		arg.TenantID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.Status,
			&i.AttemptCount,
			&i.ReplayCount,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.LastReplayedAt,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.LastError,
			&i.DeliveredAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeliveryFailed = `-- name: MarkWebhookDeliveryFailed :one
WITH failed AS (
    UPDATE webhook_deliveries
    SET status = 'failed',
        response_status = $1,
        response_body = $2,
        last_error = $3,
        locked_at = NULL,
        locked_by = NULL,
        updated_at = now()
    WHERE webhook_deliveries.id = $4
      AND locked_by = $5
    RETURNING id, event_id, endpoint_id, status, attempt_count, replay_count, next_attempt_at, last_attempt_at, last_replayed_at, response_status, response_body, last_error, delivered_at, locked_at, locked_by, created_at, updated_at
), update_endpoint AS (
    UPDATE webhook_endpoints
    SET consecutive_failures = consecutive_failures + 1,
        last_failure_at = now(),
        enabled = CASE
            WHEN consecutive_failures + 1 >= $6::integer THEN false
            ELSE enabled
        END,
        disabled_at = CASE
            WHEN consecutive_failures + 1 >= $6::integer THEN COALESCE(disabled_at, now())
            ELSE disabled_at
        END,
        disabled_reason = CASE
            WHEN enabled AND consecutive_failures + 1 >= $6::integer THEN 'failure_threshold'
            ELSE disabled_reason
        END,
        updated_at = now()
    WHERE webhook_endpoints.id = (SELECT endpoint_id FROM failed)
    RETURNING webhook_endpoints.id
)
SELECT id, event_id, endpoint_id, status, attempt_count, replay_count, next_attempt_at, last_attempt_at, last_replayed_at, response_status, response_body, last_error, delivered_at, locked_at, locked_by, created_at, updated_at FROM failed
`

type MarkWebhookDeliveryFailedParams struct {
	ResponseStatus   *int32    `db:"response_status" json:"response_status"`
	ResponseBody     *string   `db:"response_body" json:"response_body"`
	LastError        *string   `db:"last_error" json:"last_error"`
	ID               uuid.UUID `db:"id" json:"id"`
	WorkerID         *string   `db:"worker_id" json:"worker_id"`
	AutoDisableAfter int32     `db:"auto_disable_after" json:"auto_disable_after"`
}

type MarkWebhookDeliveryFailedRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	EndpointID     uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	Status         string             `db:"status" json:"status"`
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	ReplayCount    int32              `db:"replay_count" json:"replay_count"`
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastAttemptAt  pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	LastReplayedAt pgtype.Timestamptz `db:"last_replayed_at" json:"last_replayed_at"`
	ResponseStatus *int32             `db:"response_status" json:"response_status"`
	ResponseBody   *string            `db:"response_body" json:"response_body"`
	LastError      *string            `db:"last_error" json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	LockedAt       pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy       *string            `db:"locked_by" json:"locked_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) (MarkWebhookDeliveryFailedRow, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliveryFailed,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.LastError,
		arg.ID,
		arg.WorkerID,
		arg.AutoDisableAfter,
	)
	var i MarkWebhookDeliveryFailedRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWebhookDeliverySucceeded = `-- name: MarkWebhookDeliverySucceeded :one
WITH succeeded AS (
    UPDATE webhook_deliveries
    SET status = 'succeeded',
        response_status = $1,
        response_body = $2,
        last_error = NULL,
        delivered_at = now(),
        locked_at = NULL,
        locked_by = NULL,
        updated_at = now()
    WHERE webhook_deliveries.id = $3
      AND locked_by = $4
    RETURNING id, event_id, endpoint_id, status, attempt_count, replay_count, next_attempt_at, last_attempt_at, last_replayed_at, response_status, response_body, last_error, delivered_at, locked_at, locked_by, created_at, updated_at
), reset_endpoint AS (
    UPDATE webhook_endpoints
    SET consecutive_failures = 0,
        last_failure_at = NULL,
        disabled_reason = NULL,
        updated_at = now()
    WHERE webhook_endpoints.id = (SELECT endpoint_id FROM succeeded)
      AND enabled = true
      AND consecutive_failures > 0
    RETURNING webhook_endpoints.id
)
SELECT id, event_id, endpoint_id, status, attempt_count, replay_count, next_attempt_at, last_attempt_at, last_replayed_at, response_status, response_body, last_error, delivered_at, locked_at, locked_by, created_at, updated_at FROM succeeded
`

type MarkWebhookDeliverySucceededParams struct {
	ResponseStatus *int32    `db:"response_status" json:"response_status"`
	ResponseBody   *string   `db:"response_body" json:"response_body"`
	ID             uuid.UUID `db:"id" json:"id"`
	WorkerID       *string   `db:"worker_id" json:"worker_id"`
}

type MarkWebhookDeliverySucceededRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	EndpointID     uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	Status         string             `db:"status" json:"status"`
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	ReplayCount    int32              `db:"replay_count" json:"replay_count"`
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastAttemptAt  pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	LastReplayedAt pgtype.Timestamptz `db:"last_replayed_at" json:"last_replayed_at"`
	ResponseStatus *int32             `db:"response_status" json:"response_status"`
	ResponseBody   *string            `db:"response_body" json:"response_body"`
	LastError      *string            `db:"last_error" json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	LockedAt       pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy       *string            `db:"locked_by" json:"locked_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) MarkWebhookDeliverySucceeded(ctx context.Context, arg MarkWebhookDeliverySucceededParams) (MarkWebhookDeliverySucceededRow, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliverySucceeded,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ID,
		arg.WorkerID,
	)
	var i MarkWebhookDeliverySucceededRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseWebhookDeliveryClaim = `-- name: ReleaseWebhookDeliveryClaim :execrows
UPDATE webhook_deliveries
SET locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
WHERE id = $1
  AND locked_by = $2
`

type ReleaseWebhookDeliveryClaimParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	WorkerID *string   `db:"worker_id" json:"worker_id"`
}

func (q *Queries) ReleaseWebhookDeliveryClaim(ctx context.Context, arg ReleaseWebhookDeliveryClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseWebhookDeliveryClaim, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replayWebhookDelivery = `-- name: ReplayWebhookDelivery :one
UPDATE webhook_deliveries
SET status = 'pending',
    replay_count = webhook_deliveries.replay_count + 1,
    last_replayed_at = now(),
    next_attempt_at = now(),
    response_status = NULL,
    response_body = NULL,
    last_error = NULL,
    delivered_at = NULL,
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
FROM webhook_events,
     webhook_endpoints,
     tenants
WHERE webhook_deliveries.id = $1
  AND webhook_events.id = webhook_deliveries.event_id
  AND webhook_endpoints.id = webhook_deliveries.endpoint_id
  AND tenants.id = webhook_events.tenant_id
  AND webhook_events.tenant_id = $2
  AND tenants.status = 'active'
  AND webhook_endpoints.enabled = true
  AND webhook_endpoints.disabled_at IS NULL
  AND webhook_deliveries.status IN ('succeeded', 'failed', 'canceled')
RETURNING webhook_deliveries.id, webhook_deliveries.event_id, webhook_deliveries.endpoint_id, webhook_deliveries.status, webhook_deliveries.attempt_count, webhook_deliveries.replay_count, webhook_deliveries.next_attempt_at, webhook_deliveries.last_attempt_at, webhook_deliveries.last_replayed_at, webhook_deliveries.response_status, webhook_deliveries.response_body, webhook_deliveries.last_error, webhook_deliveries.delivered_at, webhook_deliveries.locked_at, webhook_deliveries.locked_by, webhook_deliveries.created_at, webhook_deliveries.updated_at
`

type ReplayWebhookDeliveryParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) ReplayWebhookDelivery(ctx context.Context, arg ReplayWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, replayWebhookDelivery, arg.ID, arg.TenantID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retryWebhookDelivery = `-- name: RetryWebhookDelivery :one
UPDATE webhook_deliveries
SET status = 'pending',
    next_attempt_at = now(),
    response_status = NULL,
    response_body = NULL,
    last_error = NULL,
    delivered_at = NULL,
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
FROM webhook_events,
     webhook_endpoints,
     tenants
WHERE webhook_deliveries.id = $1
  AND webhook_events.id = webhook_deliveries.event_id
  AND webhook_endpoints.id = webhook_deliveries.endpoint_id
  AND tenants.id = webhook_events.tenant_id
  AND webhook_events.tenant_id = $2
  AND tenants.status = 'active'
  AND webhook_endpoints.enabled = true
  AND webhook_endpoints.disabled_at IS NULL
  AND webhook_deliveries.status = 'failed'
RETURNING webhook_deliveries.id, webhook_deliveries.event_id, webhook_deliveries.endpoint_id, webhook_deliveries.status, webhook_deliveries.attempt_count, webhook_deliveries.replay_count, webhook_deliveries.next_attempt_at, webhook_deliveries.last_attempt_at, webhook_deliveries.last_replayed_at, webhook_deliveries.response_status, webhook_deliveries.response_body, webhook_deliveries.last_error, webhook_deliveries.delivered_at, webhook_deliveries.locked_at, webhook_deliveries.locked_by, webhook_deliveries.created_at, webhook_deliveries.updated_at
`

type RetryWebhookDeliveryParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) RetryWebhookDelivery(ctx context.Context, arg RetryWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, retryWebhookDelivery, arg.ID, arg.TenantID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const scheduleWebhookDeliveryRetry = `-- name: ScheduleWebhookDeliveryRetry :one
UPDATE webhook_deliveries
SET status = 'retrying',
    next_attempt_at = $1,
    response_status = $2,
    response_body = $3,
    last_error = $4,
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
WHERE id = $5
  AND locked_by = $6
RETURNING id, event_id, endpoint_id, status, attempt_count, replay_count, next_attempt_at, last_attempt_at, last_replayed_at, response_status, response_body, last_error, delivered_at, locked_at, locked_by, created_at, updated_at
`

type ScheduleWebhookDeliveryRetryParams struct {
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	ResponseStatus *int32             `db:"response_status" json:"response_status"`
	ResponseBody   *string            `db:"response_body" json:"response_body"`
	LastError      *string            `db:"last_error" json:"last_error"`
	ID             uuid.UUID          `db:"id" json:"id"`
	WorkerID       *string            `db:"worker_id" json:"worker_id"`
}

func (q *Queries) ScheduleWebhookDeliveryRetry(ctx context.Context, arg ScheduleWebhookDeliveryRetryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, scheduleWebhookDeliveryRetry,
		arg.NextAttemptAt,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.LastError,
		arg.ID,
		arg.WorkerID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
