import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { pretty, render } from "react-email";
import InvitationEmail from "../emails/invitation";
import OTPEmail from "../emails/otp";

// Substitute trusted Go actions only after React has escaped and formatted HTML.
// This preserves date format quotes and placeholders inside link attributes.
const actions = {
  LEAMOUT_CODE_TOKEN: "{{.Code}}",
  LEAMOUT_EXPIRY_TOKEN: '{{.ExpiresAt.UTC.Format "15:04 UTC on 02 Jan 2006"}}',
  LEAMOUT_ORGANIZATION_TOKEN: "{{.Organization}}",
  LEAMOUT_INVITER_TOKEN: "{{.Inviter}}",
  LEAMOUT_ROLE_TOKEN: "{{.Role}}",
  "https://leamout.invalid/LEAMOUT_ACCEPT_URL_TOKEN": "{{.AcceptURL}}",
};

const templates = {
  otp: <OTPEmail code="LEAMOUT_CODE_TOKEN" expiresAt="LEAMOUT_EXPIRY_TOKEN" />,
  invitation: (
    <InvitationEmail
      organization="LEAMOUT_ORGANIZATION_TOKEN"
      inviter="LEAMOUT_INVITER_TOKEN"
      membershipRole="LEAMOUT_ROLE_TOKEN"
      acceptURL="https://leamout.invalid/LEAMOUT_ACCEPT_URL_TOKEN"
      expiresAt="LEAMOUT_EXPIRY_TOKEN"
    />
  ),
};

const check = process.argv.includes("--check");

for (const [name, component] of Object.entries(templates)) {
  let html = await pretty(await render(component));
  for (const [token, action] of Object.entries(actions)) {
    html = html.replaceAll(token, action);
  }
  if (/LEAMOUT_\w+_TOKEN/.test(html)) {
    throw new Error(`Unresolved export token in ${name}`);
  }
  html = `<!-- Generated by @leamout/emails. Edit the React source, then run export. -->\n${html.trim()}\n`;
  const path = fileURLToPath(
    new URL(
      `../../../../server/internal/platform/email/templates/${name}.html`,
      import.meta.url,
    ),
  );
  if (check) {
    if ((await readFile(path, "utf8")) !== html) {
      throw new Error(`${name}.html is stale; run bun run emails:export`);
    }
  } else {
    await writeFile(path, html);
  }
  console.log(`${check ? "Checked" : "Exported"} ${name}.html`);
}
