import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { pretty, render } from "react-email";
import APIKeyExpiryEmail from "../emails/api-key-expiry";
import InvitationEmail from "../emails/invitation";
import InvitationAcceptedEmail from "../emails/invitation-accepted";
import OTPEmail from "../emails/otp";
import SecurityAlertEmail from "../emails/security-alert";
import SIPTrunkFailureEmail from "../emails/sip-trunk-failure";
import VoiceAgentFailureEmail from "../emails/voice-agent-failure";
import WelcomeEmail from "../emails/welcome";

// Substitute trusted Go actions only after React has escaped and formatted HTML.
// This preserves date format quotes and placeholders inside link attributes.
const actions = {
  LEAMOUT_USER_NAME_TOKEN: "{{.UserName}}",
  LEAMOUT_MEMBER_NAME_TOKEN: "{{.MemberName}}",
  LEAMOUT_EVENT_NAME_TOKEN: "{{.EventName}}",
  LEAMOUT_OCCURRED_AT_TOKEN:
    '{{.OccurredAt.UTC.Format "15:04 UTC on 02 Jan 2006"}}',
  LEAMOUT_KEY_NAME_TOKEN: "{{.KeyName}}",
  LEAMOUT_KEY_EXPIRES_AT_TOKEN:
    '{{.KeyExpiresAt.UTC.Format "15:04 UTC on 02 Jan 2006"}}',
  LEAMOUT_TRUNK_NAME_TOKEN: "{{.TrunkName}}",
  LEAMOUT_AGENT_NAME_TOKEN: "{{.AgentName}}",
  LEAMOUT_FAILURE_REASON_TOKEN: "{{.FailureReason}}",

  LEAMOUT_CODE_TOKEN: "{{.Code}}",
  LEAMOUT_EXPIRY_TOKEN: '{{.ExpiresAt.UTC.Format "15:04 UTC on 02 Jan 2006"}}',
  LEAMOUT_ORGANIZATION_TOKEN: "{{.Organization}}",
  LEAMOUT_INVITER_TOKEN: "{{.Inviter}}",
  LEAMOUT_ROLE_TOKEN: "{{.Role}}",
  "https://leamout.invalid/LEAMOUT_ACCEPT_URL_TOKEN": "{{.AcceptURL}}",
};

const templates = {
  welcome: <WelcomeEmail userName="LEAMOUT_USER_NAME_TOKEN" />,
  "invitation-accepted": (
    <InvitationAcceptedEmail
      memberName="LEAMOUT_MEMBER_NAME_TOKEN"
      organization="LEAMOUT_ORGANIZATION_TOKEN"
      membershipRole="LEAMOUT_ROLE_TOKEN"
    />
  ),
  "security-alert": (
    <SecurityAlertEmail
      eventName="LEAMOUT_EVENT_NAME_TOKEN"
      occurredAt="LEAMOUT_OCCURRED_AT_TOKEN"
    />
  ),
  "api-key-expiry": (
    <APIKeyExpiryEmail
      keyName="LEAMOUT_KEY_NAME_TOKEN"
      organization="LEAMOUT_ORGANIZATION_TOKEN"
      keyExpiresAt="LEAMOUT_KEY_EXPIRES_AT_TOKEN"
    />
  ),
  "sip-trunk-failure": (
    <SIPTrunkFailureEmail
      trunkName="LEAMOUT_TRUNK_NAME_TOKEN"
      organization="LEAMOUT_ORGANIZATION_TOKEN"
      failureReason="LEAMOUT_FAILURE_REASON_TOKEN"
      occurredAt="LEAMOUT_OCCURRED_AT_TOKEN"
    />
  ),
  "voice-agent-failure": (
    <VoiceAgentFailureEmail
      agentName="LEAMOUT_AGENT_NAME_TOKEN"
      organization="LEAMOUT_ORGANIZATION_TOKEN"
      failureReason="LEAMOUT_FAILURE_REASON_TOKEN"
      occurredAt="LEAMOUT_OCCURRED_AT_TOKEN"
    />
  ),

  otp: <OTPEmail code="LEAMOUT_CODE_TOKEN" expiresAt="LEAMOUT_EXPIRY_TOKEN" />,
  invitation: (
    <InvitationEmail
      organization="LEAMOUT_ORGANIZATION_TOKEN"
      inviter="LEAMOUT_INVITER_TOKEN"
      membershipRole="LEAMOUT_ROLE_TOKEN"
      acceptURL="https://leamout.invalid/LEAMOUT_ACCEPT_URL_TOKEN"
      expiresAt="LEAMOUT_EXPIRY_TOKEN"
    />
  ),
};

const check = process.argv.includes("--check");

for (const [name, component] of Object.entries(templates)) {
  let html = await pretty(await render(component));
  for (const [token, action] of Object.entries(actions)) {
    html = html.replaceAll(token, action);
  }
  if (/LEAMOUT_\w+_TOKEN/.test(html)) {
    throw new Error(`Unresolved export token in ${name}`);
  }
  html = `<!-- Generated by @leamout/emails. Edit the React source, then run export. -->\n${html.trim()}\n`;
  const path = fileURLToPath(
    new URL(
      `../../../../server/internal/platform/email/templates/${name}.html`,
      import.meta.url,
    ),
  );
  if (check) {
    if ((await readFile(path, "utf8")) !== html) {
      throw new Error(`${name}.html is stale; run bun run emails:export`);
    }
  } else {
    await writeFile(path, html);
  }
  console.log(`${check ? "Checked" : "Exported"} ${name}.html`);
}
